// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_workspace

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func WorkspaceResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"created_iso": schema.StringAttribute{
				Computed: true,
			},
			"creator_id": schema.NumberAttribute{
				Computed: true,
			},
			"creator_name": schema.StringAttribute{
				Computed: true,
			},
			"description": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"has_all_org_members": schema.BoolAttribute{
				Computed: true,
			},
			"id": schema.NumberAttribute{
				Computed: true,
			},
			"is_default": schema.BoolAttribute{
				Computed: true,
			},
			"is_global": schema.BoolAttribute{
				Computed: true,
			},
			"is_restricted": schema.BoolAttribute{
				Required: true,
			},
			"is_visible": schema.BoolAttribute{
				Required: true,
			},
			"member_list": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"email": schema.StringAttribute{
							Computed: true,
						},
						"id": schema.NumberAttribute{
							Computed: true,
						},
						"invited": schema.BoolAttribute{
							Computed: true,
						},
						"name": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: MemberListType{
						ObjectType: types.ObjectType{
							AttrTypes: MemberListValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"membership_approval_required": schema.BoolAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"onboarding_dashboard_id": schema.NumberAttribute{
				Computed: true,
			},
			"project_id": schema.NumberAttribute{
				Computed: true,
			},
			"requesting_user_orgs": schema.ListAttribute{
				ElementType: types.StringType,
				Computed:    true,
			},
			"requesting_user_teams": schema.ListAttribute{
				ElementType: types.StringType,
				Computed:    true,
			},
			"team_list": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.NumberAttribute{
							Computed: true,
						},
						"name": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: TeamListType{
						ObjectType: types.ObjectType{
							AttrTypes: TeamListValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"unified_member_list": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"email": schema.StringAttribute{
							Computed: true,
						},
						"entity_type": schema.StringAttribute{
							Computed: true,
						},
						"id": schema.NumberAttribute{
							Computed: true,
						},
						"invited": schema.BoolAttribute{
							Computed: true,
						},
						"membership_type": schema.StringAttribute{
							Computed: true,
						},
						"name": schema.StringAttribute{
							Computed: true,
						},
						"org_name": schema.StringAttribute{
							Computed: true,
						},
						"team_name": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: UnifiedMemberListType{
						ObjectType: types.ObjectType{
							AttrTypes: UnifiedMemberListValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"workspace_id": schema.Int64Attribute{
				Optional: true,
				Computed: true,
			},
		},
	}
}

type WorkspaceModel struct {
	CreatedIso                 types.String `tfsdk:"created_iso"`
	CreatorId                  types.Number `tfsdk:"creator_id"`
	CreatorName                types.String `tfsdk:"creator_name"`
	Description                types.String `tfsdk:"description"`
	HasAllOrgMembers           types.Bool   `tfsdk:"has_all_org_members"`
	Id                         types.Number `tfsdk:"id"`
	IsDefault                  types.Bool   `tfsdk:"is_default"`
	IsGlobal                   types.Bool   `tfsdk:"is_global"`
	IsRestricted               types.Bool   `tfsdk:"is_restricted"`
	IsVisible                  types.Bool   `tfsdk:"is_visible"`
	MemberList                 types.List   `tfsdk:"member_list"`
	MembershipApprovalRequired types.Bool   `tfsdk:"membership_approval_required"`
	Name                       types.String `tfsdk:"name"`
	OnboardingDashboardId      types.Number `tfsdk:"onboarding_dashboard_id"`
	ProjectId                  types.Number `tfsdk:"project_id"`
	RequestingUserOrgs         types.List   `tfsdk:"requesting_user_orgs"`
	RequestingUserTeams        types.List   `tfsdk:"requesting_user_teams"`
	TeamList                   types.List   `tfsdk:"team_list"`
	UnifiedMemberList          types.List   `tfsdk:"unified_member_list"`
	WorkspaceId                types.Int64  `tfsdk:"workspace_id"`
}

var _ basetypes.ObjectTypable = MemberListType{}

type MemberListType struct {
	basetypes.ObjectType
}

func (t MemberListType) Equal(o attr.Type) bool {
	other, ok := o.(MemberListType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t MemberListType) String() string {
	return "MemberListType"
}

func (t MemberListType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	emailAttribute, ok := attributes["email"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`email is missing from object`)

		return nil, diags
	}

	emailVal, ok := emailAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`email expected to be basetypes.StringValue, was: %T`, emailAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.NumberValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.NumberValue, was: %T`, idAttribute))
	}

	invitedAttribute, ok := attributes["invited"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`invited is missing from object`)

		return nil, diags
	}

	invitedVal, ok := invitedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`invited expected to be basetypes.BoolValue, was: %T`, invitedAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return MemberListValue{
		Email:   emailVal,
		Id:      idVal,
		Invited: invitedVal,
		Name:    nameVal,
		state:   attr.ValueStateKnown,
	}, diags
}

func NewMemberListValueNull() MemberListValue {
	return MemberListValue{
		state: attr.ValueStateNull,
	}
}

func NewMemberListValueUnknown() MemberListValue {
	return MemberListValue{
		state: attr.ValueStateUnknown,
	}
}

func NewMemberListValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (MemberListValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing MemberListValue Attribute Value",
				"While creating a MemberListValue value, a missing attribute value was detected. "+
					"A MemberListValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MemberListValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid MemberListValue Attribute Type",
				"While creating a MemberListValue value, an invalid attribute value was detected. "+
					"A MemberListValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MemberListValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("MemberListValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra MemberListValue Attribute Value",
				"While creating a MemberListValue value, an extra attribute value was detected. "+
					"A MemberListValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra MemberListValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewMemberListValueUnknown(), diags
	}

	emailAttribute, ok := attributes["email"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`email is missing from object`)

		return NewMemberListValueUnknown(), diags
	}

	emailVal, ok := emailAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`email expected to be basetypes.StringValue, was: %T`, emailAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewMemberListValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.NumberValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.NumberValue, was: %T`, idAttribute))
	}

	invitedAttribute, ok := attributes["invited"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`invited is missing from object`)

		return NewMemberListValueUnknown(), diags
	}

	invitedVal, ok := invitedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`invited expected to be basetypes.BoolValue, was: %T`, invitedAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewMemberListValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	if diags.HasError() {
		return NewMemberListValueUnknown(), diags
	}

	return MemberListValue{
		Email:   emailVal,
		Id:      idVal,
		Invited: invitedVal,
		Name:    nameVal,
		state:   attr.ValueStateKnown,
	}, diags
}

func NewMemberListValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) MemberListValue {
	object, diags := NewMemberListValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewMemberListValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t MemberListType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewMemberListValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewMemberListValueUnknown(), nil
	}

	if in.IsNull() {
		return NewMemberListValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewMemberListValueMust(MemberListValue{}.AttributeTypes(ctx), attributes), nil
}

func (t MemberListType) ValueType(ctx context.Context) attr.Value {
	return MemberListValue{}
}

var _ basetypes.ObjectValuable = MemberListValue{}

type MemberListValue struct {
	Email   basetypes.StringValue `tfsdk:"email"`
	Id      basetypes.NumberValue `tfsdk:"id"`
	Invited basetypes.BoolValue   `tfsdk:"invited"`
	Name    basetypes.StringValue `tfsdk:"name"`
	state   attr.ValueState
}

func (v MemberListValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 4)

	var val tftypes.Value
	var err error

	attrTypes["email"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.NumberType{}.TerraformType(ctx)
	attrTypes["invited"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 4)

		val, err = v.Email.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["email"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Invited.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["invited"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v MemberListValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v MemberListValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v MemberListValue) String() string {
	return "MemberListValue"
}

func (v MemberListValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"email":   basetypes.StringType{},
		"id":      basetypes.NumberType{},
		"invited": basetypes.BoolType{},
		"name":    basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"email":   v.Email,
			"id":      v.Id,
			"invited": v.Invited,
			"name":    v.Name,
		})

	return objVal, diags
}

func (v MemberListValue) Equal(o attr.Value) bool {
	other, ok := o.(MemberListValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Email.Equal(other.Email) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Invited.Equal(other.Invited) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	return true
}

func (v MemberListValue) Type(ctx context.Context) attr.Type {
	return MemberListType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v MemberListValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"email":   basetypes.StringType{},
		"id":      basetypes.NumberType{},
		"invited": basetypes.BoolType{},
		"name":    basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = TeamListType{}

type TeamListType struct {
	basetypes.ObjectType
}

func (t TeamListType) Equal(o attr.Type) bool {
	other, ok := o.(TeamListType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t TeamListType) String() string {
	return "TeamListType"
}

func (t TeamListType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.NumberValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.NumberValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return TeamListValue{
		Id:    idVal,
		Name:  nameVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewTeamListValueNull() TeamListValue {
	return TeamListValue{
		state: attr.ValueStateNull,
	}
}

func NewTeamListValueUnknown() TeamListValue {
	return TeamListValue{
		state: attr.ValueStateUnknown,
	}
}

func NewTeamListValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (TeamListValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing TeamListValue Attribute Value",
				"While creating a TeamListValue value, a missing attribute value was detected. "+
					"A TeamListValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TeamListValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid TeamListValue Attribute Type",
				"While creating a TeamListValue value, an invalid attribute value was detected. "+
					"A TeamListValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TeamListValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("TeamListValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra TeamListValue Attribute Value",
				"While creating a TeamListValue value, an extra attribute value was detected. "+
					"A TeamListValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra TeamListValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewTeamListValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewTeamListValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.NumberValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.NumberValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewTeamListValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	if diags.HasError() {
		return NewTeamListValueUnknown(), diags
	}

	return TeamListValue{
		Id:    idVal,
		Name:  nameVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewTeamListValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) TeamListValue {
	object, diags := NewTeamListValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewTeamListValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t TeamListType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewTeamListValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewTeamListValueUnknown(), nil
	}

	if in.IsNull() {
		return NewTeamListValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewTeamListValueMust(TeamListValue{}.AttributeTypes(ctx), attributes), nil
}

func (t TeamListType) ValueType(ctx context.Context) attr.Value {
	return TeamListValue{}
}

var _ basetypes.ObjectValuable = TeamListValue{}

type TeamListValue struct {
	Id    basetypes.NumberValue `tfsdk:"id"`
	Name  basetypes.StringValue `tfsdk:"name"`
	state attr.ValueState
}

func (v TeamListValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.NumberType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v TeamListValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v TeamListValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v TeamListValue) String() string {
	return "TeamListValue"
}

func (v TeamListValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"id":   basetypes.NumberType{},
		"name": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id":   v.Id,
			"name": v.Name,
		})

	return objVal, diags
}

func (v TeamListValue) Equal(o attr.Value) bool {
	other, ok := o.(TeamListValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	return true
}

func (v TeamListValue) Type(ctx context.Context) attr.Type {
	return TeamListType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v TeamListValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id":   basetypes.NumberType{},
		"name": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = UnifiedMemberListType{}

type UnifiedMemberListType struct {
	basetypes.ObjectType
}

func (t UnifiedMemberListType) Equal(o attr.Type) bool {
	other, ok := o.(UnifiedMemberListType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t UnifiedMemberListType) String() string {
	return "UnifiedMemberListType"
}

func (t UnifiedMemberListType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	emailAttribute, ok := attributes["email"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`email is missing from object`)

		return nil, diags
	}

	emailVal, ok := emailAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`email expected to be basetypes.StringValue, was: %T`, emailAttribute))
	}

	entityTypeAttribute, ok := attributes["entity_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`entity_type is missing from object`)

		return nil, diags
	}

	entityTypeVal, ok := entityTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`entity_type expected to be basetypes.StringValue, was: %T`, entityTypeAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.NumberValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.NumberValue, was: %T`, idAttribute))
	}

	invitedAttribute, ok := attributes["invited"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`invited is missing from object`)

		return nil, diags
	}

	invitedVal, ok := invitedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`invited expected to be basetypes.BoolValue, was: %T`, invitedAttribute))
	}

	membershipTypeAttribute, ok := attributes["membership_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`membership_type is missing from object`)

		return nil, diags
	}

	membershipTypeVal, ok := membershipTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`membership_type expected to be basetypes.StringValue, was: %T`, membershipTypeAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	orgNameAttribute, ok := attributes["org_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`org_name is missing from object`)

		return nil, diags
	}

	orgNameVal, ok := orgNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`org_name expected to be basetypes.StringValue, was: %T`, orgNameAttribute))
	}

	teamNameAttribute, ok := attributes["team_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`team_name is missing from object`)

		return nil, diags
	}

	teamNameVal, ok := teamNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`team_name expected to be basetypes.StringValue, was: %T`, teamNameAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return UnifiedMemberListValue{
		Email:          emailVal,
		EntityType:     entityTypeVal,
		Id:             idVal,
		Invited:        invitedVal,
		MembershipType: membershipTypeVal,
		Name:           nameVal,
		OrgName:        orgNameVal,
		TeamName:       teamNameVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewUnifiedMemberListValueNull() UnifiedMemberListValue {
	return UnifiedMemberListValue{
		state: attr.ValueStateNull,
	}
}

func NewUnifiedMemberListValueUnknown() UnifiedMemberListValue {
	return UnifiedMemberListValue{
		state: attr.ValueStateUnknown,
	}
}

func NewUnifiedMemberListValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (UnifiedMemberListValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing UnifiedMemberListValue Attribute Value",
				"While creating a UnifiedMemberListValue value, a missing attribute value was detected. "+
					"A UnifiedMemberListValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("UnifiedMemberListValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid UnifiedMemberListValue Attribute Type",
				"While creating a UnifiedMemberListValue value, an invalid attribute value was detected. "+
					"A UnifiedMemberListValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("UnifiedMemberListValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("UnifiedMemberListValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra UnifiedMemberListValue Attribute Value",
				"While creating a UnifiedMemberListValue value, an extra attribute value was detected. "+
					"A UnifiedMemberListValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra UnifiedMemberListValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewUnifiedMemberListValueUnknown(), diags
	}

	emailAttribute, ok := attributes["email"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`email is missing from object`)

		return NewUnifiedMemberListValueUnknown(), diags
	}

	emailVal, ok := emailAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`email expected to be basetypes.StringValue, was: %T`, emailAttribute))
	}

	entityTypeAttribute, ok := attributes["entity_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`entity_type is missing from object`)

		return NewUnifiedMemberListValueUnknown(), diags
	}

	entityTypeVal, ok := entityTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`entity_type expected to be basetypes.StringValue, was: %T`, entityTypeAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewUnifiedMemberListValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.NumberValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.NumberValue, was: %T`, idAttribute))
	}

	invitedAttribute, ok := attributes["invited"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`invited is missing from object`)

		return NewUnifiedMemberListValueUnknown(), diags
	}

	invitedVal, ok := invitedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`invited expected to be basetypes.BoolValue, was: %T`, invitedAttribute))
	}

	membershipTypeAttribute, ok := attributes["membership_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`membership_type is missing from object`)

		return NewUnifiedMemberListValueUnknown(), diags
	}

	membershipTypeVal, ok := membershipTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`membership_type expected to be basetypes.StringValue, was: %T`, membershipTypeAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewUnifiedMemberListValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	orgNameAttribute, ok := attributes["org_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`org_name is missing from object`)

		return NewUnifiedMemberListValueUnknown(), diags
	}

	orgNameVal, ok := orgNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`org_name expected to be basetypes.StringValue, was: %T`, orgNameAttribute))
	}

	teamNameAttribute, ok := attributes["team_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`team_name is missing from object`)

		return NewUnifiedMemberListValueUnknown(), diags
	}

	teamNameVal, ok := teamNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`team_name expected to be basetypes.StringValue, was: %T`, teamNameAttribute))
	}

	if diags.HasError() {
		return NewUnifiedMemberListValueUnknown(), diags
	}

	return UnifiedMemberListValue{
		Email:          emailVal,
		EntityType:     entityTypeVal,
		Id:             idVal,
		Invited:        invitedVal,
		MembershipType: membershipTypeVal,
		Name:           nameVal,
		OrgName:        orgNameVal,
		TeamName:       teamNameVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewUnifiedMemberListValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) UnifiedMemberListValue {
	object, diags := NewUnifiedMemberListValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewUnifiedMemberListValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t UnifiedMemberListType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewUnifiedMemberListValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewUnifiedMemberListValueUnknown(), nil
	}

	if in.IsNull() {
		return NewUnifiedMemberListValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewUnifiedMemberListValueMust(UnifiedMemberListValue{}.AttributeTypes(ctx), attributes), nil
}

func (t UnifiedMemberListType) ValueType(ctx context.Context) attr.Value {
	return UnifiedMemberListValue{}
}

var _ basetypes.ObjectValuable = UnifiedMemberListValue{}

type UnifiedMemberListValue struct {
	Email          basetypes.StringValue `tfsdk:"email"`
	EntityType     basetypes.StringValue `tfsdk:"entity_type"`
	Id             basetypes.NumberValue `tfsdk:"id"`
	Invited        basetypes.BoolValue   `tfsdk:"invited"`
	MembershipType basetypes.StringValue `tfsdk:"membership_type"`
	Name           basetypes.StringValue `tfsdk:"name"`
	OrgName        basetypes.StringValue `tfsdk:"org_name"`
	TeamName       basetypes.StringValue `tfsdk:"team_name"`
	state          attr.ValueState
}

func (v UnifiedMemberListValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 8)

	var val tftypes.Value
	var err error

	attrTypes["email"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["entity_type"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.NumberType{}.TerraformType(ctx)
	attrTypes["invited"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["membership_type"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["org_name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["team_name"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 8)

		val, err = v.Email.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["email"] = val

		val, err = v.EntityType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["entity_type"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Invited.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["invited"] = val

		val, err = v.MembershipType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["membership_type"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.OrgName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["org_name"] = val

		val, err = v.TeamName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["team_name"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v UnifiedMemberListValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v UnifiedMemberListValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v UnifiedMemberListValue) String() string {
	return "UnifiedMemberListValue"
}

func (v UnifiedMemberListValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"email":           basetypes.StringType{},
		"entity_type":     basetypes.StringType{},
		"id":              basetypes.NumberType{},
		"invited":         basetypes.BoolType{},
		"membership_type": basetypes.StringType{},
		"name":            basetypes.StringType{},
		"org_name":        basetypes.StringType{},
		"team_name":       basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"email":           v.Email,
			"entity_type":     v.EntityType,
			"id":              v.Id,
			"invited":         v.Invited,
			"membership_type": v.MembershipType,
			"name":            v.Name,
			"org_name":        v.OrgName,
			"team_name":       v.TeamName,
		})

	return objVal, diags
}

func (v UnifiedMemberListValue) Equal(o attr.Value) bool {
	other, ok := o.(UnifiedMemberListValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Email.Equal(other.Email) {
		return false
	}

	if !v.EntityType.Equal(other.EntityType) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Invited.Equal(other.Invited) {
		return false
	}

	if !v.MembershipType.Equal(other.MembershipType) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.OrgName.Equal(other.OrgName) {
		return false
	}

	if !v.TeamName.Equal(other.TeamName) {
		return false
	}

	return true
}

func (v UnifiedMemberListValue) Type(ctx context.Context) attr.Type {
	return UnifiedMemberListType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v UnifiedMemberListValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"email":           basetypes.StringType{},
		"entity_type":     basetypes.StringType{},
		"id":              basetypes.NumberType{},
		"invited":         basetypes.BoolType{},
		"membership_type": basetypes.StringType{},
		"name":            basetypes.StringType{},
		"org_name":        basetypes.StringType{},
		"team_name":       basetypes.StringType{},
	}
}
