// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_lexicon_tag

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func LexiconTagResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"color": schema.StringAttribute{
				Optional:            true,
				Description:         "Color code for the tag (optional)",
				MarkdownDescription: "Color code for the tag (optional)",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Description:         "Description of the tag's purpose (optional)",
				MarkdownDescription: "Description of the tag's purpose (optional)",
			},
			"id": schema.Int64Attribute{
				Computed:            true,
				Description:         "The unique tag identifier",
				MarkdownDescription: "The unique tag identifier",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The tag name",
				MarkdownDescription: "The tag name",
			},
			"project_id": schema.Int64Attribute{
				Required:            true,
				Description:         "The project ID",
				MarkdownDescription: "The project ID",
			},
			"tag_id": schema.Int64Attribute{
				Computed:            true,
				Description:         "The tag ID (path parameter)",
				MarkdownDescription: "The tag ID (path parameter)",
			},
		},
	}
}

type LexiconTagModel struct {
	Color       types.String `tfsdk:"color"`
	Description types.String `tfsdk:"description"`
	Id          types.Int64  `tfsdk:"id"`
	Name        types.String `tfsdk:"name"`
	ProjectId   types.Int64  `tfsdk:"project_id"`
	TagId       types.Int64  `tfsdk:"tag_id"`
}
