// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_theme

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func ThemeResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"global_access_type": schema.StringAttribute{
				Optional: true,
				Computed: true,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"off",
						"viewer",
						"editor",
					),
				},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"project_id": schema.Int64Attribute{
				Optional: true,
				Computed: true,
			},
			"theme_id": schema.Int64Attribute{
				Optional: true,
				Computed: true,
			},
			"type": schema.StringAttribute{
				Required: true,
			},
		},
	}
}

type ThemeModel struct {
	GlobalAccessType types.String `tfsdk:"global_access_type"`
	Name             types.String `tfsdk:"name"`
	ProjectId        types.Int64  `tfsdk:"project_id"`
	ThemeId          types.Int64  `tfsdk:"theme_id"`
	Type             types.String `tfsdk:"type"`
}
