// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_playlist

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func PlaylistDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"allow_staff_override": schema.BoolAttribute{
				Computed: true,
			},
			"bookmarked_replays": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"distinct_id": schema.StringAttribute{
							Computed: true,
						},
						"replay_id": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: BookmarkedReplaysType{
						ObjectType: types.ObjectType{
							AttrTypes: BookmarkedReplaysValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"can_pin": schema.BoolAttribute{
				Computed: true,
			},
			"can_share": schema.BoolAttribute{
				Computed: true,
			},
			"can_update_basic": schema.BoolAttribute{
				Computed: true,
			},
			"can_view": schema.BoolAttribute{
				Computed: true,
			},
			"dashboard_id": schema.Int64Attribute{
				Computed: true,
			},
			"description": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.StringAttribute{
				Computed: true,
			},
			"is_shared_with_project": schema.BoolAttribute{
				Computed: true,
			},
			"is_sort_ascending": schema.BoolAttribute{
				Computed: true,
			},
			"is_superadmin": schema.BoolAttribute{
				Computed: true,
			},
			"last_modified_by_email": schema.StringAttribute{
				Computed: true,
			},
			"last_modified_by_id": schema.Int64Attribute{
				Computed: true,
			},
			"last_modified_by_name": schema.StringAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Computed: true,
			},
			"playlist_id": schema.StringAttribute{
				Required: true,
			},
			"project_id": schema.Int64Attribute{
				Required: true,
			},
			"sort_property": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type PlaylistModel struct {
	AllowStaffOverride  types.Bool   `tfsdk:"allow_staff_override"`
	BookmarkedReplays   types.List   `tfsdk:"bookmarked_replays"`
	CanPin              types.Bool   `tfsdk:"can_pin"`
	CanShare            types.Bool   `tfsdk:"can_share"`
	CanUpdateBasic      types.Bool   `tfsdk:"can_update_basic"`
	CanView             types.Bool   `tfsdk:"can_view"`
	DashboardId         types.Int64  `tfsdk:"dashboard_id"`
	Description         types.String `tfsdk:"description"`
	Id                  types.String `tfsdk:"id"`
	IsSharedWithProject types.Bool   `tfsdk:"is_shared_with_project"`
	IsSortAscending     types.Bool   `tfsdk:"is_sort_ascending"`
	IsSuperadmin        types.Bool   `tfsdk:"is_superadmin"`
	LastModifiedByEmail types.String `tfsdk:"last_modified_by_email"`
	LastModifiedById    types.Int64  `tfsdk:"last_modified_by_id"`
	LastModifiedByName  types.String `tfsdk:"last_modified_by_name"`
	Name                types.String `tfsdk:"name"`
	PlaylistId          types.String `tfsdk:"playlist_id"`
	ProjectId           types.Int64  `tfsdk:"project_id"`
	SortProperty        types.String `tfsdk:"sort_property"`
}

var _ basetypes.ObjectTypable = BookmarkedReplaysType{}

type BookmarkedReplaysType struct {
	basetypes.ObjectType
}

func (t BookmarkedReplaysType) Equal(o attr.Type) bool {
	other, ok := o.(BookmarkedReplaysType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t BookmarkedReplaysType) String() string {
	return "BookmarkedReplaysType"
}

func (t BookmarkedReplaysType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	distinctIdAttribute, ok := attributes["distinct_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`distinct_id is missing from object`)

		return nil, diags
	}

	distinctIdVal, ok := distinctIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`distinct_id expected to be basetypes.StringValue, was: %T`, distinctIdAttribute))
	}

	replayIdAttribute, ok := attributes["replay_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`replay_id is missing from object`)

		return nil, diags
	}

	replayIdVal, ok := replayIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`replay_id expected to be basetypes.StringValue, was: %T`, replayIdAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return BookmarkedReplaysValue{
		DistinctId: distinctIdVal,
		ReplayId:   replayIdVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewBookmarkedReplaysValueNull() BookmarkedReplaysValue {
	return BookmarkedReplaysValue{
		state: attr.ValueStateNull,
	}
}

func NewBookmarkedReplaysValueUnknown() BookmarkedReplaysValue {
	return BookmarkedReplaysValue{
		state: attr.ValueStateUnknown,
	}
}

func NewBookmarkedReplaysValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (BookmarkedReplaysValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing BookmarkedReplaysValue Attribute Value",
				"While creating a BookmarkedReplaysValue value, a missing attribute value was detected. "+
					"A BookmarkedReplaysValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("BookmarkedReplaysValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid BookmarkedReplaysValue Attribute Type",
				"While creating a BookmarkedReplaysValue value, an invalid attribute value was detected. "+
					"A BookmarkedReplaysValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("BookmarkedReplaysValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("BookmarkedReplaysValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra BookmarkedReplaysValue Attribute Value",
				"While creating a BookmarkedReplaysValue value, an extra attribute value was detected. "+
					"A BookmarkedReplaysValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra BookmarkedReplaysValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewBookmarkedReplaysValueUnknown(), diags
	}

	distinctIdAttribute, ok := attributes["distinct_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`distinct_id is missing from object`)

		return NewBookmarkedReplaysValueUnknown(), diags
	}

	distinctIdVal, ok := distinctIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`distinct_id expected to be basetypes.StringValue, was: %T`, distinctIdAttribute))
	}

	replayIdAttribute, ok := attributes["replay_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`replay_id is missing from object`)

		return NewBookmarkedReplaysValueUnknown(), diags
	}

	replayIdVal, ok := replayIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`replay_id expected to be basetypes.StringValue, was: %T`, replayIdAttribute))
	}

	if diags.HasError() {
		return NewBookmarkedReplaysValueUnknown(), diags
	}

	return BookmarkedReplaysValue{
		DistinctId: distinctIdVal,
		ReplayId:   replayIdVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewBookmarkedReplaysValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) BookmarkedReplaysValue {
	object, diags := NewBookmarkedReplaysValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewBookmarkedReplaysValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t BookmarkedReplaysType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewBookmarkedReplaysValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewBookmarkedReplaysValueUnknown(), nil
	}

	if in.IsNull() {
		return NewBookmarkedReplaysValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewBookmarkedReplaysValueMust(BookmarkedReplaysValue{}.AttributeTypes(ctx), attributes), nil
}

func (t BookmarkedReplaysType) ValueType(ctx context.Context) attr.Value {
	return BookmarkedReplaysValue{}
}

var _ basetypes.ObjectValuable = BookmarkedReplaysValue{}

type BookmarkedReplaysValue struct {
	DistinctId basetypes.StringValue `tfsdk:"distinct_id"`
	ReplayId   basetypes.StringValue `tfsdk:"replay_id"`
	state      attr.ValueState
}

func (v BookmarkedReplaysValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["distinct_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["replay_id"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.DistinctId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["distinct_id"] = val

		val, err = v.ReplayId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["replay_id"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v BookmarkedReplaysValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v BookmarkedReplaysValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v BookmarkedReplaysValue) String() string {
	return "BookmarkedReplaysValue"
}

func (v BookmarkedReplaysValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"distinct_id": basetypes.StringType{},
		"replay_id":   basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"distinct_id": v.DistinctId,
			"replay_id":   v.ReplayId,
		})

	return objVal, diags
}

func (v BookmarkedReplaysValue) Equal(o attr.Value) bool {
	other, ok := o.(BookmarkedReplaysValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.DistinctId.Equal(other.DistinctId) {
		return false
	}

	if !v.ReplayId.Equal(other.ReplayId) {
		return false
	}

	return true
}

func (v BookmarkedReplaysValue) Type(ctx context.Context) attr.Type {
	return BookmarkedReplaysType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v BookmarkedReplaysValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"distinct_id": basetypes.StringType{},
		"replay_id":   basetypes.StringType{},
	}
}
