// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_org_session_settings

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func OrgSessionSettingsResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"organization_id": schema.Int64Attribute{
				Optional: true,
				Computed: true,
			},
			"settings": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
		},
	}
}

type OrgSessionSettingsModel struct {
	OrganizationId types.Int64  `tfsdk:"organization_id"`
	Settings       types.String `tfsdk:"settings"`
}
