// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_canvas

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func CanvasResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"content_type": schema.StringAttribute{
				Computed: true,
			},
			"created": schema.StringAttribute{
				Computed: true,
			},
			"creator_email": schema.StringAttribute{
				Computed: true,
			},
			"creator_id": schema.Int64Attribute{
				Computed: true,
			},
			"creator_name": schema.StringAttribute{
				Computed: true,
			},
			"description": schema.StringAttribute{
				Optional: true,
				Computed: true,
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 255),
				},
			},
			"id": schema.StringAttribute{
				Computed: true,
			},
			"is_favorited": schema.BoolAttribute{
				Computed: true,
			},
			"last_modified_by_email": schema.StringAttribute{
				Computed: true,
			},
			"last_modified_by_id": schema.Int64Attribute{
				Computed: true,
			},
			"last_modified_by_name": schema.StringAttribute{
				Computed: true,
			},
			"metric_tree_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"modified": schema.StringAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 255),
				},
			},
			"pinned_date": schema.StringAttribute{
				Computed: true,
			},
			"project_id": schema.Int64Attribute{
				Optional: true,
				Computed: true,
			},
			"room_id": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type CanvasModel struct {
	ContentType         types.String `tfsdk:"content_type"`
	Created             types.String `tfsdk:"created"`
	CreatorEmail        types.String `tfsdk:"creator_email"`
	CreatorId           types.Int64  `tfsdk:"creator_id"`
	CreatorName         types.String `tfsdk:"creator_name"`
	Description         types.String `tfsdk:"description"`
	Id                  types.String `tfsdk:"id"`
	IsFavorited         types.Bool   `tfsdk:"is_favorited"`
	LastModifiedByEmail types.String `tfsdk:"last_modified_by_email"`
	LastModifiedById    types.Int64  `tfsdk:"last_modified_by_id"`
	LastModifiedByName  types.String `tfsdk:"last_modified_by_name"`
	MetricTreeId        types.String `tfsdk:"metric_tree_id"`
	Modified            types.String `tfsdk:"modified"`
	Name                types.String `tfsdk:"name"`
	PinnedDate          types.String `tfsdk:"pinned_date"`
	ProjectId           types.Int64  `tfsdk:"project_id"`
	RoomId              types.String `tfsdk:"room_id"`
}
