// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_dashboard

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func DashboardResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"card_order": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"cards": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"action": schema.StringAttribute{
							Optional: true,
							Computed: true,
						},
						"chart_options": schema.SingleNestedAttribute{
							Attributes: map[string]schema.Attribute{
								"type": schema.StringAttribute{
									Optional: true,
									Computed: true,
									Validators: []validator.String{
										stringvalidator.OneOf(
											"bar",
											"line-retention",
											"retention-trend",
											"bar-segmented",
											"bar-stacked",
											"funnel-steps",
											"funnel-trend",
											"funnel-median-ttc",
											"funnel-ttc-bar",
											"funnel-ttc-line",
											"funnel-frequency-bar",
											"funnel-frequency-line",
											"funnel-steps-metric",
											"line",
											"stacked-line",
											"line-stacked",
											"metric",
											"pie",
											"insights-metric",
											"retention-trend-metric",
											"table",
										),
									},
								},
							},
							CustomType: ChartOptionsType{
								ObjectType: types.ObjectType{
									AttrTypes: ChartOptionsValue{}.AttributeTypes(ctx),
								},
							},
							Optional: true,
							Computed: true,
						},
						"id": schema.StringAttribute{
							Optional: true,
							Computed: true,
						},
						"source_bookmark_id": schema.Int64Attribute{
							Optional: true,
							Computed: true,
						},
						"title": schema.StringAttribute{
							Optional: true,
							Computed: true,
						},
						"type": schema.StringAttribute{
							Optional: true,
							Computed: true,
						},
						"width": schema.Int64Attribute{
							Optional: true,
							Computed: true,
						},
					},
					CustomType: CardsType{
						ObjectType: types.ObjectType{
							AttrTypes: CardsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Optional: true,
				Computed: true,
			},
			"created": schema.StringAttribute{
				Computed: true,
			},
			"creator": schema.StringAttribute{
				Computed: true,
			},
			"creator_email": schema.StringAttribute{
				Computed: true,
			},
			"creator_id": schema.Int64Attribute{
				Computed: true,
			},
			"creator_name": schema.StringAttribute{
				Computed: true,
			},
			"dashboard_id": schema.Int64Attribute{
				Optional: true,
				Computed: true,
			},
			"description": schema.StringAttribute{
				Optional: true,
				Computed: true,
				Validators: []validator.String{
					stringvalidator.LengthAtMost(255),
				},
			},
			"duplicate": schema.Int64Attribute{
				Optional: true,
				Computed: true,
			},
			"filters": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"custom_property": schema.StringAttribute{
							Optional: true,
							Computed: true,
						},
						"custom_property_id": schema.StringAttribute{
							Optional: true,
							Computed: true,
						},
						"data_group_id": schema.StringAttribute{
							Optional: true,
							Computed: true,
						},
						"filter_operator": schema.StringAttribute{
							Optional: true,
							Computed: true,
						},
						"filter_value": schema.StringAttribute{
							Optional: true,
							Computed: true,
						},
						"join_property_type": schema.StringAttribute{
							Optional: true,
							Computed: true,
						},
						"list_inclusion": schema.StringAttribute{
							Optional: true,
							Computed: true,
							Validators: []validator.String{
								stringvalidator.OneOf(
									"all",
									"matching",
								),
							},
						},
						"list_quantifier": schema.StringAttribute{
							Optional: true,
							Computed: true,
							Validators: []validator.String{
								stringvalidator.OneOf(
									"any",
									"all",
								),
							},
						},
						"property_default_type": schema.StringAttribute{
							Optional: true,
							Computed: true,
						},
						"property_object_key": schema.StringAttribute{
							Optional: true,
							Computed: true,
						},
						"property_type": schema.StringAttribute{
							Optional: true,
							Computed: true,
						},
						"resource_type": schema.StringAttribute{
							Optional: true,
							Computed: true,
						},
					},
					CustomType: FiltersType{
						ObjectType: types.ObjectType{
							AttrTypes: FiltersValue{}.AttributeTypes(ctx),
						},
					},
				},
				Optional: true,
				Computed: true,
			},
			"generation_type": schema.StringAttribute{
				Optional: true,
				Computed: true,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"User Created",
						"My Dashboard",
						"Template Generated",
						"RCA generated",
						"Staged Template",
						"Copilot Generated",
					),
				},
			},
			"global_access_type": schema.StringAttribute{
				Optional: true,
				Computed: true,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"editor",
						"viewer",
						"off",
					),
				},
			},
			"id": schema.Int64Attribute{
				Computed: true,
			},
			"is_draft": schema.BoolAttribute{
				Optional: true,
				Computed: true,
			},
			"is_favorited": schema.BoolAttribute{
				Computed: true,
			},
			"is_private": schema.BoolAttribute{
				Optional: true,
				Computed: true,
			},
			"is_restricted": schema.BoolAttribute{
				Optional: true,
				Computed: true,
			},
			"layout_version": schema.Int64Attribute{
				Computed: true,
			},
			"modified": schema.StringAttribute{
				Computed: true,
			},
			"pinned_date": schema.StringAttribute{
				Computed: true,
			},
			"project_id": schema.Int64Attribute{
				Optional: true,
				Computed: true,
			},
			"rows": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{},
					CustomType: RowsType{
						ObjectType: types.ObjectType{
							AttrTypes: RowsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Optional: true,
				Computed: true,
			},
			"target_parent_dashboard_id": schema.Int64Attribute{
				Optional: true,
				Computed: true,
			},
			"target_project_id": schema.Int64Attribute{
				Optional: true,
				Computed: true,
			},
			"template_type": schema.StringAttribute{
				Computed: true,
			},
			"time_filter": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"date_range": schema.StringAttribute{
						Optional: true,
						Computed: true,
					},
					"display_text": schema.StringAttribute{
						Optional: true,
						Computed: true,
					},
				},
				CustomType: TimeFilterType{
					ObjectType: types.ObjectType{
						AttrTypes: TimeFilterValue{}.AttributeTypes(ctx),
					},
				},
				Optional:            true,
				Computed:            true,
				Description:         "Mirror of ``api-spec.yml#/components/schemas/TimeFilter``.",
				MarkdownDescription: "Mirror of ``api-spec.yml#/components/schemas/TimeFilter``.",
			},
			"title": schema.StringAttribute{
				Optional: true,
				Computed: true,
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 255),
				},
			},
			"total_view_count": schema.Int64Attribute{
				Computed: true,
			},
			"unique_view_count": schema.Int64Attribute{
				Computed: true,
			},
		},
	}
}

type DashboardModel struct {
	CardOrder               types.List      `tfsdk:"card_order"`
	Cards                   types.List      `tfsdk:"cards"`
	Created                 types.String    `tfsdk:"created"`
	Creator                 types.String    `tfsdk:"creator"`
	CreatorEmail            types.String    `tfsdk:"creator_email"`
	CreatorId               types.Int64     `tfsdk:"creator_id"`
	CreatorName             types.String    `tfsdk:"creator_name"`
	DashboardId             types.Int64     `tfsdk:"dashboard_id"`
	Description             types.String    `tfsdk:"description"`
	Duplicate               types.Int64     `tfsdk:"duplicate"`
	Filters                 types.List      `tfsdk:"filters"`
	GenerationType          types.String    `tfsdk:"generation_type"`
	GlobalAccessType        types.String    `tfsdk:"global_access_type"`
	Id                      types.Int64     `tfsdk:"id"`
	IsDraft                 types.Bool      `tfsdk:"is_draft"`
	IsFavorited             types.Bool      `tfsdk:"is_favorited"`
	IsPrivate               types.Bool      `tfsdk:"is_private"`
	IsRestricted            types.Bool      `tfsdk:"is_restricted"`
	LayoutVersion           types.Int64     `tfsdk:"layout_version"`
	Modified                types.String    `tfsdk:"modified"`
	PinnedDate              types.String    `tfsdk:"pinned_date"`
	ProjectId               types.Int64     `tfsdk:"project_id"`
	Rows                    types.List      `tfsdk:"rows"`
	TargetParentDashboardId types.Int64     `tfsdk:"target_parent_dashboard_id"`
	TargetProjectId         types.Int64     `tfsdk:"target_project_id"`
	TemplateType            types.String    `tfsdk:"template_type"`
	TimeFilter              TimeFilterValue `tfsdk:"time_filter"`
	Title                   types.String    `tfsdk:"title"`
	TotalViewCount          types.Int64     `tfsdk:"total_view_count"`
	UniqueViewCount         types.Int64     `tfsdk:"unique_view_count"`
}

var _ basetypes.ObjectTypable = CardsType{}

type CardsType struct {
	basetypes.ObjectType
}

func (t CardsType) Equal(o attr.Type) bool {
	other, ok := o.(CardsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t CardsType) String() string {
	return "CardsType"
}

func (t CardsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	actionAttribute, ok := attributes["action"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`action is missing from object`)

		return nil, diags
	}

	actionVal, ok := actionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`action expected to be basetypes.StringValue, was: %T`, actionAttribute))
	}

	chartOptionsAttribute, ok := attributes["chart_options"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`chart_options is missing from object`)

		return nil, diags
	}

	chartOptionsVal, ok := chartOptionsAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`chart_options expected to be basetypes.ObjectValue, was: %T`, chartOptionsAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	sourceBookmarkIdAttribute, ok := attributes["source_bookmark_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`source_bookmark_id is missing from object`)

		return nil, diags
	}

	sourceBookmarkIdVal, ok := sourceBookmarkIdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`source_bookmark_id expected to be basetypes.Int64Value, was: %T`, sourceBookmarkIdAttribute))
	}

	titleAttribute, ok := attributes["title"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`title is missing from object`)

		return nil, diags
	}

	titleVal, ok := titleAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`title expected to be basetypes.StringValue, was: %T`, titleAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	widthAttribute, ok := attributes["width"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`width is missing from object`)

		return nil, diags
	}

	widthVal, ok := widthAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`width expected to be basetypes.Int64Value, was: %T`, widthAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return CardsValue{
		Action:           actionVal,
		ChartOptions:     chartOptionsVal,
		Id:               idVal,
		SourceBookmarkId: sourceBookmarkIdVal,
		Title:            titleVal,
		CardsType:        typeVal,
		Width:            widthVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewCardsValueNull() CardsValue {
	return CardsValue{
		state: attr.ValueStateNull,
	}
}

func NewCardsValueUnknown() CardsValue {
	return CardsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewCardsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (CardsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing CardsValue Attribute Value",
				"While creating a CardsValue value, a missing attribute value was detected. "+
					"A CardsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CardsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid CardsValue Attribute Type",
				"While creating a CardsValue value, an invalid attribute value was detected. "+
					"A CardsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CardsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("CardsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra CardsValue Attribute Value",
				"While creating a CardsValue value, an extra attribute value was detected. "+
					"A CardsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra CardsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewCardsValueUnknown(), diags
	}

	actionAttribute, ok := attributes["action"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`action is missing from object`)

		return NewCardsValueUnknown(), diags
	}

	actionVal, ok := actionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`action expected to be basetypes.StringValue, was: %T`, actionAttribute))
	}

	chartOptionsAttribute, ok := attributes["chart_options"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`chart_options is missing from object`)

		return NewCardsValueUnknown(), diags
	}

	chartOptionsVal, ok := chartOptionsAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`chart_options expected to be basetypes.ObjectValue, was: %T`, chartOptionsAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewCardsValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	sourceBookmarkIdAttribute, ok := attributes["source_bookmark_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`source_bookmark_id is missing from object`)

		return NewCardsValueUnknown(), diags
	}

	sourceBookmarkIdVal, ok := sourceBookmarkIdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`source_bookmark_id expected to be basetypes.Int64Value, was: %T`, sourceBookmarkIdAttribute))
	}

	titleAttribute, ok := attributes["title"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`title is missing from object`)

		return NewCardsValueUnknown(), diags
	}

	titleVal, ok := titleAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`title expected to be basetypes.StringValue, was: %T`, titleAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewCardsValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	widthAttribute, ok := attributes["width"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`width is missing from object`)

		return NewCardsValueUnknown(), diags
	}

	widthVal, ok := widthAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`width expected to be basetypes.Int64Value, was: %T`, widthAttribute))
	}

	if diags.HasError() {
		return NewCardsValueUnknown(), diags
	}

	return CardsValue{
		Action:           actionVal,
		ChartOptions:     chartOptionsVal,
		Id:               idVal,
		SourceBookmarkId: sourceBookmarkIdVal,
		Title:            titleVal,
		CardsType:        typeVal,
		Width:            widthVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewCardsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) CardsValue {
	object, diags := NewCardsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewCardsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t CardsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewCardsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewCardsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewCardsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewCardsValueMust(CardsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t CardsType) ValueType(ctx context.Context) attr.Value {
	return CardsValue{}
}

var _ basetypes.ObjectValuable = CardsValue{}

type CardsValue struct {
	Action           basetypes.StringValue `tfsdk:"action"`
	ChartOptions     basetypes.ObjectValue `tfsdk:"chart_options"`
	Id               basetypes.StringValue `tfsdk:"id"`
	SourceBookmarkId basetypes.Int64Value  `tfsdk:"source_bookmark_id"`
	Title            basetypes.StringValue `tfsdk:"title"`
	CardsType        basetypes.StringValue `tfsdk:"type"`
	Width            basetypes.Int64Value  `tfsdk:"width"`
	state            attr.ValueState
}

func (v CardsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 7)

	var val tftypes.Value
	var err error

	attrTypes["action"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["chart_options"] = basetypes.ObjectType{
		AttrTypes: ChartOptionsValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["source_bookmark_id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["title"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["width"] = basetypes.Int64Type{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 7)

		val, err = v.Action.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["action"] = val

		val, err = v.ChartOptions.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["chart_options"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.SourceBookmarkId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["source_bookmark_id"] = val

		val, err = v.Title.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["title"] = val

		val, err = v.CardsType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		val, err = v.Width.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["width"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v CardsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v CardsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v CardsValue) String() string {
	return "CardsValue"
}

func (v CardsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var chartOptions basetypes.ObjectValue

	if v.ChartOptions.IsNull() {
		chartOptions = types.ObjectNull(
			ChartOptionsValue{}.AttributeTypes(ctx),
		)
	}

	if v.ChartOptions.IsUnknown() {
		chartOptions = types.ObjectUnknown(
			ChartOptionsValue{}.AttributeTypes(ctx),
		)
	}

	if !v.ChartOptions.IsNull() && !v.ChartOptions.IsUnknown() {
		chartOptions = types.ObjectValueMust(
			ChartOptionsValue{}.AttributeTypes(ctx),
			v.ChartOptions.Attributes(),
		)
	}

	attributeTypes := map[string]attr.Type{
		"action": basetypes.StringType{},
		"chart_options": basetypes.ObjectType{
			AttrTypes: ChartOptionsValue{}.AttributeTypes(ctx),
		},
		"id":                 basetypes.StringType{},
		"source_bookmark_id": basetypes.Int64Type{},
		"title":              basetypes.StringType{},
		"type":               basetypes.StringType{},
		"width":              basetypes.Int64Type{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"action":             v.Action,
			"chart_options":      chartOptions,
			"id":                 v.Id,
			"source_bookmark_id": v.SourceBookmarkId,
			"title":              v.Title,
			"type":               v.CardsType,
			"width":              v.Width,
		})

	return objVal, diags
}

func (v CardsValue) Equal(o attr.Value) bool {
	other, ok := o.(CardsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Action.Equal(other.Action) {
		return false
	}

	if !v.ChartOptions.Equal(other.ChartOptions) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.SourceBookmarkId.Equal(other.SourceBookmarkId) {
		return false
	}

	if !v.Title.Equal(other.Title) {
		return false
	}

	if !v.CardsType.Equal(other.CardsType) {
		return false
	}

	if !v.Width.Equal(other.Width) {
		return false
	}

	return true
}

func (v CardsValue) Type(ctx context.Context) attr.Type {
	return CardsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v CardsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"action": basetypes.StringType{},
		"chart_options": basetypes.ObjectType{
			AttrTypes: ChartOptionsValue{}.AttributeTypes(ctx),
		},
		"id":                 basetypes.StringType{},
		"source_bookmark_id": basetypes.Int64Type{},
		"title":              basetypes.StringType{},
		"type":               basetypes.StringType{},
		"width":              basetypes.Int64Type{},
	}
}

var _ basetypes.ObjectTypable = ChartOptionsType{}

type ChartOptionsType struct {
	basetypes.ObjectType
}

func (t ChartOptionsType) Equal(o attr.Type) bool {
	other, ok := o.(ChartOptionsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ChartOptionsType) String() string {
	return "ChartOptionsType"
}

func (t ChartOptionsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ChartOptionsValue{
		ChartOptionsType: typeVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewChartOptionsValueNull() ChartOptionsValue {
	return ChartOptionsValue{
		state: attr.ValueStateNull,
	}
}

func NewChartOptionsValueUnknown() ChartOptionsValue {
	return ChartOptionsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewChartOptionsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ChartOptionsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ChartOptionsValue Attribute Value",
				"While creating a ChartOptionsValue value, a missing attribute value was detected. "+
					"A ChartOptionsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ChartOptionsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ChartOptionsValue Attribute Type",
				"While creating a ChartOptionsValue value, an invalid attribute value was detected. "+
					"A ChartOptionsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ChartOptionsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ChartOptionsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ChartOptionsValue Attribute Value",
				"While creating a ChartOptionsValue value, an extra attribute value was detected. "+
					"A ChartOptionsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ChartOptionsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewChartOptionsValueUnknown(), diags
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewChartOptionsValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewChartOptionsValueUnknown(), diags
	}

	return ChartOptionsValue{
		ChartOptionsType: typeVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewChartOptionsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ChartOptionsValue {
	object, diags := NewChartOptionsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewChartOptionsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ChartOptionsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewChartOptionsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewChartOptionsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewChartOptionsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewChartOptionsValueMust(ChartOptionsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ChartOptionsType) ValueType(ctx context.Context) attr.Value {
	return ChartOptionsValue{}
}

var _ basetypes.ObjectValuable = ChartOptionsValue{}

type ChartOptionsValue struct {
	ChartOptionsType basetypes.StringValue `tfsdk:"type"`
	state            attr.ValueState
}

func (v ChartOptionsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.ChartOptionsType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ChartOptionsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ChartOptionsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ChartOptionsValue) String() string {
	return "ChartOptionsValue"
}

func (v ChartOptionsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"type": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"type": v.ChartOptionsType,
		})

	return objVal, diags
}

func (v ChartOptionsValue) Equal(o attr.Value) bool {
	other, ok := o.(ChartOptionsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.ChartOptionsType.Equal(other.ChartOptionsType) {
		return false
	}

	return true
}

func (v ChartOptionsValue) Type(ctx context.Context) attr.Type {
	return ChartOptionsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ChartOptionsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"type": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = FiltersType{}

type FiltersType struct {
	basetypes.ObjectType
}

func (t FiltersType) Equal(o attr.Type) bool {
	other, ok := o.(FiltersType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t FiltersType) String() string {
	return "FiltersType"
}

func (t FiltersType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	customPropertyAttribute, ok := attributes["custom_property"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`custom_property is missing from object`)

		return nil, diags
	}

	customPropertyVal, ok := customPropertyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`custom_property expected to be basetypes.StringValue, was: %T`, customPropertyAttribute))
	}

	customPropertyIdAttribute, ok := attributes["custom_property_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`custom_property_id is missing from object`)

		return nil, diags
	}

	customPropertyIdVal, ok := customPropertyIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`custom_property_id expected to be basetypes.StringValue, was: %T`, customPropertyIdAttribute))
	}

	dataGroupIdAttribute, ok := attributes["data_group_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`data_group_id is missing from object`)

		return nil, diags
	}

	dataGroupIdVal, ok := dataGroupIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`data_group_id expected to be basetypes.StringValue, was: %T`, dataGroupIdAttribute))
	}

	filterOperatorAttribute, ok := attributes["filter_operator"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`filter_operator is missing from object`)

		return nil, diags
	}

	filterOperatorVal, ok := filterOperatorAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`filter_operator expected to be basetypes.StringValue, was: %T`, filterOperatorAttribute))
	}

	filterValueAttribute, ok := attributes["filter_value"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`filter_value is missing from object`)

		return nil, diags
	}

	filterValueVal, ok := filterValueAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`filter_value expected to be basetypes.StringValue, was: %T`, filterValueAttribute))
	}

	joinPropertyTypeAttribute, ok := attributes["join_property_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`join_property_type is missing from object`)

		return nil, diags
	}

	joinPropertyTypeVal, ok := joinPropertyTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`join_property_type expected to be basetypes.StringValue, was: %T`, joinPropertyTypeAttribute))
	}

	listInclusionAttribute, ok := attributes["list_inclusion"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`list_inclusion is missing from object`)

		return nil, diags
	}

	listInclusionVal, ok := listInclusionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`list_inclusion expected to be basetypes.StringValue, was: %T`, listInclusionAttribute))
	}

	listQuantifierAttribute, ok := attributes["list_quantifier"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`list_quantifier is missing from object`)

		return nil, diags
	}

	listQuantifierVal, ok := listQuantifierAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`list_quantifier expected to be basetypes.StringValue, was: %T`, listQuantifierAttribute))
	}

	propertyDefaultTypeAttribute, ok := attributes["property_default_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`property_default_type is missing from object`)

		return nil, diags
	}

	propertyDefaultTypeVal, ok := propertyDefaultTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`property_default_type expected to be basetypes.StringValue, was: %T`, propertyDefaultTypeAttribute))
	}

	propertyObjectKeyAttribute, ok := attributes["property_object_key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`property_object_key is missing from object`)

		return nil, diags
	}

	propertyObjectKeyVal, ok := propertyObjectKeyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`property_object_key expected to be basetypes.StringValue, was: %T`, propertyObjectKeyAttribute))
	}

	propertyTypeAttribute, ok := attributes["property_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`property_type is missing from object`)

		return nil, diags
	}

	propertyTypeVal, ok := propertyTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`property_type expected to be basetypes.StringValue, was: %T`, propertyTypeAttribute))
	}

	resourceTypeAttribute, ok := attributes["resource_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`resource_type is missing from object`)

		return nil, diags
	}

	resourceTypeVal, ok := resourceTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`resource_type expected to be basetypes.StringValue, was: %T`, resourceTypeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return FiltersValue{
		CustomProperty:      customPropertyVal,
		CustomPropertyId:    customPropertyIdVal,
		DataGroupId:         dataGroupIdVal,
		FilterOperator:      filterOperatorVal,
		FilterValue:         filterValueVal,
		JoinPropertyType:    joinPropertyTypeVal,
		ListInclusion:       listInclusionVal,
		ListQuantifier:      listQuantifierVal,
		PropertyDefaultType: propertyDefaultTypeVal,
		PropertyObjectKey:   propertyObjectKeyVal,
		PropertyType:        propertyTypeVal,
		ResourceType:        resourceTypeVal,
		state:               attr.ValueStateKnown,
	}, diags
}

func NewFiltersValueNull() FiltersValue {
	return FiltersValue{
		state: attr.ValueStateNull,
	}
}

func NewFiltersValueUnknown() FiltersValue {
	return FiltersValue{
		state: attr.ValueStateUnknown,
	}
}

func NewFiltersValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (FiltersValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing FiltersValue Attribute Value",
				"While creating a FiltersValue value, a missing attribute value was detected. "+
					"A FiltersValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("FiltersValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid FiltersValue Attribute Type",
				"While creating a FiltersValue value, an invalid attribute value was detected. "+
					"A FiltersValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("FiltersValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("FiltersValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra FiltersValue Attribute Value",
				"While creating a FiltersValue value, an extra attribute value was detected. "+
					"A FiltersValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra FiltersValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewFiltersValueUnknown(), diags
	}

	customPropertyAttribute, ok := attributes["custom_property"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`custom_property is missing from object`)

		return NewFiltersValueUnknown(), diags
	}

	customPropertyVal, ok := customPropertyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`custom_property expected to be basetypes.StringValue, was: %T`, customPropertyAttribute))
	}

	customPropertyIdAttribute, ok := attributes["custom_property_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`custom_property_id is missing from object`)

		return NewFiltersValueUnknown(), diags
	}

	customPropertyIdVal, ok := customPropertyIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`custom_property_id expected to be basetypes.StringValue, was: %T`, customPropertyIdAttribute))
	}

	dataGroupIdAttribute, ok := attributes["data_group_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`data_group_id is missing from object`)

		return NewFiltersValueUnknown(), diags
	}

	dataGroupIdVal, ok := dataGroupIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`data_group_id expected to be basetypes.StringValue, was: %T`, dataGroupIdAttribute))
	}

	filterOperatorAttribute, ok := attributes["filter_operator"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`filter_operator is missing from object`)

		return NewFiltersValueUnknown(), diags
	}

	filterOperatorVal, ok := filterOperatorAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`filter_operator expected to be basetypes.StringValue, was: %T`, filterOperatorAttribute))
	}

	filterValueAttribute, ok := attributes["filter_value"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`filter_value is missing from object`)

		return NewFiltersValueUnknown(), diags
	}

	filterValueVal, ok := filterValueAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`filter_value expected to be basetypes.StringValue, was: %T`, filterValueAttribute))
	}

	joinPropertyTypeAttribute, ok := attributes["join_property_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`join_property_type is missing from object`)

		return NewFiltersValueUnknown(), diags
	}

	joinPropertyTypeVal, ok := joinPropertyTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`join_property_type expected to be basetypes.StringValue, was: %T`, joinPropertyTypeAttribute))
	}

	listInclusionAttribute, ok := attributes["list_inclusion"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`list_inclusion is missing from object`)

		return NewFiltersValueUnknown(), diags
	}

	listInclusionVal, ok := listInclusionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`list_inclusion expected to be basetypes.StringValue, was: %T`, listInclusionAttribute))
	}

	listQuantifierAttribute, ok := attributes["list_quantifier"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`list_quantifier is missing from object`)

		return NewFiltersValueUnknown(), diags
	}

	listQuantifierVal, ok := listQuantifierAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`list_quantifier expected to be basetypes.StringValue, was: %T`, listQuantifierAttribute))
	}

	propertyDefaultTypeAttribute, ok := attributes["property_default_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`property_default_type is missing from object`)

		return NewFiltersValueUnknown(), diags
	}

	propertyDefaultTypeVal, ok := propertyDefaultTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`property_default_type expected to be basetypes.StringValue, was: %T`, propertyDefaultTypeAttribute))
	}

	propertyObjectKeyAttribute, ok := attributes["property_object_key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`property_object_key is missing from object`)

		return NewFiltersValueUnknown(), diags
	}

	propertyObjectKeyVal, ok := propertyObjectKeyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`property_object_key expected to be basetypes.StringValue, was: %T`, propertyObjectKeyAttribute))
	}

	propertyTypeAttribute, ok := attributes["property_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`property_type is missing from object`)

		return NewFiltersValueUnknown(), diags
	}

	propertyTypeVal, ok := propertyTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`property_type expected to be basetypes.StringValue, was: %T`, propertyTypeAttribute))
	}

	resourceTypeAttribute, ok := attributes["resource_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`resource_type is missing from object`)

		return NewFiltersValueUnknown(), diags
	}

	resourceTypeVal, ok := resourceTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`resource_type expected to be basetypes.StringValue, was: %T`, resourceTypeAttribute))
	}

	if diags.HasError() {
		return NewFiltersValueUnknown(), diags
	}

	return FiltersValue{
		CustomProperty:      customPropertyVal,
		CustomPropertyId:    customPropertyIdVal,
		DataGroupId:         dataGroupIdVal,
		FilterOperator:      filterOperatorVal,
		FilterValue:         filterValueVal,
		JoinPropertyType:    joinPropertyTypeVal,
		ListInclusion:       listInclusionVal,
		ListQuantifier:      listQuantifierVal,
		PropertyDefaultType: propertyDefaultTypeVal,
		PropertyObjectKey:   propertyObjectKeyVal,
		PropertyType:        propertyTypeVal,
		ResourceType:        resourceTypeVal,
		state:               attr.ValueStateKnown,
	}, diags
}

func NewFiltersValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) FiltersValue {
	object, diags := NewFiltersValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewFiltersValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t FiltersType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewFiltersValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewFiltersValueUnknown(), nil
	}

	if in.IsNull() {
		return NewFiltersValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewFiltersValueMust(FiltersValue{}.AttributeTypes(ctx), attributes), nil
}

func (t FiltersType) ValueType(ctx context.Context) attr.Value {
	return FiltersValue{}
}

var _ basetypes.ObjectValuable = FiltersValue{}

type FiltersValue struct {
	CustomProperty      basetypes.StringValue `tfsdk:"custom_property"`
	CustomPropertyId    basetypes.StringValue `tfsdk:"custom_property_id"`
	DataGroupId         basetypes.StringValue `tfsdk:"data_group_id"`
	FilterOperator      basetypes.StringValue `tfsdk:"filter_operator"`
	FilterValue         basetypes.StringValue `tfsdk:"filter_value"`
	JoinPropertyType    basetypes.StringValue `tfsdk:"join_property_type"`
	ListInclusion       basetypes.StringValue `tfsdk:"list_inclusion"`
	ListQuantifier      basetypes.StringValue `tfsdk:"list_quantifier"`
	PropertyDefaultType basetypes.StringValue `tfsdk:"property_default_type"`
	PropertyObjectKey   basetypes.StringValue `tfsdk:"property_object_key"`
	PropertyType        basetypes.StringValue `tfsdk:"property_type"`
	ResourceType        basetypes.StringValue `tfsdk:"resource_type"`
	state               attr.ValueState
}

func (v FiltersValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 12)

	var val tftypes.Value
	var err error

	attrTypes["custom_property"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["custom_property_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["data_group_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["filter_operator"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["filter_value"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["join_property_type"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["list_inclusion"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["list_quantifier"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["property_default_type"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["property_object_key"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["property_type"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["resource_type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 12)

		val, err = v.CustomProperty.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["custom_property"] = val

		val, err = v.CustomPropertyId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["custom_property_id"] = val

		val, err = v.DataGroupId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["data_group_id"] = val

		val, err = v.FilterOperator.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["filter_operator"] = val

		val, err = v.FilterValue.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["filter_value"] = val

		val, err = v.JoinPropertyType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["join_property_type"] = val

		val, err = v.ListInclusion.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["list_inclusion"] = val

		val, err = v.ListQuantifier.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["list_quantifier"] = val

		val, err = v.PropertyDefaultType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["property_default_type"] = val

		val, err = v.PropertyObjectKey.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["property_object_key"] = val

		val, err = v.PropertyType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["property_type"] = val

		val, err = v.ResourceType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["resource_type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v FiltersValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v FiltersValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v FiltersValue) String() string {
	return "FiltersValue"
}

func (v FiltersValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"custom_property":       basetypes.StringType{},
		"custom_property_id":    basetypes.StringType{},
		"data_group_id":         basetypes.StringType{},
		"filter_operator":       basetypes.StringType{},
		"filter_value":          basetypes.StringType{},
		"join_property_type":    basetypes.StringType{},
		"list_inclusion":        basetypes.StringType{},
		"list_quantifier":       basetypes.StringType{},
		"property_default_type": basetypes.StringType{},
		"property_object_key":   basetypes.StringType{},
		"property_type":         basetypes.StringType{},
		"resource_type":         basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"custom_property":       v.CustomProperty,
			"custom_property_id":    v.CustomPropertyId,
			"data_group_id":         v.DataGroupId,
			"filter_operator":       v.FilterOperator,
			"filter_value":          v.FilterValue,
			"join_property_type":    v.JoinPropertyType,
			"list_inclusion":        v.ListInclusion,
			"list_quantifier":       v.ListQuantifier,
			"property_default_type": v.PropertyDefaultType,
			"property_object_key":   v.PropertyObjectKey,
			"property_type":         v.PropertyType,
			"resource_type":         v.ResourceType,
		})

	return objVal, diags
}

func (v FiltersValue) Equal(o attr.Value) bool {
	other, ok := o.(FiltersValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.CustomProperty.Equal(other.CustomProperty) {
		return false
	}

	if !v.CustomPropertyId.Equal(other.CustomPropertyId) {
		return false
	}

	if !v.DataGroupId.Equal(other.DataGroupId) {
		return false
	}

	if !v.FilterOperator.Equal(other.FilterOperator) {
		return false
	}

	if !v.FilterValue.Equal(other.FilterValue) {
		return false
	}

	if !v.JoinPropertyType.Equal(other.JoinPropertyType) {
		return false
	}

	if !v.ListInclusion.Equal(other.ListInclusion) {
		return false
	}

	if !v.ListQuantifier.Equal(other.ListQuantifier) {
		return false
	}

	if !v.PropertyDefaultType.Equal(other.PropertyDefaultType) {
		return false
	}

	if !v.PropertyObjectKey.Equal(other.PropertyObjectKey) {
		return false
	}

	if !v.PropertyType.Equal(other.PropertyType) {
		return false
	}

	if !v.ResourceType.Equal(other.ResourceType) {
		return false
	}

	return true
}

func (v FiltersValue) Type(ctx context.Context) attr.Type {
	return FiltersType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v FiltersValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"custom_property":       basetypes.StringType{},
		"custom_property_id":    basetypes.StringType{},
		"data_group_id":         basetypes.StringType{},
		"filter_operator":       basetypes.StringType{},
		"filter_value":          basetypes.StringType{},
		"join_property_type":    basetypes.StringType{},
		"list_inclusion":        basetypes.StringType{},
		"list_quantifier":       basetypes.StringType{},
		"property_default_type": basetypes.StringType{},
		"property_object_key":   basetypes.StringType{},
		"property_type":         basetypes.StringType{},
		"resource_type":         basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = RowsType{}

type RowsType struct {
	basetypes.ObjectType
}

func (t RowsType) Equal(o attr.Type) bool {
	other, ok := o.(RowsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t RowsType) String() string {
	return "RowsType"
}

func (t RowsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if diags.HasError() {
		return nil, diags
	}

	return RowsValue{
		state: attr.ValueStateKnown,
	}, diags
}

func NewRowsValueNull() RowsValue {
	return RowsValue{
		state: attr.ValueStateNull,
	}
}

func NewRowsValueUnknown() RowsValue {
	return RowsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewRowsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (RowsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing RowsValue Attribute Value",
				"While creating a RowsValue value, a missing attribute value was detected. "+
					"A RowsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("RowsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid RowsValue Attribute Type",
				"While creating a RowsValue value, an invalid attribute value was detected. "+
					"A RowsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("RowsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("RowsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra RowsValue Attribute Value",
				"While creating a RowsValue value, an extra attribute value was detected. "+
					"A RowsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra RowsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewRowsValueUnknown(), diags
	}

	if diags.HasError() {
		return NewRowsValueUnknown(), diags
	}

	return RowsValue{
		state: attr.ValueStateKnown,
	}, diags
}

func NewRowsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) RowsValue {
	object, diags := NewRowsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewRowsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t RowsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewRowsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewRowsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewRowsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewRowsValueMust(RowsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t RowsType) ValueType(ctx context.Context) attr.Value {
	return RowsValue{}
}

var _ basetypes.ObjectValuable = RowsValue{}

type RowsValue struct {
	state attr.ValueState
}

func (v RowsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 0)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 0)

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v RowsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v RowsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v RowsValue) String() string {
	return "RowsValue"
}

func (v RowsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{})

	return objVal, diags
}

func (v RowsValue) Equal(o attr.Value) bool {
	other, ok := o.(RowsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	return true
}

func (v RowsValue) Type(ctx context.Context) attr.Type {
	return RowsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v RowsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{}
}

var _ basetypes.ObjectTypable = TimeFilterType{}

type TimeFilterType struct {
	basetypes.ObjectType
}

func (t TimeFilterType) Equal(o attr.Type) bool {
	other, ok := o.(TimeFilterType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t TimeFilterType) String() string {
	return "TimeFilterType"
}

func (t TimeFilterType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	dateRangeAttribute, ok := attributes["date_range"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`date_range is missing from object`)

		return nil, diags
	}

	dateRangeVal, ok := dateRangeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`date_range expected to be basetypes.StringValue, was: %T`, dateRangeAttribute))
	}

	displayTextAttribute, ok := attributes["display_text"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`display_text is missing from object`)

		return nil, diags
	}

	displayTextVal, ok := displayTextAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`display_text expected to be basetypes.StringValue, was: %T`, displayTextAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return TimeFilterValue{
		DateRange:   dateRangeVal,
		DisplayText: displayTextVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewTimeFilterValueNull() TimeFilterValue {
	return TimeFilterValue{
		state: attr.ValueStateNull,
	}
}

func NewTimeFilterValueUnknown() TimeFilterValue {
	return TimeFilterValue{
		state: attr.ValueStateUnknown,
	}
}

func NewTimeFilterValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (TimeFilterValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing TimeFilterValue Attribute Value",
				"While creating a TimeFilterValue value, a missing attribute value was detected. "+
					"A TimeFilterValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TimeFilterValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid TimeFilterValue Attribute Type",
				"While creating a TimeFilterValue value, an invalid attribute value was detected. "+
					"A TimeFilterValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TimeFilterValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("TimeFilterValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra TimeFilterValue Attribute Value",
				"While creating a TimeFilterValue value, an extra attribute value was detected. "+
					"A TimeFilterValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra TimeFilterValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewTimeFilterValueUnknown(), diags
	}

	dateRangeAttribute, ok := attributes["date_range"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`date_range is missing from object`)

		return NewTimeFilterValueUnknown(), diags
	}

	dateRangeVal, ok := dateRangeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`date_range expected to be basetypes.StringValue, was: %T`, dateRangeAttribute))
	}

	displayTextAttribute, ok := attributes["display_text"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`display_text is missing from object`)

		return NewTimeFilterValueUnknown(), diags
	}

	displayTextVal, ok := displayTextAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`display_text expected to be basetypes.StringValue, was: %T`, displayTextAttribute))
	}

	if diags.HasError() {
		return NewTimeFilterValueUnknown(), diags
	}

	return TimeFilterValue{
		DateRange:   dateRangeVal,
		DisplayText: displayTextVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewTimeFilterValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) TimeFilterValue {
	object, diags := NewTimeFilterValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewTimeFilterValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t TimeFilterType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewTimeFilterValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewTimeFilterValueUnknown(), nil
	}

	if in.IsNull() {
		return NewTimeFilterValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewTimeFilterValueMust(TimeFilterValue{}.AttributeTypes(ctx), attributes), nil
}

func (t TimeFilterType) ValueType(ctx context.Context) attr.Value {
	return TimeFilterValue{}
}

var _ basetypes.ObjectValuable = TimeFilterValue{}

type TimeFilterValue struct {
	DateRange   basetypes.StringValue `tfsdk:"date_range"`
	DisplayText basetypes.StringValue `tfsdk:"display_text"`
	state       attr.ValueState
}

func (v TimeFilterValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["date_range"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["display_text"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.DateRange.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["date_range"] = val

		val, err = v.DisplayText.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["display_text"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v TimeFilterValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v TimeFilterValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v TimeFilterValue) String() string {
	return "TimeFilterValue"
}

func (v TimeFilterValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"date_range":   basetypes.StringType{},
		"display_text": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"date_range":   v.DateRange,
			"display_text": v.DisplayText,
		})

	return objVal, diags
}

func (v TimeFilterValue) Equal(o attr.Value) bool {
	other, ok := o.(TimeFilterValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.DateRange.Equal(other.DateRange) {
		return false
	}

	if !v.DisplayText.Equal(other.DisplayText) {
		return false
	}

	return true
}

func (v TimeFilterValue) Type(ctx context.Context) attr.Type {
	return TimeFilterType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v TimeFilterValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"date_range":   basetypes.StringType{},
		"display_text": basetypes.StringType{},
	}
}
