// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_bookmark

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func BookmarkResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"allow_staff_override": schema.BoolAttribute{
				Computed: true,
			},
			"bookmark_id": schema.Int64Attribute{
				Optional: true,
				Computed: true,
			},
			"bookmark_url_slug": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"can_share": schema.BoolAttribute{
				Computed: true,
			},
			"can_update_basic": schema.BoolAttribute{
				Computed: true,
			},
			"can_view": schema.BoolAttribute{
				Computed: true,
			},
			"created": schema.StringAttribute{
				Computed: true,
			},
			"creator": schema.StringAttribute{
				Computed: true,
			},
			"creator_email": schema.StringAttribute{
				Computed: true,
			},
			"creator_id": schema.Int64Attribute{
				Computed: true,
			},
			"creator_name": schema.StringAttribute{
				Computed: true,
			},
			"dashboard_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"deleted": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"description": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"generation_type": schema.StringAttribute{
				Computed: true,
			},
			"global_access_type": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"icon": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"id": schema.Int64Attribute{
				Computed: true,
			},
			"include_in_dashboard": schema.BoolAttribute{
				Computed: true,
			},
			"is_default": schema.BoolAttribute{
				Computed: true,
			},
			"is_modification_restricted": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"is_superadmin": schema.BoolAttribute{
				Computed: true,
			},
			"is_visibility_restricted": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"last_modified_by_email": schema.StringAttribute{
				Computed: true,
			},
			"last_modified_by_id": schema.Int64Attribute{
				Computed: true,
			},
			"last_modified_by_name": schema.StringAttribute{
				Computed: true,
			},
			"modified": schema.StringAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"original_type": schema.StringAttribute{
				Computed: true,
			},
			"prev_bookmark_url_slug": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"project_id": schema.Int64Attribute{
				Computed: true,
			},
			"total_view_count": schema.Int64Attribute{
				Computed: true,
			},
			"type": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"unique_view_count": schema.Int64Attribute{
				Computed: true,
			},
			"v": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"workspace_id": schema.Int64Attribute{
				Computed: true,
			},
		},
	}
}

type BookmarkModel struct {
	AllowStaffOverride       types.Bool   `tfsdk:"allow_staff_override"`
	BookmarkId               types.Int64  `tfsdk:"bookmark_id"`
	BookmarkUrlSlug          types.String `tfsdk:"bookmark_url_slug"`
	CanShare                 types.Bool   `tfsdk:"can_share"`
	CanUpdateBasic           types.Bool   `tfsdk:"can_update_basic"`
	CanView                  types.Bool   `tfsdk:"can_view"`
	Created                  types.String `tfsdk:"created"`
	Creator                  types.String `tfsdk:"creator"`
	CreatorEmail             types.String `tfsdk:"creator_email"`
	CreatorId                types.Int64  `tfsdk:"creator_id"`
	CreatorName              types.String `tfsdk:"creator_name"`
	DashboardId              types.String `tfsdk:"dashboard_id"`
	Deleted                  types.String `tfsdk:"deleted"`
	Description              types.String `tfsdk:"description"`
	GenerationType           types.String `tfsdk:"generation_type"`
	GlobalAccessType         types.String `tfsdk:"global_access_type"`
	Icon                     types.String `tfsdk:"icon"`
	Id                       types.Int64  `tfsdk:"id"`
	IncludeInDashboard       types.Bool   `tfsdk:"include_in_dashboard"`
	IsDefault                types.Bool   `tfsdk:"is_default"`
	IsModificationRestricted types.String `tfsdk:"is_modification_restricted"`
	IsSuperadmin             types.Bool   `tfsdk:"is_superadmin"`
	IsVisibilityRestricted   types.String `tfsdk:"is_visibility_restricted"`
	LastModifiedByEmail      types.String `tfsdk:"last_modified_by_email"`
	LastModifiedById         types.Int64  `tfsdk:"last_modified_by_id"`
	LastModifiedByName       types.String `tfsdk:"last_modified_by_name"`
	Modified                 types.String `tfsdk:"modified"`
	Name                     types.String `tfsdk:"name"`
	OriginalType             types.String `tfsdk:"original_type"`
	PrevBookmarkUrlSlug      types.String `tfsdk:"prev_bookmark_url_slug"`
	ProjectId                types.Int64  `tfsdk:"project_id"`
	TotalViewCount           types.Int64  `tfsdk:"total_view_count"`
	Type                     types.String `tfsdk:"type"`
	UniqueViewCount          types.Int64  `tfsdk:"unique_view_count"`
	V                        types.String `tfsdk:"v"`
	WorkspaceId              types.Int64  `tfsdk:"workspace_id"`
}
