// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_custom_alert

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"regexp"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func CustomAlertResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"bookmark_id": schema.Int64Attribute{
				Required: true,
			},
			"custom_alert_id": schema.Int64Attribute{
				Optional: true,
				Computed: true,
			},
			"frequency": schema.Int64Attribute{
				Required: true,
			},
			"id": schema.Int64Attribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 50),
				},
			},
			"notification_windows": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"enabled": schema.BoolAttribute{
						Required:            true,
						Description:         "Whether notification windows are active",
						MarkdownDescription: "Whether notification windows are active",
					},
					"windows": schema.ListNestedAttribute{
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"end_day": schema.Int64Attribute{
									Required:            true,
									Description:         "End day: 0-6 (same week), 7-13 (next week)",
									MarkdownDescription: "End day: 0-6 (same week), 7-13 (next week)",
									Validators: []validator.Int64{
										int64validator.Between(0, 13),
									},
								},
								"end_time": schema.StringAttribute{
									Required:            true,
									Description:         "End time in HH:MM format",
									MarkdownDescription: "End time in HH:MM format",
									Validators: []validator.String{
										stringvalidator.RegexMatches(regexp.MustCompile("^([01]?[0-9]|2[0-3]):[0-5][0-9]$"), ""),
									},
								},
								"start_day": schema.Int64Attribute{
									Required:            true,
									Description:         "Start day: 0-6 (Mon-Sun)",
									MarkdownDescription: "Start day: 0-6 (Mon-Sun)",
									Validators: []validator.Int64{
										int64validator.Between(0, 6),
									},
								},
								"start_time": schema.StringAttribute{
									Required:            true,
									Description:         "Start time in HH:MM format",
									MarkdownDescription: "Start time in HH:MM format",
									Validators: []validator.String{
										stringvalidator.RegexMatches(regexp.MustCompile("^([01]?[0-9]|2[0-3]):[0-5][0-9]$"), ""),
									},
								},
							},
							CustomType: WindowsType{
								ObjectType: types.ObjectType{
									AttrTypes: WindowsValue{}.AttributeTypes(ctx),
								},
							},
						},
						Optional: true,
						Computed: true,
					},
				},
				CustomType: NotificationWindowsType{
					ObjectType: types.ObjectType{
						AttrTypes: NotificationWindowsValue{}.AttributeTypes(ctx),
					},
				},
				Optional:            true,
				Computed:            true,
				Description:         "Notification windows configuration for an alert.",
				MarkdownDescription: "Notification windows configuration for an alert.",
			},
			"paused": schema.BoolAttribute{
				Required: true,
			},
			"project_id": schema.Int64Attribute{
				Optional: true,
				Computed: true,
			},
		},
	}
}

type CustomAlertModel struct {
	BookmarkId          types.Int64              `tfsdk:"bookmark_id"`
	CustomAlertId       types.Int64              `tfsdk:"custom_alert_id"`
	Frequency           types.Int64              `tfsdk:"frequency"`
	Id                  types.Int64              `tfsdk:"id"`
	Name                types.String             `tfsdk:"name"`
	NotificationWindows NotificationWindowsValue `tfsdk:"notification_windows"`
	Paused              types.Bool               `tfsdk:"paused"`
	ProjectId           types.Int64              `tfsdk:"project_id"`
}

var _ basetypes.ObjectTypable = NotificationWindowsType{}

type NotificationWindowsType struct {
	basetypes.ObjectType
}

func (t NotificationWindowsType) Equal(o attr.Type) bool {
	other, ok := o.(NotificationWindowsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t NotificationWindowsType) String() string {
	return "NotificationWindowsType"
}

func (t NotificationWindowsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	enabledAttribute, ok := attributes["enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`enabled is missing from object`)

		return nil, diags
	}

	enabledVal, ok := enabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`enabled expected to be basetypes.BoolValue, was: %T`, enabledAttribute))
	}

	windowsAttribute, ok := attributes["windows"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`windows is missing from object`)

		return nil, diags
	}

	windowsVal, ok := windowsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`windows expected to be basetypes.ListValue, was: %T`, windowsAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return NotificationWindowsValue{
		Enabled: enabledVal,
		Windows: windowsVal,
		state:   attr.ValueStateKnown,
	}, diags
}

func NewNotificationWindowsValueNull() NotificationWindowsValue {
	return NotificationWindowsValue{
		state: attr.ValueStateNull,
	}
}

func NewNotificationWindowsValueUnknown() NotificationWindowsValue {
	return NotificationWindowsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewNotificationWindowsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (NotificationWindowsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing NotificationWindowsValue Attribute Value",
				"While creating a NotificationWindowsValue value, a missing attribute value was detected. "+
					"A NotificationWindowsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("NotificationWindowsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid NotificationWindowsValue Attribute Type",
				"While creating a NotificationWindowsValue value, an invalid attribute value was detected. "+
					"A NotificationWindowsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("NotificationWindowsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("NotificationWindowsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra NotificationWindowsValue Attribute Value",
				"While creating a NotificationWindowsValue value, an extra attribute value was detected. "+
					"A NotificationWindowsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra NotificationWindowsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewNotificationWindowsValueUnknown(), diags
	}

	enabledAttribute, ok := attributes["enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`enabled is missing from object`)

		return NewNotificationWindowsValueUnknown(), diags
	}

	enabledVal, ok := enabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`enabled expected to be basetypes.BoolValue, was: %T`, enabledAttribute))
	}

	windowsAttribute, ok := attributes["windows"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`windows is missing from object`)

		return NewNotificationWindowsValueUnknown(), diags
	}

	windowsVal, ok := windowsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`windows expected to be basetypes.ListValue, was: %T`, windowsAttribute))
	}

	if diags.HasError() {
		return NewNotificationWindowsValueUnknown(), diags
	}

	return NotificationWindowsValue{
		Enabled: enabledVal,
		Windows: windowsVal,
		state:   attr.ValueStateKnown,
	}, diags
}

func NewNotificationWindowsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) NotificationWindowsValue {
	object, diags := NewNotificationWindowsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewNotificationWindowsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t NotificationWindowsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewNotificationWindowsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewNotificationWindowsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewNotificationWindowsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewNotificationWindowsValueMust(NotificationWindowsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t NotificationWindowsType) ValueType(ctx context.Context) attr.Value {
	return NotificationWindowsValue{}
}

var _ basetypes.ObjectValuable = NotificationWindowsValue{}

type NotificationWindowsValue struct {
	Enabled basetypes.BoolValue `tfsdk:"enabled"`
	Windows basetypes.ListValue `tfsdk:"windows"`
	state   attr.ValueState
}

func (v NotificationWindowsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["enabled"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["windows"] = basetypes.ListType{
		ElemType: WindowsValue{}.Type(ctx),
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Enabled.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["enabled"] = val

		val, err = v.Windows.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["windows"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v NotificationWindowsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v NotificationWindowsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v NotificationWindowsValue) String() string {
	return "NotificationWindowsValue"
}

func (v NotificationWindowsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	windows := types.ListValueMust(
		WindowsType{
			basetypes.ObjectType{
				AttrTypes: WindowsValue{}.AttributeTypes(ctx),
			},
		},
		v.Windows.Elements(),
	)

	if v.Windows.IsNull() {
		windows = types.ListNull(
			WindowsType{
				basetypes.ObjectType{
					AttrTypes: WindowsValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	if v.Windows.IsUnknown() {
		windows = types.ListUnknown(
			WindowsType{
				basetypes.ObjectType{
					AttrTypes: WindowsValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	attributeTypes := map[string]attr.Type{
		"enabled": basetypes.BoolType{},
		"windows": basetypes.ListType{
			ElemType: WindowsValue{}.Type(ctx),
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"enabled": v.Enabled,
			"windows": windows,
		})

	return objVal, diags
}

func (v NotificationWindowsValue) Equal(o attr.Value) bool {
	other, ok := o.(NotificationWindowsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Enabled.Equal(other.Enabled) {
		return false
	}

	if !v.Windows.Equal(other.Windows) {
		return false
	}

	return true
}

func (v NotificationWindowsValue) Type(ctx context.Context) attr.Type {
	return NotificationWindowsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v NotificationWindowsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"enabled": basetypes.BoolType{},
		"windows": basetypes.ListType{
			ElemType: WindowsValue{}.Type(ctx),
		},
	}
}

var _ basetypes.ObjectTypable = WindowsType{}

type WindowsType struct {
	basetypes.ObjectType
}

func (t WindowsType) Equal(o attr.Type) bool {
	other, ok := o.(WindowsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t WindowsType) String() string {
	return "WindowsType"
}

func (t WindowsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	endDayAttribute, ok := attributes["end_day"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`end_day is missing from object`)

		return nil, diags
	}

	endDayVal, ok := endDayAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`end_day expected to be basetypes.Int64Value, was: %T`, endDayAttribute))
	}

	endTimeAttribute, ok := attributes["end_time"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`end_time is missing from object`)

		return nil, diags
	}

	endTimeVal, ok := endTimeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`end_time expected to be basetypes.StringValue, was: %T`, endTimeAttribute))
	}

	startDayAttribute, ok := attributes["start_day"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`start_day is missing from object`)

		return nil, diags
	}

	startDayVal, ok := startDayAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`start_day expected to be basetypes.Int64Value, was: %T`, startDayAttribute))
	}

	startTimeAttribute, ok := attributes["start_time"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`start_time is missing from object`)

		return nil, diags
	}

	startTimeVal, ok := startTimeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`start_time expected to be basetypes.StringValue, was: %T`, startTimeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return WindowsValue{
		EndDay:    endDayVal,
		EndTime:   endTimeVal,
		StartDay:  startDayVal,
		StartTime: startTimeVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewWindowsValueNull() WindowsValue {
	return WindowsValue{
		state: attr.ValueStateNull,
	}
}

func NewWindowsValueUnknown() WindowsValue {
	return WindowsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewWindowsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (WindowsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing WindowsValue Attribute Value",
				"While creating a WindowsValue value, a missing attribute value was detected. "+
					"A WindowsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("WindowsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid WindowsValue Attribute Type",
				"While creating a WindowsValue value, an invalid attribute value was detected. "+
					"A WindowsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("WindowsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("WindowsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra WindowsValue Attribute Value",
				"While creating a WindowsValue value, an extra attribute value was detected. "+
					"A WindowsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra WindowsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewWindowsValueUnknown(), diags
	}

	endDayAttribute, ok := attributes["end_day"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`end_day is missing from object`)

		return NewWindowsValueUnknown(), diags
	}

	endDayVal, ok := endDayAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`end_day expected to be basetypes.Int64Value, was: %T`, endDayAttribute))
	}

	endTimeAttribute, ok := attributes["end_time"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`end_time is missing from object`)

		return NewWindowsValueUnknown(), diags
	}

	endTimeVal, ok := endTimeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`end_time expected to be basetypes.StringValue, was: %T`, endTimeAttribute))
	}

	startDayAttribute, ok := attributes["start_day"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`start_day is missing from object`)

		return NewWindowsValueUnknown(), diags
	}

	startDayVal, ok := startDayAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`start_day expected to be basetypes.Int64Value, was: %T`, startDayAttribute))
	}

	startTimeAttribute, ok := attributes["start_time"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`start_time is missing from object`)

		return NewWindowsValueUnknown(), diags
	}

	startTimeVal, ok := startTimeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`start_time expected to be basetypes.StringValue, was: %T`, startTimeAttribute))
	}

	if diags.HasError() {
		return NewWindowsValueUnknown(), diags
	}

	return WindowsValue{
		EndDay:    endDayVal,
		EndTime:   endTimeVal,
		StartDay:  startDayVal,
		StartTime: startTimeVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewWindowsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) WindowsValue {
	object, diags := NewWindowsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewWindowsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t WindowsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewWindowsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewWindowsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewWindowsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewWindowsValueMust(WindowsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t WindowsType) ValueType(ctx context.Context) attr.Value {
	return WindowsValue{}
}

var _ basetypes.ObjectValuable = WindowsValue{}

type WindowsValue struct {
	EndDay    basetypes.Int64Value  `tfsdk:"end_day"`
	EndTime   basetypes.StringValue `tfsdk:"end_time"`
	StartDay  basetypes.Int64Value  `tfsdk:"start_day"`
	StartTime basetypes.StringValue `tfsdk:"start_time"`
	state     attr.ValueState
}

func (v WindowsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 4)

	var val tftypes.Value
	var err error

	attrTypes["end_day"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["end_time"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["start_day"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["start_time"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 4)

		val, err = v.EndDay.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["end_day"] = val

		val, err = v.EndTime.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["end_time"] = val

		val, err = v.StartDay.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["start_day"] = val

		val, err = v.StartTime.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["start_time"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v WindowsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v WindowsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v WindowsValue) String() string {
	return "WindowsValue"
}

func (v WindowsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"end_day":    basetypes.Int64Type{},
		"end_time":   basetypes.StringType{},
		"start_day":  basetypes.Int64Type{},
		"start_time": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"end_day":    v.EndDay,
			"end_time":   v.EndTime,
			"start_day":  v.StartDay,
			"start_time": v.StartTime,
		})

	return objVal, diags
}

func (v WindowsValue) Equal(o attr.Value) bool {
	other, ok := o.(WindowsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.EndDay.Equal(other.EndDay) {
		return false
	}

	if !v.EndTime.Equal(other.EndTime) {
		return false
	}

	if !v.StartDay.Equal(other.StartDay) {
		return false
	}

	if !v.StartTime.Equal(other.StartTime) {
		return false
	}

	return true
}

func (v WindowsValue) Type(ctx context.Context) attr.Type {
	return WindowsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v WindowsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"end_day":    basetypes.Int64Type{},
		"end_time":   basetypes.StringType{},
		"start_day":  basetypes.Int64Type{},
		"start_time": basetypes.StringType{},
	}
}
