// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_feature_flag

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func FeatureFlagResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"allow_staff_override": schema.BoolAttribute{
				Computed: true,
			},
			"can_pin": schema.BoolAttribute{
				Computed: true,
			},
			"can_share": schema.BoolAttribute{
				Computed: true,
			},
			"can_update_basic": schema.BoolAttribute{
				Computed: true,
			},
			"can_view": schema.BoolAttribute{
				Computed: true,
			},
			"content_environments_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"content_type": schema.StringAttribute{
				Computed: true,
			},
			"context": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 255),
				},
			},
			"created": schema.StringAttribute{
				Computed: true,
			},
			"creator_email": schema.StringAttribute{
				Computed: true,
			},
			"creator_id": schema.Int64Attribute{
				Computed: true,
			},
			"creator_name": schema.StringAttribute{
				Computed: true,
			},
			"data_group_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"deleted": schema.StringAttribute{
				Computed: true,
			},
			"description": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"enabled_at": schema.StringAttribute{
				Computed: true,
			},
			"experiment_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"flag_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"hash_salt": schema.StringAttribute{
				Optional: true,
				Computed: true,
				Validators: []validator.String{
					stringvalidator.LengthBetween(32, 32),
				},
			},
			"id": schema.StringAttribute{
				Computed: true,
			},
			"is_experiment_active": schema.BoolAttribute{
				Optional: true,
				Computed: true,
			},
			"is_favorited": schema.BoolAttribute{
				Computed: true,
			},
			"is_shared_with_project": schema.BoolAttribute{
				Computed: true,
			},
			"is_superadmin": schema.BoolAttribute{
				Computed: true,
			},
			"key": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 255),
				},
			},
			"last_modified_by_email": schema.StringAttribute{
				Computed: true,
			},
			"last_modified_by_id": schema.Int64Attribute{
				Computed: true,
			},
			"last_modified_by_name": schema.StringAttribute{
				Computed: true,
			},
			"modified": schema.StringAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 255),
				},
			},
			"pinned_date": schema.StringAttribute{
				Computed: true,
			},
			"project_id": schema.Int64Attribute{
				Computed: true,
			},
			"project_name": schema.StringAttribute{
				Computed: true,
			},
			"reset_hash_salt": schema.BoolAttribute{
				Optional: true,
				Computed: true,
			},
			"ruleset": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"rollout": schema.ListNestedAttribute{
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"cohort_hash": schema.StringAttribute{
									Optional: true,
									Computed: true,
								},
								"name": schema.StringAttribute{
									Optional: true,
									Computed: true,
								},
								"rollout_percentage": schema.NumberAttribute{
									Required: true,
								},
								"variant_splits": schema.MapAttribute{
									ElementType: types.NumberType,
									Required:    true,
								},
							},
							CustomType: RolloutType{
								ObjectType: types.ObjectType{
									AttrTypes: RolloutValue{}.AttributeTypes(ctx),
								},
							},
						},
						Required: true,
					},
					"variants": schema.ListNestedAttribute{
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"description": schema.StringAttribute{
									Optional: true,
									Computed: true,
								},
								"is_control": schema.BoolAttribute{
									Required: true,
								},
								"is_sticky": schema.BoolAttribute{
									Optional: true,
									Computed: true,
									Default:  booldefault.StaticBool(false),
								},
								"key": schema.StringAttribute{
									Required: true,
								},
								"screenshot": schema.StringAttribute{
									Optional: true,
									Computed: true,
								},
								"split": schema.NumberAttribute{
									Required: true,
								},
							},
							CustomType: VariantsType{
								ObjectType: types.ObjectType{
									AttrTypes: VariantsValue{}.AttributeTypes(ctx),
								},
							},
						},
						Required: true,
						Validators: []validator.List{
							listvalidator.SizeAtMost(11),
						},
					},
				},
				CustomType: RulesetType{
					ObjectType: types.ObjectType{
						AttrTypes: RulesetValue{}.AttributeTypes(ctx),
					},
				},
				Required: true,
			},
			"serving_method": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"client",
						"server",
						"remote_or_local",
						"remote_only",
					),
				},
			},
			"status": schema.StringAttribute{
				Optional: true,
				Computed: true,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"enabled",
						"disabled",
						"archived",
					),
				},
			},
			"tags": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"workspace_id": schema.Int64Attribute{
				Optional: true,
				Computed: true,
			},
		},
	}
}

type FeatureFlagModel struct {
	AllowStaffOverride    types.Bool   `tfsdk:"allow_staff_override"`
	CanPin                types.Bool   `tfsdk:"can_pin"`
	CanShare              types.Bool   `tfsdk:"can_share"`
	CanUpdateBasic        types.Bool   `tfsdk:"can_update_basic"`
	CanView               types.Bool   `tfsdk:"can_view"`
	ContentEnvironmentsId types.String `tfsdk:"content_environments_id"`
	ContentType           types.String `tfsdk:"content_type"`
	Context               types.String `tfsdk:"context"`
	Created               types.String `tfsdk:"created"`
	CreatorEmail          types.String `tfsdk:"creator_email"`
	CreatorId             types.Int64  `tfsdk:"creator_id"`
	CreatorName           types.String `tfsdk:"creator_name"`
	DataGroupId           types.String `tfsdk:"data_group_id"`
	Deleted               types.String `tfsdk:"deleted"`
	Description           types.String `tfsdk:"description"`
	EnabledAt             types.String `tfsdk:"enabled_at"`
	ExperimentId          types.String `tfsdk:"experiment_id"`
	FlagId                types.String `tfsdk:"flag_id"`
	HashSalt              types.String `tfsdk:"hash_salt"`
	Id                    types.String `tfsdk:"id"`
	IsExperimentActive    types.Bool   `tfsdk:"is_experiment_active"`
	IsFavorited           types.Bool   `tfsdk:"is_favorited"`
	IsSharedWithProject   types.Bool   `tfsdk:"is_shared_with_project"`
	IsSuperadmin          types.Bool   `tfsdk:"is_superadmin"`
	Key                   types.String `tfsdk:"key"`
	LastModifiedByEmail   types.String `tfsdk:"last_modified_by_email"`
	LastModifiedById      types.Int64  `tfsdk:"last_modified_by_id"`
	LastModifiedByName    types.String `tfsdk:"last_modified_by_name"`
	Modified              types.String `tfsdk:"modified"`
	Name                  types.String `tfsdk:"name"`
	PinnedDate            types.String `tfsdk:"pinned_date"`
	ProjectId             types.Int64  `tfsdk:"project_id"`
	ProjectName           types.String `tfsdk:"project_name"`
	ResetHashSalt         types.Bool   `tfsdk:"reset_hash_salt"`
	Ruleset               RulesetValue `tfsdk:"ruleset"`
	ServingMethod         types.String `tfsdk:"serving_method"`
	Status                types.String `tfsdk:"status"`
	Tags                  types.List   `tfsdk:"tags"`
	WorkspaceId           types.Int64  `tfsdk:"workspace_id"`
}

var _ basetypes.ObjectTypable = RulesetType{}

type RulesetType struct {
	basetypes.ObjectType
}

func (t RulesetType) Equal(o attr.Type) bool {
	other, ok := o.(RulesetType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t RulesetType) String() string {
	return "RulesetType"
}

func (t RulesetType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	rolloutAttribute, ok := attributes["rollout"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`rollout is missing from object`)

		return nil, diags
	}

	rolloutVal, ok := rolloutAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`rollout expected to be basetypes.ListValue, was: %T`, rolloutAttribute))
	}

	variantsAttribute, ok := attributes["variants"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`variants is missing from object`)

		return nil, diags
	}

	variantsVal, ok := variantsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`variants expected to be basetypes.ListValue, was: %T`, variantsAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return RulesetValue{
		Rollout:  rolloutVal,
		Variants: variantsVal,
		state:    attr.ValueStateKnown,
	}, diags
}

func NewRulesetValueNull() RulesetValue {
	return RulesetValue{
		state: attr.ValueStateNull,
	}
}

func NewRulesetValueUnknown() RulesetValue {
	return RulesetValue{
		state: attr.ValueStateUnknown,
	}
}

func NewRulesetValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (RulesetValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing RulesetValue Attribute Value",
				"While creating a RulesetValue value, a missing attribute value was detected. "+
					"A RulesetValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("RulesetValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid RulesetValue Attribute Type",
				"While creating a RulesetValue value, an invalid attribute value was detected. "+
					"A RulesetValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("RulesetValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("RulesetValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra RulesetValue Attribute Value",
				"While creating a RulesetValue value, an extra attribute value was detected. "+
					"A RulesetValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra RulesetValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewRulesetValueUnknown(), diags
	}

	rolloutAttribute, ok := attributes["rollout"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`rollout is missing from object`)

		return NewRulesetValueUnknown(), diags
	}

	rolloutVal, ok := rolloutAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`rollout expected to be basetypes.ListValue, was: %T`, rolloutAttribute))
	}

	variantsAttribute, ok := attributes["variants"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`variants is missing from object`)

		return NewRulesetValueUnknown(), diags
	}

	variantsVal, ok := variantsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`variants expected to be basetypes.ListValue, was: %T`, variantsAttribute))
	}

	if diags.HasError() {
		return NewRulesetValueUnknown(), diags
	}

	return RulesetValue{
		Rollout:  rolloutVal,
		Variants: variantsVal,
		state:    attr.ValueStateKnown,
	}, diags
}

func NewRulesetValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) RulesetValue {
	object, diags := NewRulesetValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewRulesetValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t RulesetType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewRulesetValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewRulesetValueUnknown(), nil
	}

	if in.IsNull() {
		return NewRulesetValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewRulesetValueMust(RulesetValue{}.AttributeTypes(ctx), attributes), nil
}

func (t RulesetType) ValueType(ctx context.Context) attr.Value {
	return RulesetValue{}
}

var _ basetypes.ObjectValuable = RulesetValue{}

type RulesetValue struct {
	Rollout  basetypes.ListValue `tfsdk:"rollout"`
	Variants basetypes.ListValue `tfsdk:"variants"`
	state    attr.ValueState
}

func (v RulesetValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["rollout"] = basetypes.ListType{
		ElemType: RolloutValue{}.Type(ctx),
	}.TerraformType(ctx)
	attrTypes["variants"] = basetypes.ListType{
		ElemType: VariantsValue{}.Type(ctx),
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Rollout.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["rollout"] = val

		val, err = v.Variants.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["variants"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v RulesetValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v RulesetValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v RulesetValue) String() string {
	return "RulesetValue"
}

func (v RulesetValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	rollout := types.ListValueMust(
		RolloutType{
			basetypes.ObjectType{
				AttrTypes: RolloutValue{}.AttributeTypes(ctx),
			},
		},
		v.Rollout.Elements(),
	)

	if v.Rollout.IsNull() {
		rollout = types.ListNull(
			RolloutType{
				basetypes.ObjectType{
					AttrTypes: RolloutValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	if v.Rollout.IsUnknown() {
		rollout = types.ListUnknown(
			RolloutType{
				basetypes.ObjectType{
					AttrTypes: RolloutValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	variants := types.ListValueMust(
		VariantsType{
			basetypes.ObjectType{
				AttrTypes: VariantsValue{}.AttributeTypes(ctx),
			},
		},
		v.Variants.Elements(),
	)

	if v.Variants.IsNull() {
		variants = types.ListNull(
			VariantsType{
				basetypes.ObjectType{
					AttrTypes: VariantsValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	if v.Variants.IsUnknown() {
		variants = types.ListUnknown(
			VariantsType{
				basetypes.ObjectType{
					AttrTypes: VariantsValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	attributeTypes := map[string]attr.Type{
		"rollout": basetypes.ListType{
			ElemType: RolloutValue{}.Type(ctx),
		},
		"variants": basetypes.ListType{
			ElemType: VariantsValue{}.Type(ctx),
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"rollout":  rollout,
			"variants": variants,
		})

	return objVal, diags
}

func (v RulesetValue) Equal(o attr.Value) bool {
	other, ok := o.(RulesetValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Rollout.Equal(other.Rollout) {
		return false
	}

	if !v.Variants.Equal(other.Variants) {
		return false
	}

	return true
}

func (v RulesetValue) Type(ctx context.Context) attr.Type {
	return RulesetType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v RulesetValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"rollout": basetypes.ListType{
			ElemType: RolloutValue{}.Type(ctx),
		},
		"variants": basetypes.ListType{
			ElemType: VariantsValue{}.Type(ctx),
		},
	}
}

var _ basetypes.ObjectTypable = RolloutType{}

type RolloutType struct {
	basetypes.ObjectType
}

func (t RolloutType) Equal(o attr.Type) bool {
	other, ok := o.(RolloutType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t RolloutType) String() string {
	return "RolloutType"
}

func (t RolloutType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	cohortHashAttribute, ok := attributes["cohort_hash"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cohort_hash is missing from object`)

		return nil, diags
	}

	cohortHashVal, ok := cohortHashAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cohort_hash expected to be basetypes.StringValue, was: %T`, cohortHashAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	rolloutPercentageAttribute, ok := attributes["rollout_percentage"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`rollout_percentage is missing from object`)

		return nil, diags
	}

	rolloutPercentageVal, ok := rolloutPercentageAttribute.(basetypes.NumberValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`rollout_percentage expected to be basetypes.NumberValue, was: %T`, rolloutPercentageAttribute))
	}

	variantSplitsAttribute, ok := attributes["variant_splits"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`variant_splits is missing from object`)

		return nil, diags
	}

	variantSplitsVal, ok := variantSplitsAttribute.(basetypes.MapValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`variant_splits expected to be basetypes.MapValue, was: %T`, variantSplitsAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return RolloutValue{
		CohortHash:        cohortHashVal,
		Name:              nameVal,
		RolloutPercentage: rolloutPercentageVal,
		VariantSplits:     variantSplitsVal,
		state:             attr.ValueStateKnown,
	}, diags
}

func NewRolloutValueNull() RolloutValue {
	return RolloutValue{
		state: attr.ValueStateNull,
	}
}

func NewRolloutValueUnknown() RolloutValue {
	return RolloutValue{
		state: attr.ValueStateUnknown,
	}
}

func NewRolloutValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (RolloutValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing RolloutValue Attribute Value",
				"While creating a RolloutValue value, a missing attribute value was detected. "+
					"A RolloutValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("RolloutValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid RolloutValue Attribute Type",
				"While creating a RolloutValue value, an invalid attribute value was detected. "+
					"A RolloutValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("RolloutValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("RolloutValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra RolloutValue Attribute Value",
				"While creating a RolloutValue value, an extra attribute value was detected. "+
					"A RolloutValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra RolloutValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewRolloutValueUnknown(), diags
	}

	cohortHashAttribute, ok := attributes["cohort_hash"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cohort_hash is missing from object`)

		return NewRolloutValueUnknown(), diags
	}

	cohortHashVal, ok := cohortHashAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cohort_hash expected to be basetypes.StringValue, was: %T`, cohortHashAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewRolloutValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	rolloutPercentageAttribute, ok := attributes["rollout_percentage"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`rollout_percentage is missing from object`)

		return NewRolloutValueUnknown(), diags
	}

	rolloutPercentageVal, ok := rolloutPercentageAttribute.(basetypes.NumberValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`rollout_percentage expected to be basetypes.NumberValue, was: %T`, rolloutPercentageAttribute))
	}

	variantSplitsAttribute, ok := attributes["variant_splits"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`variant_splits is missing from object`)

		return NewRolloutValueUnknown(), diags
	}

	variantSplitsVal, ok := variantSplitsAttribute.(basetypes.MapValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`variant_splits expected to be basetypes.MapValue, was: %T`, variantSplitsAttribute))
	}

	if diags.HasError() {
		return NewRolloutValueUnknown(), diags
	}

	return RolloutValue{
		CohortHash:        cohortHashVal,
		Name:              nameVal,
		RolloutPercentage: rolloutPercentageVal,
		VariantSplits:     variantSplitsVal,
		state:             attr.ValueStateKnown,
	}, diags
}

func NewRolloutValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) RolloutValue {
	object, diags := NewRolloutValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewRolloutValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t RolloutType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewRolloutValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewRolloutValueUnknown(), nil
	}

	if in.IsNull() {
		return NewRolloutValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewRolloutValueMust(RolloutValue{}.AttributeTypes(ctx), attributes), nil
}

func (t RolloutType) ValueType(ctx context.Context) attr.Value {
	return RolloutValue{}
}

var _ basetypes.ObjectValuable = RolloutValue{}

type RolloutValue struct {
	CohortHash        basetypes.StringValue `tfsdk:"cohort_hash"`
	Name              basetypes.StringValue `tfsdk:"name"`
	RolloutPercentage basetypes.NumberValue `tfsdk:"rollout_percentage"`
	VariantSplits     basetypes.MapValue    `tfsdk:"variant_splits"`
	state             attr.ValueState
}

func (v RolloutValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 4)

	var val tftypes.Value
	var err error

	attrTypes["cohort_hash"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["rollout_percentage"] = basetypes.NumberType{}.TerraformType(ctx)
	attrTypes["variant_splits"] = basetypes.MapType{
		ElemType: types.NumberType,
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 4)

		val, err = v.CohortHash.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["cohort_hash"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.RolloutPercentage.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["rollout_percentage"] = val

		val, err = v.VariantSplits.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["variant_splits"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v RolloutValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v RolloutValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v RolloutValue) String() string {
	return "RolloutValue"
}

func (v RolloutValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var variantSplitsVal basetypes.MapValue
	switch {
	case v.VariantSplits.IsUnknown():
		variantSplitsVal = types.MapUnknown(types.NumberType)
	case v.VariantSplits.IsNull():
		variantSplitsVal = types.MapNull(types.NumberType)
	default:
		var d diag.Diagnostics
		variantSplitsVal, d = types.MapValue(types.NumberType, v.VariantSplits.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"cohort_hash":        basetypes.StringType{},
			"name":               basetypes.StringType{},
			"rollout_percentage": basetypes.NumberType{},
			"variant_splits": basetypes.MapType{
				ElemType: types.NumberType,
			},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"cohort_hash":        basetypes.StringType{},
		"name":               basetypes.StringType{},
		"rollout_percentage": basetypes.NumberType{},
		"variant_splits": basetypes.MapType{
			ElemType: types.NumberType,
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"cohort_hash":        v.CohortHash,
			"name":               v.Name,
			"rollout_percentage": v.RolloutPercentage,
			"variant_splits":     variantSplitsVal,
		})

	return objVal, diags
}

func (v RolloutValue) Equal(o attr.Value) bool {
	other, ok := o.(RolloutValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.CohortHash.Equal(other.CohortHash) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.RolloutPercentage.Equal(other.RolloutPercentage) {
		return false
	}

	if !v.VariantSplits.Equal(other.VariantSplits) {
		return false
	}

	return true
}

func (v RolloutValue) Type(ctx context.Context) attr.Type {
	return RolloutType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v RolloutValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"cohort_hash":        basetypes.StringType{},
		"name":               basetypes.StringType{},
		"rollout_percentage": basetypes.NumberType{},
		"variant_splits": basetypes.MapType{
			ElemType: types.NumberType,
		},
	}
}

var _ basetypes.ObjectTypable = VariantsType{}

type VariantsType struct {
	basetypes.ObjectType
}

func (t VariantsType) Equal(o attr.Type) bool {
	other, ok := o.(VariantsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t VariantsType) String() string {
	return "VariantsType"
}

func (t VariantsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return nil, diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	isControlAttribute, ok := attributes["is_control"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`is_control is missing from object`)

		return nil, diags
	}

	isControlVal, ok := isControlAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`is_control expected to be basetypes.BoolValue, was: %T`, isControlAttribute))
	}

	isStickyAttribute, ok := attributes["is_sticky"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`is_sticky is missing from object`)

		return nil, diags
	}

	isStickyVal, ok := isStickyAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`is_sticky expected to be basetypes.BoolValue, was: %T`, isStickyAttribute))
	}

	keyAttribute, ok := attributes["key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key is missing from object`)

		return nil, diags
	}

	keyVal, ok := keyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key expected to be basetypes.StringValue, was: %T`, keyAttribute))
	}

	screenshotAttribute, ok := attributes["screenshot"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`screenshot is missing from object`)

		return nil, diags
	}

	screenshotVal, ok := screenshotAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`screenshot expected to be basetypes.StringValue, was: %T`, screenshotAttribute))
	}

	splitAttribute, ok := attributes["split"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`split is missing from object`)

		return nil, diags
	}

	splitVal, ok := splitAttribute.(basetypes.NumberValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`split expected to be basetypes.NumberValue, was: %T`, splitAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return VariantsValue{
		Description: descriptionVal,
		IsControl:   isControlVal,
		IsSticky:    isStickyVal,
		Key:         keyVal,
		Screenshot:  screenshotVal,
		Split:       splitVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewVariantsValueNull() VariantsValue {
	return VariantsValue{
		state: attr.ValueStateNull,
	}
}

func NewVariantsValueUnknown() VariantsValue {
	return VariantsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewVariantsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (VariantsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing VariantsValue Attribute Value",
				"While creating a VariantsValue value, a missing attribute value was detected. "+
					"A VariantsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("VariantsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid VariantsValue Attribute Type",
				"While creating a VariantsValue value, an invalid attribute value was detected. "+
					"A VariantsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("VariantsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("VariantsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra VariantsValue Attribute Value",
				"While creating a VariantsValue value, an extra attribute value was detected. "+
					"A VariantsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra VariantsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewVariantsValueUnknown(), diags
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return NewVariantsValueUnknown(), diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	isControlAttribute, ok := attributes["is_control"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`is_control is missing from object`)

		return NewVariantsValueUnknown(), diags
	}

	isControlVal, ok := isControlAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`is_control expected to be basetypes.BoolValue, was: %T`, isControlAttribute))
	}

	isStickyAttribute, ok := attributes["is_sticky"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`is_sticky is missing from object`)

		return NewVariantsValueUnknown(), diags
	}

	isStickyVal, ok := isStickyAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`is_sticky expected to be basetypes.BoolValue, was: %T`, isStickyAttribute))
	}

	keyAttribute, ok := attributes["key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key is missing from object`)

		return NewVariantsValueUnknown(), diags
	}

	keyVal, ok := keyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key expected to be basetypes.StringValue, was: %T`, keyAttribute))
	}

	screenshotAttribute, ok := attributes["screenshot"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`screenshot is missing from object`)

		return NewVariantsValueUnknown(), diags
	}

	screenshotVal, ok := screenshotAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`screenshot expected to be basetypes.StringValue, was: %T`, screenshotAttribute))
	}

	splitAttribute, ok := attributes["split"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`split is missing from object`)

		return NewVariantsValueUnknown(), diags
	}

	splitVal, ok := splitAttribute.(basetypes.NumberValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`split expected to be basetypes.NumberValue, was: %T`, splitAttribute))
	}

	if diags.HasError() {
		return NewVariantsValueUnknown(), diags
	}

	return VariantsValue{
		Description: descriptionVal,
		IsControl:   isControlVal,
		IsSticky:    isStickyVal,
		Key:         keyVal,
		Screenshot:  screenshotVal,
		Split:       splitVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewVariantsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) VariantsValue {
	object, diags := NewVariantsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewVariantsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t VariantsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewVariantsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewVariantsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewVariantsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewVariantsValueMust(VariantsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t VariantsType) ValueType(ctx context.Context) attr.Value {
	return VariantsValue{}
}

var _ basetypes.ObjectValuable = VariantsValue{}

type VariantsValue struct {
	Description basetypes.StringValue `tfsdk:"description"`
	IsControl   basetypes.BoolValue   `tfsdk:"is_control"`
	IsSticky    basetypes.BoolValue   `tfsdk:"is_sticky"`
	Key         basetypes.StringValue `tfsdk:"key"`
	Screenshot  basetypes.StringValue `tfsdk:"screenshot"`
	Split       basetypes.NumberValue `tfsdk:"split"`
	state       attr.ValueState
}

func (v VariantsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 6)

	var val tftypes.Value
	var err error

	attrTypes["description"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["is_control"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["is_sticky"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["key"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["screenshot"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["split"] = basetypes.NumberType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 6)

		val, err = v.Description.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["description"] = val

		val, err = v.IsControl.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["is_control"] = val

		val, err = v.IsSticky.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["is_sticky"] = val

		val, err = v.Key.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["key"] = val

		val, err = v.Screenshot.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["screenshot"] = val

		val, err = v.Split.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["split"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v VariantsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v VariantsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v VariantsValue) String() string {
	return "VariantsValue"
}

func (v VariantsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"description": basetypes.StringType{},
		"is_control":  basetypes.BoolType{},
		"is_sticky":   basetypes.BoolType{},
		"key":         basetypes.StringType{},
		"screenshot":  basetypes.StringType{},
		"split":       basetypes.NumberType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"description": v.Description,
			"is_control":  v.IsControl,
			"is_sticky":   v.IsSticky,
			"key":         v.Key,
			"screenshot":  v.Screenshot,
			"split":       v.Split,
		})

	return objVal, diags
}

func (v VariantsValue) Equal(o attr.Value) bool {
	other, ok := o.(VariantsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Description.Equal(other.Description) {
		return false
	}

	if !v.IsControl.Equal(other.IsControl) {
		return false
	}

	if !v.IsSticky.Equal(other.IsSticky) {
		return false
	}

	if !v.Key.Equal(other.Key) {
		return false
	}

	if !v.Screenshot.Equal(other.Screenshot) {
		return false
	}

	if !v.Split.Equal(other.Split) {
		return false
	}

	return true
}

func (v VariantsValue) Type(ctx context.Context) attr.Type {
	return VariantsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v VariantsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"description": basetypes.StringType{},
		"is_control":  basetypes.BoolType{},
		"is_sticky":   basetypes.BoolType{},
		"key":         basetypes.StringType{},
		"screenshot":  basetypes.StringType{},
		"split":       basetypes.NumberType{},
	}
}
