// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_behavior

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func BehaviorDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"behavior_id": schema.Int64Attribute{
				Required: true,
			},
			"description": schema.StringAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Computed: true,
			},
			"project_id": schema.Int64Attribute{
				Required: true,
			},
			"type": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type BehaviorModel struct {
	BehaviorId  types.Int64  `tfsdk:"behavior_id"`
	Description types.String `tfsdk:"description"`
	Name        types.String `tfsdk:"name"`
	ProjectId   types.Int64  `tfsdk:"project_id"`
	Type        types.String `tfsdk:"type"`
}
