// Code generated by gen/crudgen.py. DO NOT EDIT.

package provider

import "github.com/mixpanel/terraform-provider-mixpanel/internal/client"

// BehaviorAttrSpec describes the synthetic / jsonencode attributes of the behavior
// entity to the generic tftypes<->JSON bridge in the client package. It is shared
// by the behavior resource and data source.
func BehaviorAttrSpec() client.AttrSpec {
	return client.AttrSpec{
		IDAttr:            "behavior_id",
		ProjectIDAttr:     "project_id",
		PathParamAttrs:    map[string]bool{},
		JSONEncodeAttrs:   map[string]bool{"definition": true, "behaviors": true},
		JSONStringAttrs:   map[string]bool{},
		JSONEncodeWireKey: map[string]string{},
		OutputOnlyAttrs:   map[string]bool{},
		SpreadAttrs:       map[string]bool{},
	}
}
