// Code generated by gen/crudgen.py. DO NOT EDIT.
//
// HAND-EDITED EXCEPTION: project sharing. This resource carries a synthetic
// `share_with_project` attribute (see sharing.go): Create/Update reconcile the
// project share via the shared-entities API and Read refreshes it. Entities a
// service account creates are otherwise invisible to human users. Re-apply
// these edits if regenerating this file.
//
// HAND-EDITED EXCEPTION 2: plan-time definition/behaviors validation
// (ValidateConfig, see analytics_validate.go for the rule table and citations).
// Re-apply if regenerating.

package provider

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-go/tftypes"

	"github.com/mixpanel/terraform-provider-mixpanel/internal/client"
	rsc "github.com/mixpanel/terraform-provider-mixpanel/internal/provider/resource_behavior"
)

var (
	_ resource.Resource                   = (*BehaviorResource)(nil)
	_ resource.ResourceWithConfigure      = (*BehaviorResource)(nil)
	_ resource.ResourceWithImportState    = (*BehaviorResource)(nil)
	_ resource.ResourceWithValidateConfig = (*BehaviorResource)(nil)
)

// keep the generated schema package and schema builder imported.
var _ = schema.StringAttribute{}

// keep the types package imported (used by nested schema overrides).
var _ = types.NumberType

// NewBehaviorResource constructs the behavior resource.
func NewBehaviorResource() resource.Resource {
	return &BehaviorResource{}
}

type BehaviorResource struct {
	client *client.Client
}

func (r *BehaviorResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_behavior"
}

func (r *BehaviorResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	s := rsc.BehaviorResourceSchema(ctx)
	s.Attributes["definition"] = schema.StringAttribute{Optional: true, Computed: true}
	s.Attributes["behaviors"] = schema.StringAttribute{Optional: true, Computed: true}
	s.Attributes[shareAttrName] = shareWithProjectAttribute()
	normalizedJSON(s.Attributes, "behaviors", "definition")
	stabilizeComputed(s.Attributes)
	resp.Schema = s
}

func (r *BehaviorResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}
	r.client = c
}

// projectID resolves the project from the behavior project_id attribute (if any)
// falling back to the provider default.
func (r *BehaviorResource) projectID(ctx context.Context, raw tftypes.Value) (string, error) {
	pid, err := stringAttrFromRaw(raw, "project_id")
	if err == nil && pid != "" {
		return r.client.ProjectID(pid), nil
	}
	return r.client.ProjectID(""), nil
}

func (r *BehaviorResource) collectionPath(projectID string) string {
	return strings.NewReplacer("{project_id}", projectID).Replace("/api/app/projects/{project_id}/behaviors")
}

func (r *BehaviorResource) instancePath(projectID, id string) string {
	return strings.NewReplacer("{project_id}", projectID, "{behavior_id}", id).Replace("/api/app/projects/{project_id}/behaviors/{behavior_id}")
}

// ValidateConfig rejects the confirmed webapp-corrupting behavior definition
// shapes at plan time (see analytics_validate.go).
func (r *BehaviorResource) ValidateConfig(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {
	validatedJSONAttr(ctx, req.Config, "definition", &resp.Diagnostics, validateBehaviorDefinition)
	validatedJSONAttr(ctx, req.Config, "behaviors", &resp.Diagnostics, validateBehaviorBulk)
	warnJSONAttr(ctx, req.Config, "definition", &resp.Diagnostics, retentionBucketWarnings)
}

func (r *BehaviorResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	spec := BehaviorAttrSpec()
	projectID, err := r.projectID(ctx, req.Plan.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	body, err := client.WireFromRawForCreate(req.Plan.Raw, spec)
	if err != nil {
		resp.Diagnostics.AddError("Encoding behavior request", err.Error())
		return
	}
	respBody, err := r.client.Do(ctx, "POST", r.collectionPath(projectID), body)
	if err != nil {
		resp.Diagnostics.AddError("Creating behavior", err.Error())
		return
	}
	// The create response is enveloped and carries results as a single-entry
	// id->object map keyed by the new behavior id (verified live:
	// {"status":"ok","results":{"<id>":{"id":<id>,...}}}); the inner object is
	// the same behaviors_to_dict_map body the instance GET returns, so it is
	// used directly as the canonical state (no read-back needed).
	wire, err := unwrapBehavior(respBody)
	if err != nil {
		resp.Diagnostics.AddError("Decoding behavior create response", err.Error())
		return
	}
	id := idForBehavior(wire)
	if id == "" {
		resp.Diagnostics.AddError("Creating behavior", "create response did not contain an id")
		return
	}
	r.writeBehaviorState(ctx, &resp.State, &resp.Diagnostics, client.MergeApply, req.Plan.Raw, wire, projectID, id)
	finishShareOnCreate(ctx, r.client, &resp.State, &resp.Diagnostics, req.Plan.Raw, projectID, sharedEntityTypeBehavior, id)
}

func (r *BehaviorResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	projectID, err := r.projectID(ctx, req.State.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	id, err := stringAttrFromRaw(req.State.Raw, "behavior_id")
	if err != nil {
		resp.Diagnostics.AddError("Reading behavior id", err.Error())
		return
	}
	respBody, err := r.client.Do(ctx, "GET", r.instancePath(projectID, id), nil)
	if err != nil {
		if apiErr, ok := err.(*client.APIError); ok && apiErr.StatusCode == 404 {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Reading behavior", err.Error())
		return
	}
	wire, err := unwrapBehavior(respBody)
	if err != nil {
		resp.Diagnostics.AddError("Decoding behavior response", err.Error())
		return
	}
	// Wire-preferred refresh (client.MergeRead): the API response wins for every
	// attribute it carries, so out-of-band edits become visible to `terraform
	// plan` as drift. The prior state is the merge base only for attributes the
	// GET omits (fields the API never echoes back, write-only secrets, spread
	// attributes) — those are preserved instead of being clobbered to null.
	r.writeBehaviorState(ctx, &resp.State, &resp.Diagnostics, client.MergeRead, req.State.Raw, wire, projectID, id)
	refreshShareOnRead(ctx, r.client, &resp.State, &resp.Diagnostics, projectID, sharedEntityTypeBehavior, id)
}

func (r *BehaviorResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	spec := BehaviorAttrSpec()
	projectID, err := r.projectID(ctx, req.Plan.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	id, err := stringAttrFromRaw(req.State.Raw, "behavior_id")
	if err != nil {
		resp.Diagnostics.AddError("Reading behavior id", err.Error())
		return
	}
	body, err := client.WireFromRawForUpdate(req.Plan.Raw, spec)
	if err != nil {
		resp.Diagnostics.AddError("Encoding behavior request", err.Error())
		return
	}
	respBody, err := r.client.Do(ctx, "PATCH", r.instancePath(projectID, id), body)
	if err != nil {
		resp.Diagnostics.AddError("Updating behavior", err.Error())
		return
	}
	wire, err := unwrapBehavior(respBody)
	if err != nil {
		resp.Diagnostics.AddError("Decoding behavior response", err.Error())
		return
	}
	r.writeBehaviorState(ctx, &resp.State, &resp.Diagnostics, client.MergeApply, req.Plan.Raw, wire, projectID, id)
	finishShareOnUpdate(ctx, r.client, &resp.State, &resp.Diagnostics, req.Plan.Raw, req.State.Raw, projectID, sharedEntityTypeBehavior, id)
}

func (r *BehaviorResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	projectID, err := r.projectID(ctx, req.State.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	id, err := stringAttrFromRaw(req.State.Raw, "behavior_id")
	if err != nil {
		resp.Diagnostics.AddError("Reading behavior id", err.Error())
		return
	}
	// DELETE may return a JSON body (Mixpanel convention); Do tolerates it.
	if _, err := r.client.Do(ctx, "DELETE", r.instancePath(projectID, id), nil); err != nil {
		if apiErr, ok := err.(*client.APIError); ok && apiErr.StatusCode == 404 {
			return
		}
		resp.Diagnostics.AddError("Deleting behavior", err.Error())
		return
	}
}

func (r *BehaviorResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.SplitN(req.ID, ":", 2)
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		resp.Diagnostics.AddError(
			"Invalid import ID",
			fmt.Sprintf("expected import ID in the form \"project_id:<id>\", got %q", req.ID),
		)
		return
	}
	setImportID(ctx, &resp.State, &resp.Diagnostics, "project_id", parts[0], "int64")
	setImportID(ctx, &resp.State, &resp.Diagnostics, "behavior_id", parts[1], "int64")
}

// writeBehaviorState turns an unwrapped API body into resource state. On
// create/update (client.MergeApply, base = req.Plan.Raw) config-supplied values
// are preserved verbatim; on read (client.MergeRead, base = req.State.Raw) the
// API response wins wherever it carries a field, so drift is refreshed into
// state. See client.RawFromWireMerged for the exact merge semantics.
func (r *BehaviorResource) writeBehaviorState(ctx context.Context, state *tfsdk.State, diags *diagAppender, mode client.MergeMode, base tftypes.Value, wire map[string]any, projectID, id string) {
	extras := map[string]any{
		"behavior_id": id,
	}
	if projectID != "" {
		extras["project_id"] = projectID
	}
	schemaType := state.Schema.Type().TerraformType(ctx)
	val, err := client.RawFromWireMerged(schemaType, mode, base, wire, extras, BehaviorAttrSpec())
	if err != nil {
		diags.AddError("Building behavior state", err.Error())
		return
	}
	state.Raw = val
}

// idForBehavior extracts the identity value from an unwrapped response body.
func idForBehavior(wire map[string]any) string {
	if v, ok := client.IDFromWire(wire, "behavior_id"); ok {
		return v
	}
	if v, ok := nestedID(wire, "id"); ok {
		return v
	}
	return ""
}

// unwrapBehavior unwraps the API envelope (when enveloped) and returns the body map.
// All behaviors responses (create/get/update/delete) return results as a
// single-entry id->object map (behaviors_to_dict_map, verified live), so the
// results-map unwrap is enabled; the inner object carries its own integer "id".
func unwrapBehavior(respBody []byte) (map[string]any, error) {
	body, err := unwrapBody(respBody, true)
	if err != nil {
		return nil, err
	}
	return unwrapResultsMap(body, true), nil
}
