// Code generated by gen/crudgen.py. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-go/tftypes"

	"github.com/mixpanel/terraform-provider-mixpanel/internal/client"
	dsc "github.com/mixpanel/terraform-provider-mixpanel/internal/provider/datasource_behavior"
)

var (
	_ datasource.DataSource              = (*BehaviorDataSource)(nil)
	_ datasource.DataSourceWithConfigure = (*BehaviorDataSource)(nil)
)

// keep the generated data-source schema package and schema builder imported.
var _ = dschema.StringAttribute{}

// NewBehaviorDataSource constructs the behavior data source.
func NewBehaviorDataSource() datasource.DataSource {
	return &BehaviorDataSource{}
}

type BehaviorDataSource struct {
	client *client.Client
}

func (d *BehaviorDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_behavior"
}

func (d *BehaviorDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	s := dsc.BehaviorDataSourceSchema(ctx)
	s.Attributes["definition"] = dschema.StringAttribute{Optional: true, Computed: true}
	s.Attributes["behaviors"] = dschema.StringAttribute{Optional: true, Computed: true}
	resp.Schema = s
}

func (d *BehaviorDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}
	d.client = c
}

func (d *BehaviorDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	spec := BehaviorAttrSpec()
	projectID := d.client.ProjectID("")
	if pid, perr := stringAttrFromRaw(req.Config.Raw, "project_id"); perr == nil && pid != "" {
		projectID = d.client.ProjectID(pid)
	}
	id, err := stringAttrFromRaw(req.Config.Raw, "behavior_id")
	if err != nil {
		resp.Diagnostics.AddError("Reading behavior id", err.Error())
		return
	}
	path := strings.NewReplacer("{project_id}", projectID, "{behavior_id}", id).Replace("/api/app/projects/{project_id}/behaviors/{behavior_id}")
	respBody, err := d.client.Do(ctx, "GET", path, nil)
	if err != nil {
		resp.Diagnostics.AddError("Reading behavior", err.Error())
		return
	}
	wire, err := unwrapBody(respBody, true)
	if err != nil {
		resp.Diagnostics.AddError("Decoding behavior response", err.Error())
		return
	}
	wire = unwrapResultsMap(wire, false)
	extras := map[string]any{
		"behavior_id": id,
	}
	if projectID != "" {
		extras["project_id"] = projectID
	}
	schemaType := schemaTypeOfDataSource(ctx, resp.State)
	val, err := client.RawFromWire(schemaType, wire, extras, spec)
	if err != nil {
		resp.Diagnostics.AddError("Building behavior state", err.Error())
		return
	}
	resp.State.Raw = val
	_ = tftypes.Value{}
	_ = tfsdk.State{}
}
