// Code generated by gen/crudgen.py. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-go/tftypes"

	"github.com/mixpanel/terraform-provider-mixpanel/internal/client"
	rsc "github.com/mixpanel/terraform-provider-mixpanel/internal/provider/resource_business_context"
)

var (
	_ resource.Resource                = (*BusinessContextResource)(nil)
	_ resource.ResourceWithConfigure   = (*BusinessContextResource)(nil)
	_ resource.ResourceWithImportState = (*BusinessContextResource)(nil)
)

// keep the generated schema package and schema builder imported.
var _ = schema.StringAttribute{}

// keep the types package imported (used by nested schema overrides).
var _ = types.NumberType

// NewBusinessContextResource constructs the business_context resource.
func NewBusinessContextResource() resource.Resource {
	return &BusinessContextResource{}
}

type BusinessContextResource struct {
	client *client.Client
}

func (r *BusinessContextResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_business_context"
}

func (r *BusinessContextResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	s := rsc.BusinessContextResourceSchema(ctx)
	requireReplace(s.Attributes, "project_id")
	stabilizeComputed(s.Attributes)
	resp.Schema = s
}

func (r *BusinessContextResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}
	r.client = c
}

// projectID resolves the project from the business_context project_id attribute (if any)
// falling back to the provider default.
func (r *BusinessContextResource) projectID(ctx context.Context, raw tftypes.Value) (string, error) {
	pid, err := stringAttrFromRaw(raw, "project_id")
	if err == nil && pid != "" {
		return r.client.ProjectID(pid), nil
	}
	return r.client.ProjectID(""), nil
}

func (r *BusinessContextResource) collectionPath(projectID string) string {
	return strings.NewReplacer("{project_id}", projectID).Replace("/api/app/projects/{project_id}/business-context")
}

func (r *BusinessContextResource) instancePath(projectID, id string) string {
	return strings.NewReplacer("{project_id}", projectID, "{project_id}", id).Replace("/api/app/projects/{project_id}/business-context")
}

func (r *BusinessContextResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	spec := BusinessContextAttrSpec()
	projectID, err := r.projectID(ctx, req.Plan.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	body, err := client.WireFromRaw(req.Plan.Raw, spec)
	if err != nil {
		resp.Diagnostics.AddError("Encoding business_context request", err.Error())
		return
	}
	if _, err := r.client.Do(ctx, "POST", r.collectionPath(projectID), body); err != nil {
		resp.Diagnostics.AddError("Creating business_context", err.Error())
		return
	}
	// Read back the canonical settings so state reflects what the API stored.
	getBody, err := r.client.Do(ctx, "GET", r.collectionPath(projectID), nil)
	if err != nil {
		resp.Diagnostics.AddError("Reading business_context after create", err.Error())
		return
	}
	wire, err := unwrapBusinessContext(getBody)
	if err != nil {
		resp.Diagnostics.AddError("Decoding business_context response", err.Error())
		return
	}
	wire = wrapSingleton(wire, "")
	// synthetic id = project id (a project singleton has one settings object).
	r.writeBusinessContextState(ctx, &resp.State, &resp.Diagnostics, req.Plan.Raw, wire, projectID, projectID)
}

func (r *BusinessContextResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	projectID, err := r.projectID(ctx, req.State.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	respBody, err := r.client.Do(ctx, "GET", r.collectionPath(projectID), nil)
	if err != nil {
		if apiErr, ok := err.(*client.APIError); ok && apiErr.StatusCode == 404 {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Reading business_context", err.Error())
		return
	}
	wire, err := unwrapBusinessContext(respBody)
	if err != nil {
		resp.Diagnostics.AddError("Decoding business_context response", err.Error())
		return
	}
	wire = wrapSingleton(wire, "")
	// synthetic id = project id (a project singleton has one settings object).
	r.writeBusinessContextState(ctx, &resp.State, &resp.Diagnostics, req.State.Raw, wire, projectID, projectID)
}

func (r *BusinessContextResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	spec := BusinessContextAttrSpec()
	projectID, err := r.projectID(ctx, req.Plan.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	body, err := client.WireFromRaw(req.Plan.Raw, spec)
	if err != nil {
		resp.Diagnostics.AddError("Encoding business_context request", err.Error())
		return
	}
	if _, err := r.client.Do(ctx, "POST", r.collectionPath(projectID), body); err != nil {
		resp.Diagnostics.AddError("Updating business_context", err.Error())
		return
	}
	getBody, err := r.client.Do(ctx, "GET", r.collectionPath(projectID), nil)
	if err != nil {
		resp.Diagnostics.AddError("Reading business_context after update", err.Error())
		return
	}
	wire, err := unwrapBusinessContext(getBody)
	if err != nil {
		resp.Diagnostics.AddError("Decoding business_context response", err.Error())
		return
	}
	wire = wrapSingleton(wire, "")
	r.writeBusinessContextState(ctx, &resp.State, &resp.Diagnostics, req.Plan.Raw, wire, projectID, projectID)
}

func (r *BusinessContextResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	// business_context is a project singleton: destroy removes it from state only and does
	// NOT mutate the API (the settings are project-global and cannot be deleted).
	_ = ctx
	_ = req
	_ = resp
}

func (r *BusinessContextResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	if req.ID == "" {
		resp.Diagnostics.AddError(
			"Invalid import ID",
			"expected import ID to be the project id (the singleton has no separate id)",
		)
		return
	}
	setImportID(ctx, &resp.State, &resp.Diagnostics, "project_id", req.ID, "int64")
	setImportID(ctx, &resp.State, &resp.Diagnostics, "project_id", req.ID, "int64")
}

// writeBusinessContextState turns an unwrapped API body into resource state. base is the
// planned raw value (req.Plan.Raw) on create/update so config-supplied values are
// preserved verbatim, or a null tftypes.Value on read (state is rebuilt from the
// API response alone). See client.RawFromWireMerged for the merge semantics.
func (r *BusinessContextResource) writeBusinessContextState(ctx context.Context, state *tfsdk.State, diags *diagAppender, base tftypes.Value, wire map[string]any, projectID, id string) {
	extras := map[string]any{
		"project_id": id,
	}
	if projectID != "" {
		extras["project_id"] = projectID
	}
	schemaType := state.Schema.Type().TerraformType(ctx)
	val, err := client.RawFromWireMerged(schemaType, base, wire, extras, BusinessContextAttrSpec())
	if err != nil {
		diags.AddError("Building business_context state", err.Error())
		return
	}
	state.Raw = val
}

// idForBusinessContext extracts the identity value from an unwrapped response body.
func idForBusinessContext(wire map[string]any) string {
	if v, ok := client.IDFromWire(wire, "project_id"); ok {
		return v
	}
	if v, ok := nestedID(wire, "id"); ok {
		return v
	}
	return ""
}

// unwrapBusinessContext unwraps the API envelope (when enveloped) and returns the body map.
func unwrapBusinessContext(respBody []byte) (map[string]any, error) {
	body, err := unwrapBody(respBody, true)
	if err != nil {
		return nil, err
	}
	return unwrapResultsMap(body, false), nil
}
