// Code generated by gen/crudgen.py. DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccBusinessContext_lifecycle(t *testing.T) {
	t.Skip("singleton wrapSingleton shape not modeled by the echo mock")
	srv := newMockServer(t, mockOpts{enveloped: true, idField: "project_id", stringID: false, resultsMap: false, upsert: false, listCreate: false})

	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: testProtoV6,
		Steps: []resource.TestStep{
			{
				// Create; the implicit post-apply refresh+plan asserts idempotency.
				Config: providerConfig(srv.URL, `
resource "mixpanel_business_context" "test" {

}`),
			},
			{
				// Import the resource and assert state round-trips through Read.
				ResourceName:                         "mixpanel_business_context.test",
				ImportState:                          true,
				ImportStateVerify:                    true,
				ImportStateVerifyIdentifierAttribute: "project_id",
				ImportStateIdFunc:                    importIDFunc("mixpanel_business_context.test", "project_id", ""),
				ImportStateVerifyIgnore:              []string{},
			},
		},
	})
}
