// Code generated by gen/crudgen.py. DO NOT EDIT.
//
// HAND-EDITED EXCEPTION: "share_with_project" added to PathParamAttrs so the
// synthetic sharing attribute (see sharing.go) is never serialized into
// entity request bodies. Re-apply if regenerating.

package provider

import "github.com/mixpanel/terraform-provider-mixpanel/internal/client"

// CohortAttrSpec describes the synthetic / jsonencode attributes of the cohort
// entity to the generic tftypes<->JSON bridge in the client package. It is shared
// by the cohort resource and data source.
func CohortAttrSpec() client.AttrSpec {
	return client.AttrSpec{
		IDAttr:              "id",
		ProjectIDAttr:       "project_id",
		PathParamAttrs:      map[string]bool{"share_with_project": true, "cohort_id": true},
		JSONEncodeAttrs:     map[string]bool{"groups": true},
		JSONStringAttrs:     map[string]bool{},
		JSONEncodeWireKey:   map[string]string{"data_group_id": "data_group_id", "is_locked": "is_locked", "is_visible": "is_visible"},
		OutputOnlyAttrs:     map[string]bool{},
		SpreadAttrs:         map[string]bool{},
		CreateWritableAttrs: map[string]bool{"behaviors": true, "data_group_id": true, "description": true, "groups": true, "is_locked": true, "is_visible": true, "name": true, "selector": true},
		UpdateWritableAttrs: map[string]bool{"behaviors": true, "data_group_id": true, "description": true, "groups": true, "is_locked": true, "is_visible": true, "name": true, "selector": true},
	}
}
