// Code generated by gen/crudgen.py. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-go/tftypes"

	"github.com/mixpanel/terraform-provider-mixpanel/internal/client"
	rsc "github.com/mixpanel/terraform-provider-mixpanel/internal/provider/resource_connector"
)

var (
	_ resource.Resource                = (*ConnectorResource)(nil)
	_ resource.ResourceWithConfigure   = (*ConnectorResource)(nil)
	_ resource.ResourceWithImportState = (*ConnectorResource)(nil)
)

// keep the generated schema package and schema builder imported.
var _ = schema.StringAttribute{}

// keep the types package imported (used by nested schema overrides).
var _ = types.NumberType

// NewConnectorResource constructs the connector resource.
func NewConnectorResource() resource.Resource {
	return &ConnectorResource{}
}

type ConnectorResource struct {
	client *client.Client
}

func (r *ConnectorResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_connector"
}

func (r *ConnectorResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	s := rsc.ConnectorResourceSchema(ctx)
	s.Attributes["category_properties"] = schema.StringAttribute{Optional: true, Computed: true}
	s.Attributes["connector_properties"] = schema.StringAttribute{Optional: true, Computed: true}
	requireReplace(s.Attributes, "connector_type", "label", "project_id")
	resp.Schema = s
}

func (r *ConnectorResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}
	r.client = c
}

// projectID resolves the project from the connector project_id attribute (if any)
// falling back to the provider default.
func (r *ConnectorResource) projectID(ctx context.Context, raw tftypes.Value) (string, error) {
	pid, err := stringAttrFromRaw(raw, "project_id")
	if err == nil && pid != "" {
		return r.client.ProjectID(pid), nil
	}
	return r.client.ProjectID(""), nil
}

func (r *ConnectorResource) collectionPath(projectID string) string {
	return strings.NewReplacer("{project_id}", projectID).Replace("/api/app/projects/{project_id}/connectors")
}

func (r *ConnectorResource) instancePath(projectID, id string) string {
	return strings.NewReplacer("{project_id}", projectID, "{connector_id}", id).Replace("/api/app/projects/{project_id}/connectors/{connector_id}")
}

func (r *ConnectorResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	spec := ConnectorAttrSpec()
	projectID, err := r.projectID(ctx, req.Plan.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	body, err := client.WireFromRaw(req.Plan.Raw, spec)
	if err != nil {
		resp.Diagnostics.AddError("Encoding connector request", err.Error())
		return
	}
	respBody, err := r.client.Do(ctx, "POST", r.collectionPath(projectID), body)
	if err != nil {
		resp.Diagnostics.AddError("Creating connector", err.Error())
		return
	}
	wire, err := unwrapConnector(respBody)
	if err != nil {
		resp.Diagnostics.AddError("Decoding connector response", err.Error())
		return
	}
	id := idForConnector(wire)
	r.writeConnectorState(ctx, &resp.State, &resp.Diagnostics, req.Plan.Raw, wire, projectID, id)
}

func (r *ConnectorResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	projectID, err := r.projectID(ctx, req.State.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	id, err := stringAttrFromRaw(req.State.Raw, "connector_id")
	if err != nil {
		resp.Diagnostics.AddError("Reading connector id", err.Error())
		return
	}
	respBody, err := r.client.Do(ctx, "GET", r.instancePath(projectID, id), nil)
	if err != nil {
		if apiErr, ok := err.(*client.APIError); ok && apiErr.StatusCode == 404 {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Reading connector", err.Error())
		return
	}
	wire, err := unwrapConnector(respBody)
	if err != nil {
		resp.Diagnostics.AddError("Decoding connector response", err.Error())
		return
	}
	// Use the prior state as the merge base so attributes the user manages but
	// the API does not faithfully echo back on a GET (fields it never returns, or
	// returns enriched with server-assigned sub-keys such as a subscription id)
	// are preserved instead of being clobbered to null / a server-mangled shape,
	// which would otherwise produce a permanent post-refresh diff. Computed-only
	// values (absent from prior state) are still refreshed from the API response.
	r.writeConnectorState(ctx, &resp.State, &resp.Diagnostics, req.State.Raw, wire, projectID, id)
}

func (r *ConnectorResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	// connector has no update operation in the API (create/read/delete only). Every
	// user-settable attribute is marked RequiresReplace in Schema (via the
	// requireReplace helper), so a changed attribute is planned as a replacement
	// and this method is never reached for a real diff. It remains as a defensive
	// backstop: fail loudly rather than silently copy the plan into state (which
	// would report success while leaving the server unchanged).
	resp.Diagnostics.AddError(
		"connector does not support in-place update",
		"This resource's API has no update operation; changing an attribute replaces the resource. "+
			"Reaching this error is unexpected (attributes are marked RequiresReplace) — please report it.",
	)
}

func (r *ConnectorResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	projectID, err := r.projectID(ctx, req.State.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	id, err := stringAttrFromRaw(req.State.Raw, "connector_id")
	if err != nil {
		resp.Diagnostics.AddError("Reading connector id", err.Error())
		return
	}
	// DELETE may return a JSON body (Mixpanel convention); Do tolerates it.
	if _, err := r.client.Do(ctx, "DELETE", r.instancePath(projectID, id), nil); err != nil {
		if apiErr, ok := err.(*client.APIError); ok && apiErr.StatusCode == 404 {
			return
		}
		resp.Diagnostics.AddError("Deleting connector", err.Error())
		return
	}
}

func (r *ConnectorResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("connector_id"), req, resp)
}

// writeConnectorState turns an unwrapped API body into resource state. base is the
// planned raw value (req.Plan.Raw) on create/update so config-supplied values are
// preserved verbatim, or a null tftypes.Value on read (state is rebuilt from the
// API response alone). See client.RawFromWireMerged for the merge semantics.
func (r *ConnectorResource) writeConnectorState(ctx context.Context, state *tfsdk.State, diags *diagAppender, base tftypes.Value, wire map[string]any, projectID, id string) {
	extras := map[string]any{
		"connector_id": id,
	}
	if projectID != "" {
		extras["project_id"] = projectID
	}
	schemaType := state.Schema.Type().TerraformType(ctx)
	val, err := client.RawFromWireMerged(schemaType, base, wire, extras, ConnectorAttrSpec())
	if err != nil {
		diags.AddError("Building connector state", err.Error())
		return
	}
	state.Raw = val
}

// idForConnector extracts the identity value from an unwrapped response body.
func idForConnector(wire map[string]any) string {
	if v, ok := client.IDFromWire(wire, "connector_id"); ok {
		return v
	}
	if v, ok := nestedID(wire, "connector_id"); ok {
		return v
	}
	return ""
}

// unwrapConnector unwraps the API envelope (when enveloped) and returns the body map.
func unwrapConnector(respBody []byte) (map[string]any, error) {
	body, err := unwrapBody(respBody, true)
	if err != nil {
		return nil, err
	}
	return unwrapResultsMap(body, false), nil
}
