// Code generated by gen/crudgen.py. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-go/tftypes"

	"github.com/mixpanel/terraform-provider-mixpanel/internal/client"
	dsc "github.com/mixpanel/terraform-provider-mixpanel/internal/provider/datasource_custom_alert"
)

var (
	_ datasource.DataSource              = (*CustomAlertDataSource)(nil)
	_ datasource.DataSourceWithConfigure = (*CustomAlertDataSource)(nil)
)

// keep the generated data-source schema package and schema builder imported.
var _ = dschema.StringAttribute{}

// NewCustomAlertDataSource constructs the custom_alert data source.
func NewCustomAlertDataSource() datasource.DataSource {
	return &CustomAlertDataSource{}
}

type CustomAlertDataSource struct {
	client *client.Client
}

func (d *CustomAlertDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_custom_alert"
}

func (d *CustomAlertDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	s := dsc.CustomAlertDataSourceSchema(ctx)
	s.Attributes["condition"] = dschema.StringAttribute{Optional: true, Computed: true}
	s.Attributes["subscriptions"] = dschema.StringAttribute{Optional: true, Computed: true}
	resp.Schema = s
}

func (d *CustomAlertDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}
	d.client = c
}

func (d *CustomAlertDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	spec := CustomAlertAttrSpec()
	projectID := d.client.ProjectID("")
	if pid, perr := stringAttrFromRaw(req.Config.Raw, "project_id"); perr == nil && pid != "" {
		projectID = d.client.ProjectID(pid)
	}
	id, err := stringAttrFromRaw(req.Config.Raw, "id")
	if err != nil {
		resp.Diagnostics.AddError("Reading custom_alert id", err.Error())
		return
	}
	path := strings.NewReplacer("{project_id}", projectID, "{custom_alert_id}", id).Replace("/api/app/projects/{project_id}/alerts/custom/{custom_alert_id}")
	respBody, err := d.client.Do(ctx, "GET", path, nil)
	if err != nil {
		resp.Diagnostics.AddError("Reading custom_alert", err.Error())
		return
	}
	wire, err := unwrapBody(respBody, true)
	if err != nil {
		resp.Diagnostics.AddError("Decoding custom_alert response", err.Error())
		return
	}
	wire = unwrapResultsMap(wire, false)
	extras := map[string]any{
		"id": id,
	}
	if projectID != "" {
		extras["project_id"] = projectID
	}
	schemaType := schemaTypeOfDataSource(ctx, resp.State)
	val, err := client.RawFromWire(schemaType, wire, extras, spec)
	if err != nil {
		resp.Diagnostics.AddError("Building custom_alert state", err.Error())
		return
	}
	resp.State.Raw = val
	_ = tftypes.Value{}
	_ = tfsdk.State{}
}
