// Code generated by gen/crudgen.py. DO NOT EDIT.

package provider

import "github.com/mixpanel/terraform-provider-mixpanel/internal/client"

// CustomRoleAttrSpec describes the synthetic / jsonencode attributes of the custom_role
// entity to the generic tftypes<->JSON bridge in the client package. It is shared
// by the custom_role resource and data source.
func CustomRoleAttrSpec() client.AttrSpec {
	return client.AttrSpec{
		IDAttr:            "role_id",
		ProjectIDAttr:     "project_id",
		PathParamAttrs:    map[string]bool{},
		JSONEncodeAttrs:   map[string]bool{},
		JSONStringAttrs:   map[string]bool{},
		JSONEncodeWireKey: map[string]string{},
		OutputOnlyAttrs:   map[string]bool{"created": true, "created_by_user_id": true, "is_default": true, "modified": true},
		SpreadAttrs:       map[string]bool{},
	}
}
