// Code generated by gen/crudgen.py. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-go/tftypes"

	"github.com/mixpanel/terraform-provider-mixpanel/internal/client"
	rsc "github.com/mixpanel/terraform-provider-mixpanel/internal/provider/resource_custom_property"
)

var (
	_ resource.Resource                = (*CustomPropertyResource)(nil)
	_ resource.ResourceWithConfigure   = (*CustomPropertyResource)(nil)
	_ resource.ResourceWithImportState = (*CustomPropertyResource)(nil)
)

// keep the generated schema package and schema builder imported.
var _ = schema.StringAttribute{}

// keep the types package imported (used by nested schema overrides).
var _ = types.NumberType

// NewCustomPropertyResource constructs the custom_property resource.
func NewCustomPropertyResource() resource.Resource {
	return &CustomPropertyResource{}
}

type CustomPropertyResource struct {
	client *client.Client
}

func (r *CustomPropertyResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_custom_property"
}

func (r *CustomPropertyResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	s := rsc.CustomPropertyResourceSchema(ctx)
	s.Attributes["behavior"] = schema.StringAttribute{Optional: true, Computed: true}
	s.Attributes["composed_properties"] = schema.StringAttribute{Optional: true, Computed: true}
	s.Attributes["display_options"] = schema.StringAttribute{Optional: true, Computed: true}
	stabilizeComputed(s.Attributes)
	resp.Schema = s
}

func (r *CustomPropertyResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}
	r.client = c
}

// projectID resolves the project from the custom_property project_id attribute (if any)
// falling back to the provider default.
func (r *CustomPropertyResource) projectID(ctx context.Context, raw tftypes.Value) (string, error) {
	pid, err := stringAttrFromRaw(raw, "project_id")
	if err == nil && pid != "" {
		return r.client.ProjectID(pid), nil
	}
	return r.client.ProjectID(""), nil
}

func (r *CustomPropertyResource) collectionPath(projectID string) string {
	return strings.NewReplacer("{project_id}", projectID).Replace("/api/app/projects/{project_id}/custom_properties")
}

func (r *CustomPropertyResource) instancePath(projectID, id string) string {
	return strings.NewReplacer("{project_id}", projectID, "{custom_property_id}", id).Replace("/api/app/projects/{project_id}/custom_properties/{custom_property_id}")
}

func (r *CustomPropertyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	spec := CustomPropertyAttrSpec()
	projectID, err := r.projectID(ctx, req.Plan.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	body, err := client.WireFromRaw(req.Plan.Raw, spec)
	if err != nil {
		resp.Diagnostics.AddError("Encoding custom_property request", err.Error())
		return
	}
	respBody, err := r.client.Do(ctx, "POST", r.collectionPath(projectID), body)
	if err != nil {
		resp.Diagnostics.AddError("Creating custom_property", err.Error())
		return
	}
	wire, err := unwrapCustomProperty(respBody)
	if err != nil {
		resp.Diagnostics.AddError("Decoding custom_property response", err.Error())
		return
	}
	id := idForCustomProperty(wire)
	r.writeCustomPropertyState(ctx, &resp.State, &resp.Diagnostics, req.Plan.Raw, wire, projectID, id)
}

func (r *CustomPropertyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	projectID, err := r.projectID(ctx, req.State.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	id, err := stringAttrFromRaw(req.State.Raw, "custom_property_id")
	if err != nil {
		resp.Diagnostics.AddError("Reading custom_property id", err.Error())
		return
	}
	respBody, err := r.client.Do(ctx, "GET", r.instancePath(projectID, id), nil)
	if err != nil {
		if apiErr, ok := err.(*client.APIError); ok && apiErr.StatusCode == 404 {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Reading custom_property", err.Error())
		return
	}
	wire, err := unwrapCustomProperty(respBody)
	if err != nil {
		resp.Diagnostics.AddError("Decoding custom_property response", err.Error())
		return
	}
	// Use the prior state as the merge base so attributes the user manages but
	// the API does not faithfully echo back on a GET (fields it never returns, or
	// returns enriched with server-assigned sub-keys such as a subscription id)
	// are preserved instead of being clobbered to null / a server-mangled shape,
	// which would otherwise produce a permanent post-refresh diff. Computed-only
	// values (absent from prior state) are still refreshed from the API response.
	r.writeCustomPropertyState(ctx, &resp.State, &resp.Diagnostics, req.State.Raw, wire, projectID, id)
}

func (r *CustomPropertyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	spec := CustomPropertyAttrSpec()
	projectID, err := r.projectID(ctx, req.Plan.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	id, err := stringAttrFromRaw(req.State.Raw, "custom_property_id")
	if err != nil {
		resp.Diagnostics.AddError("Reading custom_property id", err.Error())
		return
	}
	body, err := client.WireFromRaw(req.Plan.Raw, spec)
	if err != nil {
		resp.Diagnostics.AddError("Encoding custom_property request", err.Error())
		return
	}
	respBody, err := r.client.Do(ctx, "PUT", r.instancePath(projectID, id), body)
	if err != nil {
		resp.Diagnostics.AddError("Updating custom_property", err.Error())
		return
	}
	wire, err := unwrapCustomProperty(respBody)
	if err != nil {
		resp.Diagnostics.AddError("Decoding custom_property response", err.Error())
		return
	}
	r.writeCustomPropertyState(ctx, &resp.State, &resp.Diagnostics, req.Plan.Raw, wire, projectID, id)
}

func (r *CustomPropertyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	projectID, err := r.projectID(ctx, req.State.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	id, err := stringAttrFromRaw(req.State.Raw, "custom_property_id")
	if err != nil {
		resp.Diagnostics.AddError("Reading custom_property id", err.Error())
		return
	}
	// DELETE may return a JSON body (Mixpanel convention); Do tolerates it.
	if _, err := r.client.Do(ctx, "DELETE", r.instancePath(projectID, id), nil); err != nil {
		if apiErr, ok := err.(*client.APIError); ok && apiErr.StatusCode == 404 {
			return
		}
		resp.Diagnostics.AddError("Deleting custom_property", err.Error())
		return
	}
}

func (r *CustomPropertyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.SplitN(req.ID, ":", 2)
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		resp.Diagnostics.AddError(
			"Invalid import ID",
			fmt.Sprintf("expected import ID in the form \"project_id:<id>\", got %q", req.ID),
		)
		return
	}
	setImportID(ctx, &resp.State, &resp.Diagnostics, "project_id", parts[0], "int64")
	setImportID(ctx, &resp.State, &resp.Diagnostics, "custom_property_id", parts[1], "int64")
}

// writeCustomPropertyState turns an unwrapped API body into resource state. base is the
// planned raw value (req.Plan.Raw) on create/update so config-supplied values are
// preserved verbatim, or a null tftypes.Value on read (state is rebuilt from the
// API response alone). See client.RawFromWireMerged for the merge semantics.
func (r *CustomPropertyResource) writeCustomPropertyState(ctx context.Context, state *tfsdk.State, diags *diagAppender, base tftypes.Value, wire map[string]any, projectID, id string) {
	extras := map[string]any{
		"custom_property_id": id,
	}
	if projectID != "" {
		extras["project_id"] = projectID
	}
	schemaType := state.Schema.Type().TerraformType(ctx)
	val, err := client.RawFromWireMerged(schemaType, base, wire, extras, CustomPropertyAttrSpec())
	if err != nil {
		diags.AddError("Building custom_property state", err.Error())
		return
	}
	state.Raw = val
}

// idForCustomProperty extracts the identity value from an unwrapped response body.
func idForCustomProperty(wire map[string]any) string {
	if v, ok := client.IDFromWire(wire, "custom_property_id"); ok {
		return v
	}
	if v, ok := nestedID(wire, "customPropertyId"); ok {
		return v
	}
	return ""
}

// unwrapCustomProperty unwraps the API envelope (when enveloped) and returns the body map.
func unwrapCustomProperty(respBody []byte) (map[string]any, error) {
	body, err := unwrapBody(respBody, true)
	if err != nil {
		return nil, err
	}
	return unwrapResultsMap(body, false), nil
}
