// Code generated by gen/crudgen.py. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	dschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/mixpanel/terraform-provider-mixpanel/internal/client"
)

var (
	_ datasource.DataSource              = (*CustomAlertListDataSource)(nil)
	_ datasource.DataSourceWithConfigure = (*CustomAlertListDataSource)(nil)
)

// NewCustomAlertListDataSource constructs the custom_alert list data source.
func NewCustomAlertListDataSource() datasource.DataSource {
	return &CustomAlertListDataSource{}
}

type CustomAlertListDataSource struct {
	client *client.Client
}

// CustomAlertListModel is the state model for mixpanel_custom_alerts.
type CustomAlertListModel struct {
	ProjectID types.String `tfsdk:"project_id"`
	IDs       types.List   `tfsdk:"ids"`
	ImportIDs types.List   `tfsdk:"import_ids"`
}

func (d *CustomAlertListDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_custom_alerts"
}

func (d *CustomAlertListDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = dschema.Schema{
		MarkdownDescription: "List of all custom_alert objects in a project. " +
			"`ids` are the raw server ids; `import_ids` are `<project_id>:<id>` " +
			"composites ready to feed a for_each import block.",
		Attributes: map[string]dschema.Attribute{
			"project_id": dschema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Project id. Falls back to the provider default project.",
			},
			"ids": dschema.ListAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				MarkdownDescription: "Raw ids of every custom_alert in the project.",
			},
			"import_ids": dschema.ListAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				MarkdownDescription: "`<project_id>:<id>` composite import ids for every custom_alert.",
			},
		},
	}
}

func (d *CustomAlertListDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}
	d.client = c
}

func (d *CustomAlertListDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var cfg CustomAlertListModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &cfg)...)
	if resp.Diagnostics.HasError() {
		return
	}
	projectID := d.client.ProjectID(cfg.ProjectID.ValueString())
	listPath := strings.NewReplacer("{project_id}", projectID).Replace("/api/app/projects/{project_id}/alerts/custom")
	respBody, err := d.client.Do(ctx, "GET", listPath, nil)
	if err != nil {
		resp.Diagnostics.AddError("Listing custom_alerts", err.Error())
		return
	}
	ids, err := collectIDsFromList(respBody, true, "id")
	if err != nil {
		resp.Diagnostics.AddError("Decoding custom_alert list response", err.Error())
		return
	}
	importIDs := make([]string, len(ids))
	for i, id := range ids {
		importIDs[i] = compositeImportID(projectID, id)
	}
	idList, di := types.ListValueFrom(ctx, types.StringType, ids)
	resp.Diagnostics.Append(di...)
	impList, di2 := types.ListValueFrom(ctx, types.StringType, importIDs)
	resp.Diagnostics.Append(di2...)
	if resp.Diagnostics.HasError() {
		return
	}
	state := CustomAlertListModel{
		ProjectID: types.StringValue(projectID),
		IDs:       idList,
		ImportIDs: impList,
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
