// Code generated by gen/crudgen.py. DO NOT EDIT.
//
// HAND-EDITED EXCEPTION: share_with_project assertions (entities are shared
// with the project by default; an explicit false removes the share). See
// sharing.go. Re-apply if regenerating.
//
// HAND-EDITED EXCEPTION 2: layout tests. TestAccDashboard_layoutLifecycleMock
// round-trips the synthetic `layout` attribute (write format out, GET shape
// back through the mock's read-shape store) and proves out-of-band layout
// edits surface as drift; TestDashboardLayoutWriteFormat unit-tests the
// GET-shape -> write-format transform. Re-apply if regenerating.

package provider

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/plancheck"
)

func TestAccDashboard_lifecycle(t *testing.T) {
	srv := newMockServer(t, mockOpts{enveloped: true, idField: "id", stringID: false, resultsMap: false, upsert: false, listCreate: false})

	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: testProtoV6,
		Steps: []resource.TestStep{
			{
				// Create; the implicit post-apply refresh+plan asserts idempotency.
				Config: providerConfig(srv.URL, `
resource "mixpanel_dashboard" "test" {

}`),
				Check: resource.TestCheckResourceAttr("mixpanel_dashboard.test", "share_with_project", "true"),
			},
			{
				// Explicit share_with_project = false must remove the project share
				// (update path: true -> false calls the shared-entities delete).
				Config: providerConfig(srv.URL, `
resource "mixpanel_dashboard" "test" {
  share_with_project = false
}`),
				Check: resource.TestCheckResourceAttr("mixpanel_dashboard.test", "share_with_project", "false"),
			},
			{
				// Import the resource and assert state round-trips through Read.
				ResourceName:                         "mixpanel_dashboard.test",
				ImportState:                          true,
				ImportStateVerify:                    true,
				ImportStateVerifyIdentifierAttribute: "id",
				ImportStateIdFunc:                    importIDFunc("mixpanel_dashboard.test", "id", "project_id"),
				ImportStateVerifyIgnore:              []string{"created", "creator", "creator_email", "creator_id", "creator_name", "is_favorited", "layout_version", "modified", "pinned_date", "template_type", "total_view_count", "unique_view_count"},
			},
		},
	})
}

// dashboardLayoutConfig renders a dashboard whose layout carries one row with
// one cell of the given width, in the PATCH write format.
func dashboardLayoutConfig(url string, width int) string {
	return providerConfig(url, `
resource "mixpanel_dashboard" "test" {
  title  = "layout-board"
  layout = jsonencode({
    rows = [{
      id     = "r1"
      height = 100
      cells  = [{ id = "c1", width = `+itoa(width)+` }]
    }]
    rows_order = ["r1"]
  })
}`)
}

func itoa(n int) string { return fmt.Sprintf("%d", n) }

// TestAccDashboard_layoutLifecycleMock: the `layout` attribute is written in
// the PATCH write format, stored by the (mock) server in the GET shape, and
// transformed back on refresh — creates and updates must be idempotent, and
// an out-of-band layout edit must surface as drift.
func TestAccDashboard_layoutLifecycleMock(t *testing.T) {
	srv := newMockServer(t, mockOpts{enveloped: true, idField: "id", stringID: false, resultsMap: false, upsert: false, listCreate: false})

	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: testProtoV6,
		Steps: []resource.TestStep{
			{
				// Create (POST + follow-up layout PATCH); the implicit post-apply
				// refresh+plan proves the GET-shape -> write-format transform
				// round-trips without manufacturing drift.
				Config: dashboardLayoutConfig(srv.URL, 6),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttrWith("mixpanel_dashboard.test", "layout", func(v string) error {
						var decoded map[string]any
						if err := json.Unmarshal([]byte(v), &decoded); err != nil {
							return err
						}
						if _, ok := decoded["rows"].([]any); !ok {
							return fmt.Errorf("state layout is not in the write format (rows list): %s", v)
						}
						return nil
					}),
				),
			},
			{
				// Widen the cell: an in-place update carrying the new write-format
				// layout.
				Config: dashboardLayoutConfig(srv.URL, 12),
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction("mixpanel_dashboard.test", plancheck.ResourceActionUpdate),
					},
				},
			},
			{
				// Out-of-band layout edit (webapp user resizes the cell): the
				// refresh must transform the GET shape and surface the drift.
				PreConfig: func() {
					srv.mutateStored(func(id string, obj map[string]any) {
						layout, _ := obj["layout"].(map[string]any)
						if layout == nil {
							return
						}
						rows, _ := layout["rows"].(map[string]any)
						row, _ := rows["r1"].(map[string]any)
						if row == nil {
							return
						}
						row["cells"] = []any{map[string]any{"id": "c1", "width": 4.0, "content_id": nil, "content_type": "report"}}
					})
				},
				RefreshState:       true,
				ExpectNonEmptyPlan: true,
			},
			{
				// Re-applying the config converges the layout back.
				Config: dashboardLayoutConfig(srv.URL, 12),
			},
		},
	})
}

// TestDashboardLayoutWriteFormat unit-tests the GET-shape -> write-format
// layout transform (see dashboard_resource.go).
func TestDashboardLayoutWriteFormat(t *testing.T) {
	t.Parallel()

	getShape := map[string]any{
		"rows": map[string]any{
			"rB": map[string]any{
				"height": 200.0,
				"cells": []any{
					map[string]any{"id": "c2", "width": 6.0, "content_id": 42.0, "content_type": "report"},
				},
			},
			"rA": map[string]any{
				"height": 0.0,
				"cells": []any{
					map[string]any{"id": "c1", "width": 12.0, "content_id": 41.0, "content_type": "report"},
				},
			},
			// Not referenced by order: must be appended after the ordered rows.
			"rZ": map[string]any{"height": 50.0, "cells": []any{}},
		},
		// order drives the output ordering (rB before rA despite key order).
		"order":   []any{"rB", "rA"},
		"version": "2.0.0",
	}
	got, ok := dashboardLayoutWriteFormat(getShape)
	if !ok {
		t.Fatalf("transform rejected a well-formed GET shape")
	}
	want := map[string]any{
		"rows": []any{
			map[string]any{"id": "rB", "height": 200.0, "cells": []any{map[string]any{"id": "c2", "width": 6.0}}},
			map[string]any{"id": "rA", "height": 0.0, "cells": []any{map[string]any{"id": "c1", "width": 12.0}}},
			map[string]any{"id": "rZ", "height": 50.0, "cells": []any{}},
		},
		"rows_order": []any{"rB", "rA", "rZ"},
	}
	if !reflect.DeepEqual(got, want) {
		gotJSON, _ := json.Marshal(got)
		wantJSON, _ := json.Marshal(want)
		t.Fatalf("transform mismatch:\n got: %s\nwant: %s", gotJSON, wantJSON)
	}

	// version and content pointers must never leak into the write format.
	outJSON, _ := json.Marshal(got)
	for _, forbidden := range []string{`"version"`, `"content_id"`, `"content_type"`} {
		if strings.Contains(string(outJSON), forbidden) {
			t.Fatalf("write format leaked forbidden key %s: %s", forbidden, outJSON)
		}
	}

	// Empty GET layout -> empty write layout.
	empty, ok := dashboardLayoutWriteFormat(map[string]any{"rows": map[string]any{}, "order": []any{}, "version": "2.0.0"})
	if !ok || len(empty["rows"].([]any)) != 0 || len(empty["rows_order"].([]any)) != 0 {
		t.Fatalf("empty layout transform: got %v ok=%v", empty, ok)
	}

	// Unexpected shapes must be rejected (caller keeps prior state).
	for name, bad := range map[string]any{
		"not a map":        []any{},
		"rows is a list":   map[string]any{"rows": []any{}, "order": []any{}},
		"order not a list": map[string]any{"rows": map[string]any{}, "order": "r1"},
		"row not object":   map[string]any{"rows": map[string]any{"r1": "oops"}, "order": []any{"r1"}},
		"cells not a list": map[string]any{"rows": map[string]any{"r1": map[string]any{"cells": "oops"}}, "order": []any{"r1"}},
		"order id not str": map[string]any{"rows": map[string]any{}, "order": []any{1.0}},
	} {
		if _, ok := dashboardLayoutWriteFormat(bad); ok {
			t.Fatalf("transform accepted unexpected shape %q", name)
		}
	}
}
