// Code generated by gen/crudgen.py. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-go/tftypes"

	"github.com/mixpanel/terraform-provider-mixpanel/internal/client"
	rsc "github.com/mixpanel/terraform-provider-mixpanel/internal/provider/resource_data_governance_settings"
)

var (
	_ resource.Resource                = (*DataGovernanceSettingsResource)(nil)
	_ resource.ResourceWithConfigure   = (*DataGovernanceSettingsResource)(nil)
	_ resource.ResourceWithImportState = (*DataGovernanceSettingsResource)(nil)
)

// keep the generated schema package and schema builder imported.
var _ = schema.StringAttribute{}

// keep the types package imported (used by nested schema overrides).
var _ = types.NumberType

// NewDataGovernanceSettingsResource constructs the data_governance_settings resource.
func NewDataGovernanceSettingsResource() resource.Resource {
	return &DataGovernanceSettingsResource{}
}

type DataGovernanceSettingsResource struct {
	client *client.Client
}

func (r *DataGovernanceSettingsResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_data_governance_settings"
}

func (r *DataGovernanceSettingsResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	s := rsc.DataGovernanceSettingsResourceSchema(ctx)
	s.Attributes["id"] = schema.StringAttribute{Computed: true}
	s.Attributes["data_standards"] = schema.StringAttribute{Optional: true, Computed: true}
	resp.Schema = s
}

func (r *DataGovernanceSettingsResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}
	r.client = c
}

// projectID resolves the project from the data_governance_settings project_id attribute (if any)
// falling back to the provider default.
func (r *DataGovernanceSettingsResource) projectID(ctx context.Context, raw tftypes.Value) (string, error) {
	pid, err := stringAttrFromRaw(raw, "project_id")
	if err == nil && pid != "" {
		return r.client.ProjectID(pid), nil
	}
	return r.client.ProjectID(""), nil
}

func (r *DataGovernanceSettingsResource) collectionPath(projectID string) string {
	return strings.NewReplacer("{project_id}", projectID).Replace("/api/app/projects/{project_id}/data-governance/data-standards/settings")
}

func (r *DataGovernanceSettingsResource) instancePath(projectID, id string) string {
	return strings.NewReplacer("{project_id}", projectID, "{id}", id).Replace("/api/app/projects/{project_id}/data-governance/data-standards/settings")
}

func (r *DataGovernanceSettingsResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	spec := DataGovernanceSettingsAttrSpec()
	projectID, err := r.projectID(ctx, req.Plan.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	body, err := client.WireFromRaw(req.Plan.Raw, spec)
	if err != nil {
		resp.Diagnostics.AddError("Encoding data_governance_settings request", err.Error())
		return
	}
	if _, err := r.client.Do(ctx, "POST", r.collectionPath(projectID), body); err != nil {
		resp.Diagnostics.AddError("Creating data_governance_settings", err.Error())
		return
	}
	// Read back the canonical settings so state reflects what the API stored.
	getBody, err := r.client.Do(ctx, "GET", r.collectionPath(projectID), nil)
	if err != nil {
		resp.Diagnostics.AddError("Reading data_governance_settings after create", err.Error())
		return
	}
	wire, err := unwrapDataGovernanceSettings(getBody)
	if err != nil {
		resp.Diagnostics.AddError("Decoding data_governance_settings response", err.Error())
		return
	}
	wire = wrapSingleton(wire, "data_standards")
	// synthetic id = project id (a project singleton has one settings object).
	r.writeDataGovernanceSettingsState(ctx, &resp.State, &resp.Diagnostics, req.Plan.Raw, wire, projectID, projectID)
}

func (r *DataGovernanceSettingsResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	projectID, err := r.projectID(ctx, req.State.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	respBody, err := r.client.Do(ctx, "GET", r.collectionPath(projectID), nil)
	if err != nil {
		if apiErr, ok := err.(*client.APIError); ok && apiErr.StatusCode == 404 {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Reading data_governance_settings", err.Error())
		return
	}
	wire, err := unwrapDataGovernanceSettings(respBody)
	if err != nil {
		resp.Diagnostics.AddError("Decoding data_governance_settings response", err.Error())
		return
	}
	wire = wrapSingleton(wire, "data_standards")
	// synthetic id = project id (a project singleton has one settings object).
	r.writeDataGovernanceSettingsState(ctx, &resp.State, &resp.Diagnostics, req.State.Raw, wire, projectID, projectID)
}

func (r *DataGovernanceSettingsResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	spec := DataGovernanceSettingsAttrSpec()
	projectID, err := r.projectID(ctx, req.Plan.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	body, err := client.WireFromRaw(req.Plan.Raw, spec)
	if err != nil {
		resp.Diagnostics.AddError("Encoding data_governance_settings request", err.Error())
		return
	}
	if _, err := r.client.Do(ctx, "POST", r.collectionPath(projectID), body); err != nil {
		resp.Diagnostics.AddError("Updating data_governance_settings", err.Error())
		return
	}
	getBody, err := r.client.Do(ctx, "GET", r.collectionPath(projectID), nil)
	if err != nil {
		resp.Diagnostics.AddError("Reading data_governance_settings after update", err.Error())
		return
	}
	wire, err := unwrapDataGovernanceSettings(getBody)
	if err != nil {
		resp.Diagnostics.AddError("Decoding data_governance_settings response", err.Error())
		return
	}
	wire = wrapSingleton(wire, "data_standards")
	r.writeDataGovernanceSettingsState(ctx, &resp.State, &resp.Diagnostics, req.Plan.Raw, wire, projectID, projectID)
}

func (r *DataGovernanceSettingsResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	// data_governance_settings is a project singleton: destroy removes it from state only and does
	// NOT mutate the API (the settings are project-global and cannot be deleted).
	_ = ctx
	_ = req
	_ = resp
}

func (r *DataGovernanceSettingsResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

// writeDataGovernanceSettingsState turns an unwrapped API body into resource state. base is the
// planned raw value (req.Plan.Raw) on create/update so config-supplied values are
// preserved verbatim, or a null tftypes.Value on read (state is rebuilt from the
// API response alone). See client.RawFromWireMerged for the merge semantics.
func (r *DataGovernanceSettingsResource) writeDataGovernanceSettingsState(ctx context.Context, state *tfsdk.State, diags *diagAppender, base tftypes.Value, wire map[string]any, projectID, id string) {
	extras := map[string]any{
		"id": id,
	}
	if projectID != "" {
		extras["project_id"] = projectID
	}
	schemaType := state.Schema.Type().TerraformType(ctx)
	val, err := client.RawFromWireMerged(schemaType, base, wire, extras, DataGovernanceSettingsAttrSpec())
	if err != nil {
		diags.AddError("Building data_governance_settings state", err.Error())
		return
	}
	state.Raw = val
}

// idForDataGovernanceSettings extracts the identity value from an unwrapped response body.
func idForDataGovernanceSettings(wire map[string]any) string {
	if v, ok := client.IDFromWire(wire, "id"); ok {
		return v
	}
	if v, ok := nestedID(wire, "id"); ok {
		return v
	}
	return ""
}

// unwrapDataGovernanceSettings unwraps the API envelope (when enveloped) and returns the body map.
func unwrapDataGovernanceSettings(respBody []byte) (map[string]any, error) {
	body, err := unwrapBody(respBody, true)
	if err != nil {
		return nil, err
	}
	return unwrapResultsMap(body, false), nil
}
