// Code generated by gen/crudgen.py. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-go/tftypes"

	"github.com/mixpanel/terraform-provider-mixpanel/internal/client"
	rsc "github.com/mixpanel/terraform-provider-mixpanel/internal/provider/resource_data_group"
)

var (
	_ resource.Resource                = (*DataGroupResource)(nil)
	_ resource.ResourceWithConfigure   = (*DataGroupResource)(nil)
	_ resource.ResourceWithImportState = (*DataGroupResource)(nil)
)

// keep the generated schema package and schema builder imported.
var _ = schema.StringAttribute{}

// keep the types package imported (used by nested schema overrides).
var _ = types.NumberType

// NewDataGroupResource constructs the data_group resource.
func NewDataGroupResource() resource.Resource {
	return &DataGroupResource{}
}

type DataGroupResource struct {
	client *client.Client
}

func (r *DataGroupResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_data_group"
}

func (r *DataGroupResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	s := rsc.DataGroupResourceSchema(ctx)
	stabilizeComputed(s.Attributes)
	resp.Schema = s
}

func (r *DataGroupResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}
	r.client = c
}

// projectID resolves the project from the data_group project_id attribute (if any)
// falling back to the provider default.
func (r *DataGroupResource) projectID(ctx context.Context, raw tftypes.Value) (string, error) {
	pid, err := stringAttrFromRaw(raw, "project_id")
	if err == nil && pid != "" {
		return r.client.ProjectID(pid), nil
	}
	return r.client.ProjectID(""), nil
}

func (r *DataGroupResource) collectionPath(projectID string) string {
	return strings.NewReplacer("{project_id}", projectID).Replace("/api/app/projects/{project_id}/data-groups")
}

func (r *DataGroupResource) instancePath(projectID, id string) string {
	return strings.NewReplacer("{project_id}", projectID, "{data_group_id}", id).Replace("/api/app/projects/{project_id}/data-groups/{data_group_id}")
}

func (r *DataGroupResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	spec := DataGroupAttrSpec()
	projectID, err := r.projectID(ctx, req.Plan.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	body, err := client.WireFromRaw(req.Plan.Raw, spec)
	if err != nil {
		resp.Diagnostics.AddError("Encoding data_group request", err.Error())
		return
	}
	respBody, err := r.client.Do(ctx, "POST", r.collectionPath(projectID), body)
	if err != nil {
		resp.Diagnostics.AddError("Creating data_group", err.Error())
		return
	}
	wire, err := unwrapDataGroup(respBody)
	if err != nil {
		resp.Diagnostics.AddError("Decoding data_group response", err.Error())
		return
	}
	id := idForDataGroup(wire)
	r.writeDataGroupState(ctx, &resp.State, &resp.Diagnostics, req.Plan.Raw, wire, projectID, id)
}

func (r *DataGroupResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	projectID, err := r.projectID(ctx, req.State.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	id, err := stringAttrFromRaw(req.State.Raw, "data_group_id")
	if err != nil {
		resp.Diagnostics.AddError("Reading data_group id", err.Error())
		return
	}
	respBody, err := r.client.Do(ctx, "GET", r.collectionPath(projectID), nil)
	if err != nil {
		if apiErr, ok := err.(*client.APIError); ok && apiErr.StatusCode == 404 {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Reading data_group", err.Error())
		return
	}
	wire, found, err := findInList(respBody, true, "data_group_id", id)
	if err != nil {
		resp.Diagnostics.AddError("Decoding data_group response", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	// Merge against prior state: the list item may omit user-managed fields the
	// API never echoes back; preserve those instead of clobbering to null.
	r.writeDataGroupState(ctx, &resp.State, &resp.Diagnostics, req.State.Raw, wire, projectID, id)
}

func (r *DataGroupResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	spec := DataGroupAttrSpec()
	projectID, err := r.projectID(ctx, req.Plan.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	id, err := stringAttrFromRaw(req.State.Raw, "data_group_id")
	if err != nil {
		resp.Diagnostics.AddError("Reading data_group id", err.Error())
		return
	}
	body, err := client.WireFromRaw(req.Plan.Raw, spec)
	if err != nil {
		resp.Diagnostics.AddError("Encoding data_group request", err.Error())
		return
	}
	respBody, err := r.client.Do(ctx, "POST", r.instancePath(projectID, id), body)
	if err != nil {
		resp.Diagnostics.AddError("Updating data_group", err.Error())
		return
	}
	wire, err := unwrapDataGroup(respBody)
	if err != nil {
		resp.Diagnostics.AddError("Decoding data_group response", err.Error())
		return
	}
	r.writeDataGroupState(ctx, &resp.State, &resp.Diagnostics, req.Plan.Raw, wire, projectID, id)
}

func (r *DataGroupResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	projectID, err := r.projectID(ctx, req.State.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	id, err := stringAttrFromRaw(req.State.Raw, "data_group_id")
	if err != nil {
		resp.Diagnostics.AddError("Reading data_group id", err.Error())
		return
	}
	// DELETE may return a JSON body (Mixpanel convention); Do tolerates it.
	if _, err := r.client.Do(ctx, "DELETE", r.instancePath(projectID, id), nil); err != nil {
		if apiErr, ok := err.(*client.APIError); ok && apiErr.StatusCode == 404 {
			return
		}
		resp.Diagnostics.AddError("Deleting data_group", err.Error())
		return
	}
}

func (r *DataGroupResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.SplitN(req.ID, ":", 2)
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		resp.Diagnostics.AddError(
			"Invalid import ID",
			fmt.Sprintf("expected import ID in the form \"project_id:<id>\", got %q", req.ID),
		)
		return
	}
	setImportID(ctx, &resp.State, &resp.Diagnostics, "project_id", parts[0], "int64")
	setImportID(ctx, &resp.State, &resp.Diagnostics, "data_group_id", parts[1], "string")
}

// writeDataGroupState turns an unwrapped API body into resource state. base is the
// planned raw value (req.Plan.Raw) on create/update so config-supplied values are
// preserved verbatim, or a null tftypes.Value on read (state is rebuilt from the
// API response alone). See client.RawFromWireMerged for the merge semantics.
func (r *DataGroupResource) writeDataGroupState(ctx context.Context, state *tfsdk.State, diags *diagAppender, base tftypes.Value, wire map[string]any, projectID, id string) {
	extras := map[string]any{
		"data_group_id": id,
	}
	if projectID != "" {
		extras["project_id"] = projectID
	}
	schemaType := state.Schema.Type().TerraformType(ctx)
	val, err := client.RawFromWireMerged(schemaType, base, wire, extras, DataGroupAttrSpec())
	if err != nil {
		diags.AddError("Building data_group state", err.Error())
		return
	}
	state.Raw = val
}

// idForDataGroup extracts the identity value from an unwrapped response body.
func idForDataGroup(wire map[string]any) string {
	if v, ok := client.IDFromWire(wire, "data_group_id"); ok {
		return v
	}
	if v, ok := nestedID(wire, "data_group_id"); ok {
		return v
	}
	return ""
}

// unwrapDataGroup unwraps the API envelope (when enveloped) and returns the body map.
func unwrapDataGroup(respBody []byte) (map[string]any, error) {
	body, err := unwrapBody(respBody, true)
	if err != nil {
		return nil, err
	}
	return unwrapResultsMap(body, false), nil
}
