// Code generated by gen/crudgen.py. DO NOT EDIT.

package provider

import "github.com/mixpanel/terraform-provider-mixpanel/internal/client"

// EmailDigestAttrSpec describes the synthetic / jsonencode attributes of the email_digest
// entity to the generic tftypes<->JSON bridge in the client package. It is shared
// by the email_digest resource and data source.
func EmailDigestAttrSpec() client.AttrSpec {
	return client.AttrSpec{
		IDAttr:            "id",
		ProjectIDAttr:     "project_id",
		PathParamAttrs:    map[string]bool{"email_digest_id": true},
		JSONEncodeAttrs:   map[string]bool{"slack_subscriptions": true},
		JSONStringAttrs:   map[string]bool{},
		JSONEncodeWireKey: map[string]string{},
		OutputOnlyAttrs:   map[string]bool{"confirmed_date": true, "created": true, "creator_email": true, "creator_id": true, "dashboard_creator_email": true, "dashboard_foreign_private": true, "dashboard_has_owner_with_permissions": true, "dashboard_title": true, "digest_has_owner_with_permissions": true, "has_active_user": true, "schedule": true, "status": true, "workspace_id": true, "workspace_name": true},
		SpreadAttrs:       map[string]bool{},
	}
}
