// Code generated by gen/crudgen.py. DO NOT EDIT.

package provider

import "github.com/mixpanel/terraform-provider-mixpanel/internal/client"

// EventDefinitionAttrSpec describes the synthetic / jsonencode attributes of the event_definition
// entity to the generic tftypes<->JSON bridge in the client package. It is shared
// by the event_definition resource and data source.
func EventDefinitionAttrSpec() client.AttrSpec {
	return client.AttrSpec{
		IDAttr:            "id",
		ProjectIDAttr:     "project_id",
		PathParamAttrs:    map[string]bool{"event_definition_id": true},
		JSONEncodeAttrs:   map[string]bool{},
		JSONStringAttrs:   map[string]bool{},
		JSONEncodeWireKey: map[string]string{"created_utc": "createdUTC", "modified_utc": "modifiedUTC", "team_contacts": "team_contacts"},
		OutputOnlyAttrs:   map[string]bool{"collect_everything_event_id": true, "contacts": true, "created_utc": true, "custom_event_id": true, "description": true, "display_name": true, "dropped": true, "hidden": true, "last_modified": true, "merged": true, "merged_event_id": true, "modified_utc": true, "name": true, "platforms": true, "status": true, "tags": true, "team_contacts": true, "verified": true},
		SpreadAttrs:       map[string]bool{},
	}
}
