// Code generated by gen/crudgen.py. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-go/tftypes"

	"github.com/mixpanel/terraform-provider-mixpanel/internal/client"
	rsc "github.com/mixpanel/terraform-provider-mixpanel/internal/provider/resource_event_definition"
)

var (
	_ resource.Resource                = (*EventDefinitionResource)(nil)
	_ resource.ResourceWithConfigure   = (*EventDefinitionResource)(nil)
	_ resource.ResourceWithImportState = (*EventDefinitionResource)(nil)
)

// keep the generated schema package and schema builder imported.
var _ = schema.StringAttribute{}

// keep the types package imported (used by nested schema overrides).
var _ = types.NumberType

// NewEventDefinitionResource constructs the event_definition resource.
func NewEventDefinitionResource() resource.Resource {
	return &EventDefinitionResource{}
}

type EventDefinitionResource struct {
	client *client.Client
}

func (r *EventDefinitionResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_event_definition"
}

func (r *EventDefinitionResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	s := rsc.EventDefinitionResourceSchema(ctx)
	s.Attributes["definitions"] = schema.ListNestedAttribute{
		Required: true,
		NestedObject: schema.NestedAttributeObject{
			Attributes: map[string]schema.Attribute{
				"collect_everything_event": schema.StringAttribute{Optional: true},
				"custom_event":             schema.Int64Attribute{Optional: true},
				"description":              schema.StringAttribute{Optional: true},
				"name":                     schema.StringAttribute{Optional: true},
				"verified":                 schema.BoolAttribute{Optional: true},
			},
		},
	}
	stabilizeComputed(s.Attributes)
	resp.Schema = s
}

func (r *EventDefinitionResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}
	r.client = c
}

// projectID resolves the project from the event_definition project_id attribute (if any)
// falling back to the provider default.
func (r *EventDefinitionResource) projectID(ctx context.Context, raw tftypes.Value) (string, error) {
	pid, err := stringAttrFromRaw(raw, "project_id")
	if err == nil && pid != "" {
		return r.client.ProjectID(pid), nil
	}
	return r.client.ProjectID(""), nil
}

func (r *EventDefinitionResource) collectionPath(projectID string) string {
	return strings.NewReplacer("{project_id}", projectID).Replace("/api/app/projects/{project_id}/event-definitions")
}

func (r *EventDefinitionResource) instancePath(projectID, id string) string {
	return strings.NewReplacer("{project_id}", projectID, "{event_definition_id}", id).Replace("/api/app/projects/{project_id}/event-definitions/{event_definition_id}")
}

func (r *EventDefinitionResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	spec := EventDefinitionAttrSpec()
	projectID, err := r.projectID(ctx, req.Plan.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	body, err := client.WireFromRaw(req.Plan.Raw, spec)
	if err != nil {
		resp.Diagnostics.AddError("Encoding event_definition request", err.Error())
		return
	}
	respBody, err := r.client.Do(ctx, "POST", r.collectionPath(projectID), body)
	if err != nil {
		resp.Diagnostics.AddError("Creating event_definition", err.Error())
		return
	}
	// The create response is a FLAT id-bearing object (possibly inside a single-
	// element results list); extract the server-assigned id from it.
	id, err := flatCreateID(respBody, true, "id")
	if err != nil {
		resp.Diagnostics.AddError("Decoding event_definition create response", err.Error())
		return
	}
	if id == "" {
		resp.Diagnostics.AddError("Creating event_definition", "create response did not contain an id at id")
		return
	}
	// Read back the canonical body via the instance GET so state matches the read
	// schema (the create response shape differs from it).
	getBody, err := r.client.Do(ctx, "GET", r.instancePath(projectID, id), nil)
	if err != nil {
		resp.Diagnostics.AddError("Reading event_definition after create", err.Error())
		return
	}
	wire, err := unwrapEventDefinition(getBody)
	if err != nil {
		resp.Diagnostics.AddError("Decoding event_definition response", err.Error())
		return
	}
	r.writeEventDefinitionState(ctx, &resp.State, &resp.Diagnostics, req.Plan.Raw, wire, projectID, id)
}

func (r *EventDefinitionResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	projectID, err := r.projectID(ctx, req.State.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	id, err := stringAttrFromRaw(req.State.Raw, "id")
	if err != nil {
		resp.Diagnostics.AddError("Reading event_definition id", err.Error())
		return
	}
	respBody, err := r.client.Do(ctx, "GET", r.instancePath(projectID, id), nil)
	if err != nil {
		if apiErr, ok := err.(*client.APIError); ok && apiErr.StatusCode == 404 {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Reading event_definition", err.Error())
		return
	}
	wire, err := unwrapEventDefinition(respBody)
	if err != nil {
		resp.Diagnostics.AddError("Decoding event_definition response", err.Error())
		return
	}
	// Use the prior state as the merge base so attributes the user manages but
	// the API does not faithfully echo back on a GET (fields it never returns, or
	// returns enriched with server-assigned sub-keys such as a subscription id)
	// are preserved instead of being clobbered to null / a server-mangled shape,
	// which would otherwise produce a permanent post-refresh diff. Computed-only
	// values (absent from prior state) are still refreshed from the API response.
	r.writeEventDefinitionState(ctx, &resp.State, &resp.Diagnostics, req.State.Raw, wire, projectID, id)
}

func (r *EventDefinitionResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	spec := EventDefinitionAttrSpec()
	projectID, err := r.projectID(ctx, req.Plan.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	id, err := stringAttrFromRaw(req.State.Raw, "id")
	if err != nil {
		resp.Diagnostics.AddError("Reading event_definition id", err.Error())
		return
	}
	body, err := client.WireFromRaw(req.Plan.Raw, spec)
	if err != nil {
		resp.Diagnostics.AddError("Encoding event_definition request", err.Error())
		return
	}
	respBody, err := r.client.Do(ctx, "PATCH", r.instancePath(projectID, id), body)
	if err != nil {
		resp.Diagnostics.AddError("Updating event_definition", err.Error())
		return
	}
	wire, err := unwrapEventDefinition(respBody)
	if err != nil {
		resp.Diagnostics.AddError("Decoding event_definition response", err.Error())
		return
	}
	r.writeEventDefinitionState(ctx, &resp.State, &resp.Diagnostics, req.Plan.Raw, wire, projectID, id)
}

func (r *EventDefinitionResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	projectID, err := r.projectID(ctx, req.State.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	id, err := stringAttrFromRaw(req.State.Raw, "id")
	if err != nil {
		resp.Diagnostics.AddError("Reading event_definition id", err.Error())
		return
	}
	// DELETE may return a JSON body (Mixpanel convention); Do tolerates it.
	if _, err := r.client.Do(ctx, "DELETE", r.instancePath(projectID, id), nil); err != nil {
		if apiErr, ok := err.(*client.APIError); ok && apiErr.StatusCode == 404 {
			return
		}
		resp.Diagnostics.AddError("Deleting event_definition", err.Error())
		return
	}
}

func (r *EventDefinitionResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.SplitN(req.ID, ":", 2)
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		resp.Diagnostics.AddError(
			"Invalid import ID",
			fmt.Sprintf("expected import ID in the form \"project_id:<id>\", got %q", req.ID),
		)
		return
	}
	setImportID(ctx, &resp.State, &resp.Diagnostics, "project_id", parts[0], "int64")
	setImportID(ctx, &resp.State, &resp.Diagnostics, "id", parts[1], "int64")
}

// writeEventDefinitionState turns an unwrapped API body into resource state. base is the
// planned raw value (req.Plan.Raw) on create/update so config-supplied values are
// preserved verbatim, or a null tftypes.Value on read (state is rebuilt from the
// API response alone). See client.RawFromWireMerged for the merge semantics.
func (r *EventDefinitionResource) writeEventDefinitionState(ctx context.Context, state *tfsdk.State, diags *diagAppender, base tftypes.Value, wire map[string]any, projectID, id string) {
	extras := map[string]any{
		"id": id,
	}
	if projectID != "" {
		extras["project_id"] = projectID
	}
	extras["event_definition_id"] = id
	schemaType := state.Schema.Type().TerraformType(ctx)
	val, err := client.RawFromWireMerged(schemaType, base, wire, extras, EventDefinitionAttrSpec())
	if err != nil {
		diags.AddError("Building event_definition state", err.Error())
		return
	}
	state.Raw = val
}

// idForEventDefinition extracts the identity value from an unwrapped response body.
func idForEventDefinition(wire map[string]any) string {
	if v, ok := client.IDFromWire(wire, "id"); ok {
		return v
	}
	if v, ok := nestedID(wire, "id"); ok {
		return v
	}
	return ""
}

// unwrapEventDefinition unwraps the API envelope (when enveloped) and returns the body map.
func unwrapEventDefinition(respBody []byte) (map[string]any, error) {
	body, err := unwrapBody(respBody, true)
	if err != nil {
		return nil, err
	}
	return unwrapResultsMap(body, false), nil
}
