// Code generated by gen/crudgen.py. DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-go/tftypes"

	"github.com/mixpanel/terraform-provider-mixpanel/internal/client"
	rsc "github.com/mixpanel/terraform-provider-mixpanel/internal/provider/resource_formula"
)

var (
	_ resource.Resource                = (*FormulaResource)(nil)
	_ resource.ResourceWithConfigure   = (*FormulaResource)(nil)
	_ resource.ResourceWithImportState = (*FormulaResource)(nil)
)

// keep the generated schema package and schema builder imported.
var _ = schema.StringAttribute{}

// keep the types package imported (used by nested schema overrides).
var _ = types.NumberType

// NewFormulaResource constructs the formula resource.
func NewFormulaResource() resource.Resource {
	return &FormulaResource{}
}

type FormulaResource struct {
	client *client.Client
}

func (r *FormulaResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_formula"
}

func (r *FormulaResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	s := rsc.FormulaResourceSchema(ctx)
	stabilizeComputed(s.Attributes)
	resp.Schema = s
}

func (r *FormulaResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}
	r.client = c
}

// projectID resolves the project from the formula project_id attribute (if any)
// falling back to the provider default.
func (r *FormulaResource) projectID(ctx context.Context, raw tftypes.Value) (string, error) {
	pid, err := stringAttrFromRaw(raw, "project_id")
	if err == nil && pid != "" {
		return r.client.ProjectID(pid), nil
	}
	return r.client.ProjectID(""), nil
}

func (r *FormulaResource) collectionPath(projectID string) string {
	return strings.NewReplacer("{project_id}", projectID).Replace("/api/app/projects/{project_id}/metrics")
}

func (r *FormulaResource) instancePath(projectID, id string) string {
	return strings.NewReplacer("{project_id}", projectID, "{metric_id}", id).Replace("/api/app/projects/{project_id}/metrics/{metric_id}")
}

func (r *FormulaResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	spec := FormulaAttrSpec()
	projectID, err := r.projectID(ctx, req.Plan.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	body, err := client.WireFromRaw(req.Plan.Raw, spec)
	if err != nil {
		resp.Diagnostics.AddError("Encoding formula request", err.Error())
		return
	}
	respBody, err := r.client.Do(ctx, "POST", r.collectionPath(projectID), body)
	if err != nil {
		resp.Diagnostics.AddError("Creating formula", err.Error())
		return
	}
	wire, err := unwrapFormula(respBody)
	if err != nil {
		resp.Diagnostics.AddError("Decoding formula response", err.Error())
		return
	}
	id := idForFormula(wire)
	r.writeFormulaState(ctx, &resp.State, &resp.Diagnostics, req.Plan.Raw, wire, projectID, id)
}

func (r *FormulaResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	projectID, err := r.projectID(ctx, req.State.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	id, err := stringAttrFromRaw(req.State.Raw, "id")
	if err != nil {
		resp.Diagnostics.AddError("Reading formula id", err.Error())
		return
	}
	respBody, err := r.client.Do(ctx, "GET", r.instancePath(projectID, id), nil)
	if err != nil {
		if apiErr, ok := err.(*client.APIError); ok && apiErr.StatusCode == 404 {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Reading formula", err.Error())
		return
	}
	wire, err := unwrapFormula(respBody)
	if err != nil {
		resp.Diagnostics.AddError("Decoding formula response", err.Error())
		return
	}
	// Use the prior state as the merge base so attributes the user manages but
	// the API does not faithfully echo back on a GET (fields it never returns, or
	// returns enriched with server-assigned sub-keys such as a subscription id)
	// are preserved instead of being clobbered to null / a server-mangled shape,
	// which would otherwise produce a permanent post-refresh diff. Computed-only
	// values (absent from prior state) are still refreshed from the API response.
	r.writeFormulaState(ctx, &resp.State, &resp.Diagnostics, req.State.Raw, wire, projectID, id)
}

func (r *FormulaResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	spec := FormulaAttrSpec()
	projectID, err := r.projectID(ctx, req.Plan.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	id, err := stringAttrFromRaw(req.State.Raw, "id")
	if err != nil {
		resp.Diagnostics.AddError("Reading formula id", err.Error())
		return
	}
	body, err := client.WireFromRaw(req.Plan.Raw, spec)
	if err != nil {
		resp.Diagnostics.AddError("Encoding formula request", err.Error())
		return
	}
	respBody, err := r.client.Do(ctx, "PATCH", r.instancePath(projectID, id), body)
	if err != nil {
		resp.Diagnostics.AddError("Updating formula", err.Error())
		return
	}
	wire, err := unwrapFormula(respBody)
	if err != nil {
		resp.Diagnostics.AddError("Decoding formula response", err.Error())
		return
	}
	r.writeFormulaState(ctx, &resp.State, &resp.Diagnostics, req.Plan.Raw, wire, projectID, id)
}

func (r *FormulaResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	projectID, err := r.projectID(ctx, req.State.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	id, err := stringAttrFromRaw(req.State.Raw, "id")
	if err != nil {
		resp.Diagnostics.AddError("Reading formula id", err.Error())
		return
	}

	// Formula metrics require bulk DELETE (single-item DELETE returns 501).
	// Build a bulk delete request with a single metric.
	bulkBody := map[string]interface{}{
		"metrics": []map[string]interface{}{
			{"id": id},
		},
	}

	bodyBytes, err := json.Marshal(bulkBody)
	if err != nil {
		resp.Diagnostics.AddError("Encoding bulk delete request", err.Error())
		return
	}

	// Use collection path for bulk delete
	if _, err := r.client.Do(ctx, "DELETE", r.collectionPath(projectID), bodyBytes); err != nil {
		if apiErr, ok := err.(*client.APIError); ok && apiErr.StatusCode == 404 {
			return
		}
		resp.Diagnostics.AddError("Deleting formula", err.Error())
		return
	}
}

func (r *FormulaResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.SplitN(req.ID, ":", 2)
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		resp.Diagnostics.AddError(
			"Invalid import ID",
			fmt.Sprintf("expected import ID in the form \"project_id:<id>\", got %q", req.ID),
		)
		return
	}
	setImportID(ctx, &resp.State, &resp.Diagnostics, "project_id", parts[0], "int64")
	setImportID(ctx, &resp.State, &resp.Diagnostics, "id", parts[1], "int64")
}

// writeFormulaState turns an unwrapped API body into resource state. base is the
// planned raw value (req.Plan.Raw) on create/update so config-supplied values are
// preserved verbatim, or a null tftypes.Value on read (state is rebuilt from the
// API response alone). See client.RawFromWireMerged for the merge semantics.
func (r *FormulaResource) writeFormulaState(ctx context.Context, state *tfsdk.State, diags *diagAppender, base tftypes.Value, wire map[string]any, projectID, id string) {
	extras := map[string]any{
		"id": id,
	}
	if projectID != "" {
		extras["project_id"] = projectID
	}
	extras["metric_id"] = id
	schemaType := state.Schema.Type().TerraformType(ctx)
	val, err := client.RawFromWireMerged(schemaType, base, wire, extras, FormulaAttrSpec())
	if err != nil {
		diags.AddError("Building formula state", err.Error())
		return
	}
	state.Raw = val
}

// idForFormula extracts the identity value from an unwrapped response body.
func idForFormula(wire map[string]any) string {
	if v, ok := client.IDFromWire(wire, "id"); ok {
		return v
	}
	if v, ok := nestedID(wire, "id"); ok {
		return v
	}
	return ""
}

// unwrapFormula unwraps the API envelope (when enveloped) and returns the body map.
func unwrapFormula(respBody []byte) (map[string]any, error) {
	body, err := unwrapBody(respBody, true)
	if err != nil {
		return nil, err
	}
	return unwrapResultsMap(body, false), nil
}
