// Code generated by gen/crudgen.py. DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/plancheck"
)

func TestAccFormula_lifecycle(t *testing.T) {
	srv := newMockServer(t, mockOpts{enveloped: true, idField: "id", stringID: false, resultsMap: false, upsert: false, listCreate: false})

	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: testProtoV6,
		Steps: []resource.TestStep{
			{
				// Create; the implicit post-apply refresh+plan asserts idempotency.
				Config: providerConfig(srv.URL, `
resource "mixpanel_formula" "test" {
  name = "tf-acc-test"
  type = "tf-acc-test"
  definition = "tf-acc-test"
  project_id = 1
}`),
			},
			{
				// A changed attribute must plan as the expected action.
				Config: providerConfig(srv.URL, `
resource "mixpanel_formula" "test" {
  name = "tf-acc-renamed"
  type = "tf-acc-test"
  definition = "tf-acc-test"
  project_id = 1
}`),
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction("mixpanel_formula.test", plancheck.ResourceActionUpdate),
					},
				},
			},
			{
				// Import the resource and assert state round-trips through Read.
				ResourceName:                         "mixpanel_formula.test",
				ImportState:                          true,
				ImportStateVerify:                    true,
				ImportStateVerifyIdentifierAttribute: "id",
				ImportStateIdFunc:                    importIDFunc("mixpanel_formula.test", "id", "project_id"),
				ImportStateVerifyIgnore:              []string{"allow_staff_override", "can_share", "can_update_basic", "can_update_restricted", "can_update_visibility", "can_view", "created", "created_by", "definition", "is_locked", "is_superadmin", "is_visible", "last_verified", "last_verified_by", "modified"},
			},
		},
	})
}
