// Code generated by gen/crudgen.py. DO NOT EDIT.

package provider

import "github.com/mixpanel/terraform-provider-mixpanel/internal/client"

// HeatMapCollectionAttrSpec describes the synthetic / jsonencode attributes of the heat_map_collection
// entity to the generic tftypes<->JSON bridge in the client package. It is shared
// by the heat_map_collection resource and data source.
func HeatMapCollectionAttrSpec() client.AttrSpec {
	return client.AttrSpec{
		IDAttr:            "id",
		ProjectIDAttr:     "project_id",
		PathParamAttrs:    map[string]bool{"heat_map_collection_id": true},
		JSONEncodeAttrs:   map[string]bool{"heat_maps": true},
		JSONStringAttrs:   map[string]bool{},
		JSONEncodeWireKey: map[string]string{},
		OutputOnlyAttrs:   map[string]bool{"allow_staff_override": true, "can_pin": true, "can_share": true, "can_update_basic": true, "can_view": true, "is_shared_with_project": true, "is_superadmin": true, "last_modified_by_email": true, "last_modified_by_id": true, "last_modified_by_name": true},
		SpreadAttrs:       map[string]bool{},
	}
}
