// Code generated by gen/crudgen.py. DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/plancheck"
)

func TestAccHeatMapCollection_lifecycle(t *testing.T) {
	srv := newMockServer(t, mockOpts{enveloped: true, idField: "id", stringID: true, resultsMap: false, upsert: false, listCreate: false})

	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: testProtoV6,
		Steps: []resource.TestStep{
			{
				// Create; the implicit post-apply refresh+plan asserts idempotency.
				Config: providerConfig(srv.URL, `
resource "mixpanel_heat_map_collection" "test" {
  name = "tf-acc-test"
}`),
			},
			{
				// A changed attribute must plan as the expected action.
				Config: providerConfig(srv.URL, `
resource "mixpanel_heat_map_collection" "test" {
  name = "tf-acc-renamed"
}`),
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction("mixpanel_heat_map_collection.test", plancheck.ResourceActionUpdate),
					},
				},
			},
			{
				// Import the resource and assert state round-trips through Read.
				ResourceName:                         "mixpanel_heat_map_collection.test",
				ImportState:                          true,
				ImportStateVerify:                    true,
				ImportStateVerifyIdentifierAttribute: "id",
				ImportStateIdFunc:                    importIDFunc("mixpanel_heat_map_collection.test", "id", "project_id"),
				ImportStateVerifyIgnore:              []string{"allow_staff_override", "can_pin", "can_share", "can_update_basic", "can_view", "heat_maps", "is_shared_with_project", "is_superadmin", "last_modified_by_email", "last_modified_by_id", "last_modified_by_name"},
			},
		},
	})
}
