// Code generated by gen/crudgen.py. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-go/tftypes"

	"github.com/mixpanel/terraform-provider-mixpanel/internal/client"
	rsc "github.com/mixpanel/terraform-provider-mixpanel/internal/provider/resource_lexicon_tag"
)

var (
	_ resource.Resource                = (*LexiconTagResource)(nil)
	_ resource.ResourceWithConfigure   = (*LexiconTagResource)(nil)
	_ resource.ResourceWithImportState = (*LexiconTagResource)(nil)
)

// keep the generated schema package and schema builder imported.
var _ = schema.StringAttribute{}

// keep the types package imported (used by nested schema overrides).
var _ = types.NumberType

// NewLexiconTagResource constructs the lexicon_tag resource.
func NewLexiconTagResource() resource.Resource {
	return &LexiconTagResource{}
}

type LexiconTagResource struct {
	client *client.Client
	// workspacePathBuilder resolves the canonical workspace per project (cached,
	// thread-safe) so data-definitions calls can target the workspace mount the
	// Mixpanel UI uses (same pick order as feature_flag: global, default, first).
	workspacePathBuilder *client.WorkspacePathBuilder
}

func (r *LexiconTagResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_lexicon_tag"
}

func (r *LexiconTagResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	s := rsc.LexiconTagResourceSchema(ctx)
	stabilizeComputed(s.Attributes)
	resp.Schema = s
}

func (r *LexiconTagResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}
	r.client = c
	r.workspacePathBuilder = client.NewWorkspacePathBuilder(c)
}

// projectID resolves the project from the lexicon_tag project_id attribute (if any)
// falling back to the provider default.
func (r *LexiconTagResource) projectID(ctx context.Context, raw tftypes.Value) (string, error) {
	pid, err := stringAttrFromRaw(raw, "project_id")
	if err == nil && pid != "" {
		return r.client.ProjectID(pid), nil
	}
	return r.client.ProjectID(""), nil
}

// dataDefinitionsBases returns the ordered data-definitions base paths to try
// for a project. The webapp mounts the same data-definitions urlconf on BOTH
// /api/app/projects/{project_id}/data-definitions (app_api/projects/urls.py)
// and /api/app/workspaces/{workspace_id}/data-definitions
// (app_api/workspaces/urls.py); both variants address the same project-keyed
// rows. The Mixpanel UI (appApiUrl) addresses the workspace mount whenever the
// project has workspaces, and the backend counts project-mount calls on
// workspace-enabled projects as "workspace.unexpected-project-url", so the
// provider prefers the workspace mount, resolving the canonical workspace with
// the same pick order feature_flag uses (global, then default, then first).
// The project mount is kept as a fallback: it is the only mount for projects
// without workspaces, and the workspace mount 404s before reaching the view
// when the caller is not a member of the resolved workspace (live-verified;
// service-account users are membership-checked like any other user).
func (r *LexiconTagResource) dataDefinitionsBases(ctx context.Context, projectID string) []string {
	projectBase := "/api/app/projects/" + projectID + "/data-definitions"
	if r.workspacePathBuilder != nil {
		if wid, err := r.workspacePathBuilder.WorkspaceID(ctx, projectID); err == nil && wid != "" {
			return []string{"/api/app/workspaces/" + wid + "/data-definitions", projectBase}
		}
	}
	return []string{projectBase}
}

// doDataDefinitions issues one data-definitions request, preferring the
// workspace mount and retrying the project mount on 404. The workspace-mount
// membership check rejects non-members with 404 before the view runs, so no
// side effect has occurred when the retry fires; both mounts hit identical
// storage, so a genuine not-found 404s on the fallback too and surfaces as the
// final error.
func (r *LexiconTagResource) doDataDefinitions(ctx context.Context, method, projectID, suffix string, body any) ([]byte, error) {
	bases := r.dataDefinitionsBases(ctx, projectID)
	var lastErr error
	for i, base := range bases {
		respBody, err := r.client.Do(ctx, method, base+suffix, body)
		if err == nil {
			return respBody, nil
		}
		lastErr = err
		if apiErr, ok := err.(*client.APIError); ok && apiErr.StatusCode == 404 && i < len(bases)-1 {
			continue
		}
		return nil, err
	}
	return nil, lastErr
}

func (r *LexiconTagResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	spec := LexiconTagAttrSpec()
	projectID, err := r.projectID(ctx, req.Plan.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	body, err := client.WireFromRawForCreate(req.Plan.Raw, spec)
	if err != nil {
		resp.Diagnostics.AddError("Encoding lexicon_tag request", err.Error())
		return
	}
	respBody, err := r.doDataDefinitions(ctx, "POST", projectID, "/tags", body)
	if err != nil {
		resp.Diagnostics.AddError("Creating lexicon_tag", err.Error())
		return
	}
	wire, err := unwrapLexiconTag(respBody)
	if err != nil {
		resp.Diagnostics.AddError("Decoding lexicon_tag response", err.Error())
		return
	}
	id := idForLexiconTag(wire)
	r.writeLexiconTagState(ctx, &resp.State, &resp.Diagnostics, req.Plan.Raw, wire, projectID, id)
}

func (r *LexiconTagResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	projectID, err := r.projectID(ctx, req.State.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	id, err := stringAttrFromRaw(req.State.Raw, "id")
	if err != nil {
		resp.Diagnostics.AddError("Reading lexicon_tag id", err.Error())
		return
	}
	respBody, err := r.doDataDefinitions(ctx, "GET", projectID, "/tags/"+id, nil)
	if err != nil {
		if apiErr, ok := err.(*client.APIError); ok && apiErr.StatusCode == 404 {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Reading lexicon_tag", err.Error())
		return
	}
	wire, err := unwrapLexiconTag(respBody)
	if err != nil {
		resp.Diagnostics.AddError("Decoding lexicon_tag response", err.Error())
		return
	}
	// Use the prior state as the merge base so attributes the user manages but
	// the API does not faithfully echo back on a GET (fields it never returns, or
	// returns enriched with server-assigned sub-keys such as a subscription id)
	// are preserved instead of being clobbered to null / a server-mangled shape,
	// which would otherwise produce a permanent post-refresh diff. Computed-only
	// values (absent from prior state) are still refreshed from the API response.
	r.writeLexiconTagState(ctx, &resp.State, &resp.Diagnostics, req.State.Raw, wire, projectID, id)
}

func (r *LexiconTagResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	spec := LexiconTagAttrSpec()
	projectID, err := r.projectID(ctx, req.Plan.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	id, err := stringAttrFromRaw(req.State.Raw, "id")
	if err != nil {
		resp.Diagnostics.AddError("Reading lexicon_tag id", err.Error())
		return
	}
	body, err := client.WireFromRawForUpdate(req.Plan.Raw, spec)
	if err != nil {
		resp.Diagnostics.AddError("Encoding lexicon_tag request", err.Error())
		return
	}
	respBody, err := r.doDataDefinitions(ctx, "PATCH", projectID, "/tags/"+id, body)
	if err != nil {
		resp.Diagnostics.AddError("Updating lexicon_tag", err.Error())
		return
	}
	wire, err := unwrapLexiconTag(respBody)
	if err != nil {
		resp.Diagnostics.AddError("Decoding lexicon_tag response", err.Error())
		return
	}
	r.writeLexiconTagState(ctx, &resp.State, &resp.Diagnostics, req.Plan.Raw, wire, projectID, id)
}

func (r *LexiconTagResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	projectID, err := r.projectID(ctx, req.State.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	id, err := stringAttrFromRaw(req.State.Raw, "id")
	if err != nil {
		resp.Diagnostics.AddError("Reading lexicon_tag id", err.Error())
		return
	}
	// DELETE may return a JSON body (Mixpanel convention); Do tolerates it.
	if _, err := r.doDataDefinitions(ctx, "DELETE", projectID, "/tags/"+id, nil); err != nil {
		if apiErr, ok := err.(*client.APIError); ok && apiErr.StatusCode == 404 {
			return
		}
		resp.Diagnostics.AddError("Deleting lexicon_tag", err.Error())
		return
	}
}

func (r *LexiconTagResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.SplitN(req.ID, ":", 2)
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		resp.Diagnostics.AddError(
			"Invalid import ID",
			fmt.Sprintf("expected import ID in the form \"project_id:<id>\", got %q", req.ID),
		)
		return
	}
	setImportID(ctx, &resp.State, &resp.Diagnostics, "project_id", parts[0], "int64")
	setImportID(ctx, &resp.State, &resp.Diagnostics, "id", parts[1], "int64")
}

// writeLexiconTagState turns an unwrapped API body into resource state. base is the
// planned raw value (req.Plan.Raw) on create/update so config-supplied values are
// preserved verbatim, or a null tftypes.Value on read (state is rebuilt from the
// API response alone). See client.RawFromWireMerged for the merge semantics.
func (r *LexiconTagResource) writeLexiconTagState(ctx context.Context, state *tfsdk.State, diags *diagAppender, base tftypes.Value, wire map[string]any, projectID, id string) {
	extras := map[string]any{
		"id": id,
	}
	if projectID != "" {
		extras["project_id"] = projectID
	}
	extras["tag_id"] = id
	schemaType := state.Schema.Type().TerraformType(ctx)
	val, err := client.RawFromWireMerged(schemaType, base, wire, extras, LexiconTagAttrSpec())
	if err != nil {
		diags.AddError("Building lexicon_tag state", err.Error())
		return
	}
	state.Raw = val
}

// idForLexiconTag extracts the identity value from an unwrapped response body.
func idForLexiconTag(wire map[string]any) string {
	if v, ok := client.IDFromWire(wire, "id"); ok {
		return v
	}
	if v, ok := nestedID(wire, "id"); ok {
		return v
	}
	return ""
}

// unwrapLexiconTag unwraps the API envelope (when enveloped) and returns the body map.
func unwrapLexiconTag(respBody []byte) (map[string]any, error) {
	body, err := unwrapBody(respBody, true)
	if err != nil {
		return nil, err
	}
	return unwrapResultsMap(body, false), nil
}
