// Code generated by gen/crudgen.py. DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccOrgSessionSettings_lifecycle(t *testing.T) {
	srv := newMockServer(t, mockOpts{enveloped: true, idField: "id", stringID: true, resultsMap: false, upsert: false, listCreate: false})

	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: testProtoV6,
		Steps: []resource.TestStep{
			{
				// Create; the implicit post-apply refresh+plan asserts idempotency.
				Config: providerConfig(srv.URL, `
resource "mixpanel_org_session_settings" "test" {

}`),
			},
			{
				// Import the resource and assert state round-trips through Read.
				ResourceName:                         "mixpanel_org_session_settings.test",
				ImportState:                          true,
				ImportStateVerify:                    true,
				ImportStateVerifyIdentifierAttribute: "id",
				ImportStateIdFunc:                    importIDFunc("mixpanel_org_session_settings.test", "id", ""),
				ImportStateVerifyIgnore:              []string{"settings"},
			},
		},
	})
}
