// Code generated by gen/crudgen.py. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-go/tftypes"

	"github.com/mixpanel/terraform-provider-mixpanel/internal/client"
	rsc "github.com/mixpanel/terraform-provider-mixpanel/internal/provider/resource_org_session_settings"
)

var (
	_ resource.Resource                = (*OrgSessionSettingsResource)(nil)
	_ resource.ResourceWithConfigure   = (*OrgSessionSettingsResource)(nil)
	_ resource.ResourceWithImportState = (*OrgSessionSettingsResource)(nil)
)

// keep the generated schema package and schema builder imported.
var _ = schema.StringAttribute{}

// keep the types package imported (used by nested schema overrides).
var _ = types.NumberType

// NewOrgSessionSettingsResource constructs the org_session_settings resource.
func NewOrgSessionSettingsResource() resource.Resource {
	return &OrgSessionSettingsResource{}
}

type OrgSessionSettingsResource struct {
	client *client.Client
}

func (r *OrgSessionSettingsResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_org_session_settings"
}

func (r *OrgSessionSettingsResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	s := rsc.OrgSessionSettingsResourceSchema(ctx)
	s.Attributes["id"] = schema.StringAttribute{Computed: true}
	requireReplace(s.Attributes, "organization_id")
	stabilizeComputed(s.Attributes)
	resp.Schema = s
}

func (r *OrgSessionSettingsResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}
	r.client = c
}

// projectID resolves the project from the org_session_settings project_id attribute (if any)
// falling back to the provider default.
func (r *OrgSessionSettingsResource) projectID(ctx context.Context, raw tftypes.Value) (string, error) {
	oid, err := stringAttrFromRaw(raw, "organization_id")
	if err == nil && oid != "" {
		return r.client.OrganizationID(oid), nil
	}
	return r.client.OrganizationID(""), nil
}

func (r *OrgSessionSettingsResource) collectionPath(projectID string) string {
	return strings.NewReplacer("{organization_id}", projectID).Replace("/organizations/{organization_id}/org-session-settings")
}

func (r *OrgSessionSettingsResource) instancePath(projectID, id string) string {
	return strings.NewReplacer("{organization_id}", projectID, "{id}", id).Replace("/organizations/{organization_id}/org-session-settings")
}

func (r *OrgSessionSettingsResource) updatePath(scopeID string) string {
	return strings.NewReplacer("{organization_id}", scopeID).Replace("/organizations/{organization_id}/org-session-settings/update")
}

func (r *OrgSessionSettingsResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	spec := OrgSessionSettingsAttrSpec()
	scopeID, err := r.projectID(ctx, req.Plan.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving scope id", err.Error())
		return
	}
	full, err := client.WireFromRaw(req.Plan.Raw, spec)
	if err != nil {
		resp.Diagnostics.AddError("Encoding org_session_settings request", err.Error())
		return
	}
	// The whole settings object lives under the single "settings" jsonencode attr;
	// POST the inner object (the update endpoint takes the settings fields directly).
	// settings is Optional+Computed: when the user omits it, full["settings"] is nil
	// and there is nothing to write -- skip the POST (POSTing a null/empty body can
	// error or silently clear the scope's settings) and just adopt the live values.
	if body, ok := full["settings"]; ok && body != nil {
		if _, err := r.client.Do(ctx, "POST", r.updatePath(scopeID), body); err != nil {
			resp.Diagnostics.AddError("Creating org_session_settings", err.Error())
			return
		}
	}
	getBody, err := r.client.Do(ctx, "GET", r.collectionPath(scopeID), nil)
	if err != nil {
		resp.Diagnostics.AddError("Reading org_session_settings after create", err.Error())
		return
	}
	wire, err := unwrapOrgSessionSettings(getBody)
	if err != nil {
		resp.Diagnostics.AddError("Decoding org_session_settings response", err.Error())
		return
	}
	wire = wrapSingleton(wire, "settings")
	r.writeOrgSessionSettingsState(ctx, &resp.State, &resp.Diagnostics, req.Plan.Raw, wire, scopeID, scopeID)
}

func (r *OrgSessionSettingsResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	projectID, err := r.projectID(ctx, req.State.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	respBody, err := r.client.Do(ctx, "GET", r.collectionPath(projectID), nil)
	if err != nil {
		if apiErr, ok := err.(*client.APIError); ok && apiErr.StatusCode == 404 {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Reading org_session_settings", err.Error())
		return
	}
	wire, err := unwrapOrgSessionSettings(respBody)
	if err != nil {
		resp.Diagnostics.AddError("Decoding org_session_settings response", err.Error())
		return
	}
	wire = wrapSingleton(wire, "settings")
	// synthetic id = project id (a project singleton has one settings object).
	r.writeOrgSessionSettingsState(ctx, &resp.State, &resp.Diagnostics, req.State.Raw, wire, projectID, projectID)
}

func (r *OrgSessionSettingsResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	spec := OrgSessionSettingsAttrSpec()
	scopeID, err := r.projectID(ctx, req.Plan.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving scope id", err.Error())
		return
	}
	full, err := client.WireFromRaw(req.Plan.Raw, spec)
	if err != nil {
		resp.Diagnostics.AddError("Encoding org_session_settings request", err.Error())
		return
	}
	// settings is Optional+Computed: a nil body means "no change" -- skip the POST
	// (a null/empty body can error or silently clear the scope's settings) and adopt
	// the current live values via the read-back below.
	if body, ok := full["settings"]; ok && body != nil {
		if _, err := r.client.Do(ctx, "POST", r.updatePath(scopeID), body); err != nil {
			resp.Diagnostics.AddError("Updating org_session_settings", err.Error())
			return
		}
	}
	getBody, err := r.client.Do(ctx, "GET", r.collectionPath(scopeID), nil)
	if err != nil {
		resp.Diagnostics.AddError("Reading org_session_settings after update", err.Error())
		return
	}
	wire, err := unwrapOrgSessionSettings(getBody)
	if err != nil {
		resp.Diagnostics.AddError("Decoding org_session_settings response", err.Error())
		return
	}
	wire = wrapSingleton(wire, "settings")
	r.writeOrgSessionSettingsState(ctx, &resp.State, &resp.Diagnostics, req.Plan.Raw, wire, scopeID, scopeID)
}

func (r *OrgSessionSettingsResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	// org_session_settings is a project singleton: destroy removes it from state only and does
	// NOT mutate the API (the settings are project-global and cannot be deleted).
	_ = ctx
	_ = req
	_ = resp
}

func (r *OrgSessionSettingsResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	if req.ID == "" {
		resp.Diagnostics.AddError(
			"Invalid import ID",
			"expected import ID to be the project id (the singleton has no separate id)",
		)
		return
	}
	setImportID(ctx, &resp.State, &resp.Diagnostics, "organization_id", req.ID, "int64")
	setImportID(ctx, &resp.State, &resp.Diagnostics, "id", req.ID, "string")
}

// writeOrgSessionSettingsState turns an unwrapped API body into resource state. base is the
// planned raw value (req.Plan.Raw) on create/update so config-supplied values are
// preserved verbatim, or a null tftypes.Value on read (state is rebuilt from the
// API response alone). See client.RawFromWireMerged for the merge semantics.
func (r *OrgSessionSettingsResource) writeOrgSessionSettingsState(ctx context.Context, state *tfsdk.State, diags *diagAppender, base tftypes.Value, wire map[string]any, projectID, id string) {
	extras := map[string]any{
		"id": id,
	}
	if projectID != "" {
		extras["organization_id"] = projectID
	}
	schemaType := state.Schema.Type().TerraformType(ctx)
	val, err := client.RawFromWireMerged(schemaType, base, wire, extras, OrgSessionSettingsAttrSpec())
	if err != nil {
		diags.AddError("Building org_session_settings state", err.Error())
		return
	}
	state.Raw = val
}

// idForOrgSessionSettings extracts the identity value from an unwrapped response body.
func idForOrgSessionSettings(wire map[string]any) string {
	if v, ok := client.IDFromWire(wire, "id"); ok {
		return v
	}
	if v, ok := nestedID(wire, "id"); ok {
		return v
	}
	return ""
}

// unwrapOrgSessionSettings unwraps the API envelope (when enveloped) and returns the body map.
func unwrapOrgSessionSettings(respBody []byte) (map[string]any, error) {
	body, err := unwrapBody(respBody, true)
	if err != nil {
		return nil, err
	}
	return unwrapResultsMap(body, false), nil
}
