// Code generated by gen/crudgen.py. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-go/tftypes"

	"github.com/mixpanel/terraform-provider-mixpanel/internal/client"
	rsc "github.com/mixpanel/terraform-provider-mixpanel/internal/provider/resource_playlist"
)

var (
	_ resource.Resource                = (*PlaylistResource)(nil)
	_ resource.ResourceWithConfigure   = (*PlaylistResource)(nil)
	_ resource.ResourceWithImportState = (*PlaylistResource)(nil)
)

// keep the generated schema package and schema builder imported.
var _ = schema.StringAttribute{}

// keep the types package imported (used by nested schema overrides).
var _ = types.NumberType

// NewPlaylistResource constructs the playlist resource.
func NewPlaylistResource() resource.Resource {
	return &PlaylistResource{}
}

type PlaylistResource struct {
	client *client.Client
}

func (r *PlaylistResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_playlist"
}

func (r *PlaylistResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	s := rsc.PlaylistResourceSchema(ctx)
	s.Attributes["filters"] = schema.StringAttribute{Optional: true, Computed: true}
	s.Attributes["time_filter"] = schema.StringAttribute{Optional: true, Computed: true}
	normalizedJSON(s.Attributes, "filters", "time_filter")
	stabilizeComputed(s.Attributes)
	resp.Schema = s
}

func (r *PlaylistResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}
	r.client = c
}

// projectID resolves the project from the playlist project_id attribute (if any)
// falling back to the provider default.
func (r *PlaylistResource) projectID(ctx context.Context, raw tftypes.Value) (string, error) {
	pid, err := stringAttrFromRaw(raw, "project_id")
	if err == nil && pid != "" {
		return r.client.ProjectID(pid), nil
	}
	return r.client.ProjectID(""), nil
}

func (r *PlaylistResource) collectionPath(projectID string) string {
	return strings.NewReplacer("{project_id}", projectID).Replace("/api/app/projects/{project_id}/playlists")
}

func (r *PlaylistResource) instancePath(projectID, id string) string {
	return strings.NewReplacer("{project_id}", projectID, "{playlist_id}", id).Replace("/api/app/projects/{project_id}/playlists/{playlist_id}")
}

func (r *PlaylistResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	spec := PlaylistAttrSpec()
	projectID, err := r.projectID(ctx, req.Plan.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	body, err := client.WireFromRawForCreate(req.Plan.Raw, spec)
	if err != nil {
		resp.Diagnostics.AddError("Encoding playlist request", err.Error())
		return
	}
	respBody, err := r.client.Do(ctx, "POST", r.collectionPath(projectID), body)
	if err != nil {
		resp.Diagnostics.AddError("Creating playlist", err.Error())
		return
	}
	wire, err := unwrapPlaylist(respBody)
	if err != nil {
		resp.Diagnostics.AddError("Decoding playlist response", err.Error())
		return
	}
	id := idForPlaylist(wire)
	r.writePlaylistState(ctx, &resp.State, &resp.Diagnostics, client.MergeApply, req.Plan.Raw, wire, projectID, id)
}

func (r *PlaylistResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	projectID, err := r.projectID(ctx, req.State.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	id, err := stringAttrFromRaw(req.State.Raw, "id")
	if err != nil {
		resp.Diagnostics.AddError("Reading playlist id", err.Error())
		return
	}
	respBody, err := r.client.Do(ctx, "GET", r.instancePath(projectID, id), nil)
	if err != nil {
		if apiErr, ok := err.(*client.APIError); ok && apiErr.StatusCode == 404 {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Reading playlist", err.Error())
		return
	}
	wire, err := unwrapPlaylist(respBody)
	if err != nil {
		resp.Diagnostics.AddError("Decoding playlist response", err.Error())
		return
	}
	// Wire-preferred refresh (client.MergeRead): the API response wins for every
	// attribute it carries, so out-of-band edits become visible to `terraform
	// plan` as drift. The prior state is the merge base only for attributes the
	// GET omits (fields the API never echoes back, write-only secrets, spread
	// attributes) — those are preserved instead of being clobbered to null.
	r.writePlaylistState(ctx, &resp.State, &resp.Diagnostics, client.MergeRead, req.State.Raw, wire, projectID, id)
}

func (r *PlaylistResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	spec := PlaylistAttrSpec()
	projectID, err := r.projectID(ctx, req.Plan.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	id, err := stringAttrFromRaw(req.State.Raw, "id")
	if err != nil {
		resp.Diagnostics.AddError("Reading playlist id", err.Error())
		return
	}
	body, err := client.WireFromRawForUpdate(req.Plan.Raw, spec)
	if err != nil {
		resp.Diagnostics.AddError("Encoding playlist request", err.Error())
		return
	}
	respBody, err := r.client.Do(ctx, "PUT", r.instancePath(projectID, id), body)
	if err != nil {
		resp.Diagnostics.AddError("Updating playlist", err.Error())
		return
	}
	wire, err := unwrapPlaylist(respBody)
	if err != nil {
		resp.Diagnostics.AddError("Decoding playlist response", err.Error())
		return
	}
	r.writePlaylistState(ctx, &resp.State, &resp.Diagnostics, client.MergeApply, req.Plan.Raw, wire, projectID, id)
}

func (r *PlaylistResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	projectID, err := r.projectID(ctx, req.State.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	id, err := stringAttrFromRaw(req.State.Raw, "id")
	if err != nil {
		resp.Diagnostics.AddError("Reading playlist id", err.Error())
		return
	}
	// DELETE may return a JSON body (Mixpanel convention); Do tolerates it.
	if _, err := r.client.Do(ctx, "DELETE", r.instancePath(projectID, id), nil); err != nil {
		if apiErr, ok := err.(*client.APIError); ok && apiErr.StatusCode == 404 {
			return
		}
		resp.Diagnostics.AddError("Deleting playlist", err.Error())
		return
	}
}

func (r *PlaylistResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.SplitN(req.ID, ":", 2)
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		resp.Diagnostics.AddError(
			"Invalid import ID",
			fmt.Sprintf("expected import ID in the form \"project_id:<id>\", got %q", req.ID),
		)
		return
	}
	setImportID(ctx, &resp.State, &resp.Diagnostics, "project_id", parts[0], "int64")
	setImportID(ctx, &resp.State, &resp.Diagnostics, "id", parts[1], "string")
}

// writePlaylistState turns an unwrapped API body into resource state. On
// create/update (client.MergeApply, base = req.Plan.Raw) config-supplied values
// are preserved verbatim; on read (client.MergeRead, base = req.State.Raw) the
// API response wins wherever it carries a field, so drift is refreshed into
// state. See client.RawFromWireMerged for the exact merge semantics.
func (r *PlaylistResource) writePlaylistState(ctx context.Context, state *tfsdk.State, diags *diagAppender, mode client.MergeMode, base tftypes.Value, wire map[string]any, projectID, id string) {
	extras := map[string]any{
		"id": id,
	}
	if projectID != "" {
		extras["project_id"] = projectID
	}
	extras["playlist_id"] = id
	schemaType := state.Schema.Type().TerraformType(ctx)
	val, err := client.RawFromWireMerged(schemaType, mode, base, wire, extras, PlaylistAttrSpec())
	if err != nil {
		diags.AddError("Building playlist state", err.Error())
		return
	}
	state.Raw = val
}

// idForPlaylist extracts the identity value from an unwrapped response body.
func idForPlaylist(wire map[string]any) string {
	if v, ok := client.IDFromWire(wire, "id"); ok {
		return v
	}
	if v, ok := nestedID(wire, "id"); ok {
		return v
	}
	return ""
}

// unwrapPlaylist unwraps the API envelope (when enveloped) and returns the body map.
func unwrapPlaylist(respBody []byte) (map[string]any, error) {
	body, err := unwrapBody(respBody, true)
	if err != nil {
		return nil, err
	}
	return unwrapResultsMap(body, false), nil
}
