// Code generated by gen/crudgen.py. DO NOT EDIT.
//
// HAND-EDITED EXCEPTION: project supports an in-place rename via the legacy
// webapp endpoint POST /projects/update/{id}/ (form-encoded). The generic mock
// server does not model that route, so this test wraps it with a handler that
// does. Keep in sync with project_resource.go.

package provider

import (
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/plancheck"
)

// newProjectMockServer wraps the generic RPC-lifecycle mock with the legacy
// rename route POST /projects/update/{id}/ (form-encoded "name", returns
// {"updated": true} or an HTTP-200 {"error": ...} like the real endpoint).
func newProjectMockServer(t *testing.T) (*mockServer, *httptest.Server) {
	t.Helper()
	m := newMockServer(t, mockOpts{enveloped: true, idField: "id", stringID: false, resultsMap: false, upsert: false, listCreate: false, rpcLifecycle: true, createNameKey: "projectNames", idListKey: "projectIds", matchAttr: "name"})
	wrapped := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method == http.MethodPost && strings.HasPrefix(r.URL.Path, "/projects/update/") {
			id := strings.Trim(strings.TrimPrefix(r.URL.Path, "/projects/update/"), "/")
			_ = r.ParseForm()
			name := r.PostForm.Get("name")
			w.Header().Set("Content-Type", "application/json")
			m.mu.Lock()
			obj, ok := m.store[id]
			if ok && name != "" {
				obj["name"] = name
			}
			m.mu.Unlock()
			if !ok {
				// The real endpoint reports failures as HTTP 200 + {"error": ...}.
				_, _ = w.Write([]byte(`{"error": "Invalid project"}`))
				return
			}
			_, _ = w.Write([]byte(`{"updated": true}`))
			return
		}
		m.handle(w, r)
	}))
	t.Cleanup(wrapped.Close)
	return m, wrapped
}

func TestAccProject_lifecycle(t *testing.T) {
	_, srv := newProjectMockServer(t)

	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: testProtoV6,
		Steps: []resource.TestStep{
			{
				// Create; the implicit post-apply refresh+plan asserts idempotency.
				Config: providerConfig(srv.URL, `
resource "mixpanel_project" "test" {
  name = "tf-acc-test"
}`),
			},
			{
				// A name change must plan as an in-place update (NOT a replace:
				// replacing a project deletes it and all its data) and the rename
				// must round-trip through POST /projects/update/{id}/.
				Config: providerConfig(srv.URL, `
resource "mixpanel_project" "test" {
  name = "tf-acc-renamed"
}`),
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction("mixpanel_project.test", plancheck.ResourceActionUpdate),
					},
				},
				Check: resource.TestCheckResourceAttr("mixpanel_project.test", "name", "tf-acc-renamed"),
			},
			{
				// Import the resource and assert state round-trips through Read.
				ResourceName:                         "mixpanel_project.test",
				ImportState:                          true,
				ImportStateVerify:                    true,
				ImportStateVerifyIdentifierAttribute: "id",
				ImportStateIdFunc:                    importIDFunc("mixpanel_project.test", "id", "organization_id"),
				ImportStateVerifyIgnore:              []string{"api_key", "api_secret", "timezone_name", "token", "url"},
			},
		},
	})
}
