// Code generated by gen/crudgen.py. DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/plancheck"
)

func TestAccProject_lifecycle(t *testing.T) {
	srv := newMockServer(t, mockOpts{enveloped: true, idField: "id", stringID: false, resultsMap: false, upsert: false, listCreate: false})

	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: testProtoV6,
		Steps: []resource.TestStep{
			{
				// Create; the implicit post-apply refresh+plan asserts idempotency.
				Config: providerConfig(srv.URL, `
resource "mixpanel_project" "test" {
  name = "tf-acc-test"
}`),
			},
			{
				// A changed attribute must plan as the expected action.
				Config: providerConfig(srv.URL, `
resource "mixpanel_project" "test" {
  name = "tf-acc-renamed"
}`),
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction("mixpanel_project.test", plancheck.ResourceActionReplace),
					},
				},
			},
			{
				// Import the resource and assert state round-trips through Read.
				ResourceName:                         "mixpanel_project.test",
				ImportState:                          true,
				ImportStateVerify:                    true,
				ImportStateVerifyIdentifierAttribute: "id",
				ImportStateIdFunc:                    importIDFunc("mixpanel_project.test", "id", "organization_id"),
				ImportStateVerifyIgnore:              []string{"api_key", "api_secret", "timezone_name", "token", "url"},
			},
		},
	})
}
