// Code generated by gen/crudgen.py. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-go/tftypes"

	"github.com/mixpanel/terraform-provider-mixpanel/internal/client"
	rsc "github.com/mixpanel/terraform-provider-mixpanel/internal/provider/resource_project"
)

var (
	_ resource.Resource                = (*ProjectResource)(nil)
	_ resource.ResourceWithConfigure   = (*ProjectResource)(nil)
	_ resource.ResourceWithImportState = (*ProjectResource)(nil)
)

// keep the generated schema package and schema builder imported.
var _ = schema.StringAttribute{}

// keep the types package imported (used by nested schema overrides).
var _ = types.NumberType

// NewProjectResource constructs the project resource.
func NewProjectResource() resource.Resource {
	return &ProjectResource{}
}

type ProjectResource struct {
	client *client.Client
}

func (r *ProjectResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_project"
}

func (r *ProjectResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	s := rsc.ProjectResourceSchema(ctx)
	requireReplace(s.Attributes, "name", "organization_id")
	stabilizeComputed(s.Attributes)
	resp.Schema = s
}

func (r *ProjectResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}
	r.client = c
}

// projectID resolves the project from the project project_id attribute (if any)
// falling back to the provider default.
func (r *ProjectResource) projectID(ctx context.Context, raw tftypes.Value) (string, error) {
	oid, err := stringAttrFromRaw(raw, "organization_id")
	if err == nil && oid != "" {
		return r.client.OrganizationID(oid), nil
	}
	return r.client.OrganizationID(""), nil
}

func (r *ProjectResource) collectionPath(projectID string) string {
	return strings.NewReplacer("{organization_id}", projectID).Replace("/organizations/{organization_id}/projects/")
}

func (r *ProjectResource) instancePath(projectID, id string) string {
	return strings.NewReplacer("{organization_id}", projectID, "{id}", id).Replace("")
}

func (r *ProjectResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	projectID, err := r.projectID(ctx, req.Plan.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving organization_id", err.Error())
		return
	}
	matchVal, err := stringAttrFromRaw(req.Plan.Raw, "name")
	if err != nil {
		resp.Diagnostics.AddError("Reading project name", err.Error())
		return
	}
	createPath := strings.NewReplacer("{organization_id}", projectID).Replace("/organizations/{organization_id}/create-projects/")
	createBody := map[string]any{"projectNames": []any{matchVal}}
	respBody, err := r.client.Do(ctx, "POST", createPath, createBody)
	if err != nil {
		resp.Diagnostics.AddError("Creating project", err.Error())
		return
	}
	wire, id, err := selectNewestFromList(respBody, true, "id", "name", matchVal)
	if err != nil {
		resp.Diagnostics.AddError("Decoding project response", err.Error())
		return
	}
	if id == "" {
		resp.Diagnostics.AddError("Creating project", "create response did not contain the new project (no element matching name)")
		return
	}
	r.writeProjectState(ctx, &resp.State, &resp.Diagnostics, req.Plan.Raw, wire, projectID, id)
}

func (r *ProjectResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	projectID, err := r.projectID(ctx, req.State.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving project_id", err.Error())
		return
	}
	id, err := stringAttrFromRaw(req.State.Raw, "id")
	if err != nil {
		resp.Diagnostics.AddError("Reading project id", err.Error())
		return
	}
	respBody, err := r.client.Do(ctx, "GET", r.collectionPath(projectID), nil)
	if err != nil {
		if apiErr, ok := err.(*client.APIError); ok && apiErr.StatusCode == 404 {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Reading project", err.Error())
		return
	}
	wire, found, err := findInList(respBody, true, "id", id)
	if err != nil {
		resp.Diagnostics.AddError("Decoding project response", err.Error())
		return
	}
	if !found {
		resp.State.RemoveResource(ctx)
		return
	}
	// Merge against prior state: the list item may omit user-managed fields the
	// API never echoes back; preserve those instead of clobbering to null.
	r.writeProjectState(ctx, &resp.State, &resp.Diagnostics, req.State.Raw, wire, projectID, id)
}

func (r *ProjectResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	// project has no update operation in the API (create/read/delete only). Every
	// user-settable attribute is marked RequiresReplace in Schema (via the
	// requireReplace helper), so a changed attribute is planned as a replacement
	// and this method is never reached for a real diff. It remains as a defensive
	// backstop: fail loudly rather than silently copy the plan into state (which
	// would report success while leaving the server unchanged).
	resp.Diagnostics.AddError(
		"project does not support in-place update",
		"This resource's API has no update operation; changing an attribute replaces the resource. "+
			"Reaching this error is unexpected (attributes are marked RequiresReplace) — please report it.",
	)
}

func (r *ProjectResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	projectID, err := r.projectID(ctx, req.State.Raw)
	if err != nil {
		resp.Diagnostics.AddError("Resolving organization_id", err.Error())
		return
	}
	id, err := stringAttrFromRaw(req.State.Raw, "id")
	if err != nil {
		resp.Diagnostics.AddError("Reading project id", err.Error())
		return
	}
	delPath := strings.NewReplacer("{organization_id}", projectID).Replace("/organizations/{organization_id}/delete-projects/")
	delBody := map[string]any{"projectIds": []any{jsonNumberOrString(id)}}
	if _, err := r.client.Do(ctx, "POST", delPath, delBody); err != nil {
		if apiErr, ok := err.(*client.APIError); ok && (apiErr.StatusCode == 404) {
			return
		}
		resp.Diagnostics.AddError("Deleting project", err.Error())
		return
	}
}

func (r *ProjectResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.SplitN(req.ID, ":", 2)
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		resp.Diagnostics.AddError(
			"Invalid import ID",
			fmt.Sprintf("expected import ID in the form \"organization_id:<id>\", got %q", req.ID),
		)
		return
	}
	setImportID(ctx, &resp.State, &resp.Diagnostics, "organization_id", parts[0], "int64")
	setImportID(ctx, &resp.State, &resp.Diagnostics, "id", parts[1], "int64")
}

// writeProjectState turns an unwrapped API body into resource state. base is the
// planned raw value (req.Plan.Raw) on create/update so config-supplied values are
// preserved verbatim, or a null tftypes.Value on read (state is rebuilt from the
// API response alone). See client.RawFromWireMerged for the merge semantics.
func (r *ProjectResource) writeProjectState(ctx context.Context, state *tfsdk.State, diags *diagAppender, base tftypes.Value, wire map[string]any, projectID, id string) {
	extras := map[string]any{
		"id": id,
	}
	if projectID != "" {
		extras["organization_id"] = projectID
	}
	schemaType := state.Schema.Type().TerraformType(ctx)
	val, err := client.RawFromWireMerged(schemaType, base, wire, extras, ProjectAttrSpec())
	if err != nil {
		diags.AddError("Building project state", err.Error())
		return
	}
	state.Raw = val
}

// idForProject extracts the identity value from an unwrapped response body.
func idForProject(wire map[string]any) string {
	if v, ok := client.IDFromWire(wire, "id"); ok {
		return v
	}
	if v, ok := nestedID(wire, "id"); ok {
		return v
	}
	return ""
}

// unwrapProject unwraps the API envelope (when enveloped) and returns the body map.
func unwrapProject(respBody []byte) (map[string]any, error) {
	body, err := unwrapBody(respBody, true)
	if err != nil {
		return nil, err
	}
	return unwrapResultsMap(body, false), nil
}
