// Code generated by gen/crudgen.py (rpc_assoc). DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/mixpanel/terraform-provider-mixpanel/internal/client"
	rsc "github.com/mixpanel/terraform-provider-mixpanel/internal/provider/resource_service_account_project"
)

var (
	_ resource.Resource                = (*ServiceAccountProjectResource)(nil)
	_ resource.ResourceWithConfigure   = (*ServiceAccountProjectResource)(nil)
	_ resource.ResourceWithImportState = (*ServiceAccountProjectResource)(nil)
)

// NewServiceAccountProjectResource constructs the service_account_project RPC association resource.
func NewServiceAccountProjectResource() resource.Resource {
	return &ServiceAccountProjectResource{}
}

type ServiceAccountProjectResource struct {
	client *client.Client
}

// ServiceAccountProjectModel is the typed state model for the service_account_project association.
type ServiceAccountProjectModel struct {
	ID             types.String `tfsdk:"id"`
	OrganizationID types.String `tfsdk:"organization_id"`
	Key            types.String `tfsdk:"key"`
	Payload        types.String `tfsdk:"payload"`
}

func (r *ServiceAccountProjectResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_service_account_project"
}

func (r *ServiceAccountProjectResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = rsc.ServiceAccountProjectResourceSchema(ctx)
}

func (r *ServiceAccountProjectResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}
	r.client = c
}

// orgID resolves the organization scope from the model (falling back to the
// provider default organization).
func (r *ServiceAccountProjectResource) orgID(m *ServiceAccountProjectModel) string {
	if !m.OrganizationID.IsNull() && !m.OrganizationID.IsUnknown() && m.OrganizationID.ValueString() != "" {
		return r.client.OrganizationID(m.OrganizationID.ValueString())
	}
	return r.client.OrganizationID("")
}

// decodePayload parses the jsonencode payload string into a request body.
func (r *ServiceAccountProjectResource) decodePayload(raw string) (any, error) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return map[string]any{}, nil
	}
	var body any
	if err := json.Unmarshal([]byte(raw), &body); err != nil {
		return nil, fmt.Errorf("payload is not valid JSON: %w", err)
	}
	return body, nil
}

func (r *ServiceAccountProjectResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var m ServiceAccountProjectModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	org := r.orgID(&m)
	body, err := r.decodePayload(m.Payload.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Encoding service_account_project payload", err.Error())
		return
	}
	createPath := strings.NewReplacer("{organization_id}", org).Replace("/organizations/{organization_id}/add-to-project/")
	if _, err := r.client.Do(ctx, "POST", createPath, body); err != nil {
		resp.Diagnostics.AddError("Creating service_account_project", err.Error())
		return
	}
	m.OrganizationID = types.StringValue(org)
	m.ID = types.StringValue(org + ":" + m.Key.ValueString())
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}

func (r *ServiceAccountProjectResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var m ServiceAccountProjectModel
	resp.Diagnostics.Append(req.State.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	org := r.orgID(&m)
	listPath := strings.NewReplacer("{organization_id}", org).Replace("/organizations/{organization_id}/service-accounts")
	respBody, err := r.client.Do(ctx, "GET", listPath, nil)
	if err != nil {
		if apiErr, ok := err.(*client.APIError); ok && apiErr.StatusCode == 404 {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Reading service_account_project", err.Error())
		return
	}
	unwrapped, err := client.UnwrapEnvelope(respBody)
	if err != nil {
		// Tolerate an un-enveloped body (search the raw bytes).
		unwrapped = respBody
	}
	if !rpcAssocKeyPresent(unwrapped, m.Key.ValueString()) {
		resp.State.RemoveResource(ctx)
		return
	}
	// The association still exists; preserve the config-owned columns and refresh
	// the synthetic identity.
	m.OrganizationID = types.StringValue(org)
	m.ID = types.StringValue(org + ":" + m.Key.ValueString())
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}

func (r *ServiceAccountProjectResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	// service_account_project has no update verb: key, payload and organization_id all force
	// replacement, so a real change recreates the association. This persists the
	// plan defensively (Update is only reached when nothing meaningful changed).
	var m ServiceAccountProjectModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	org := r.orgID(&m)
	m.OrganizationID = types.StringValue(org)
	m.ID = types.StringValue(org + ":" + m.Key.ValueString())
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}

func (r *ServiceAccountProjectResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var m ServiceAccountProjectModel
	resp.Diagnostics.Append(req.State.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	org := r.orgID(&m)
	body, err := r.decodePayload(m.Payload.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Encoding service_account_project delete payload", err.Error())
		return
	}
	deletePath := strings.NewReplacer("{organization_id}", org).Replace("/organizations/{organization_id}/remove-from-project/")
	if _, err := r.client.Do(ctx, "POST", deletePath, body); err != nil {
		if apiErr, ok := err.(*client.APIError); ok && apiErr.StatusCode == 404 {
			return
		}
		resp.Diagnostics.AddError("Deleting service_account_project", err.Error())
		return
	}
}

func (r *ServiceAccountProjectResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
