// Code generated by gen/crudgen.py (rpc_assoc). DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/mixpanel/terraform-provider-mixpanel/internal/client"
	rsc "github.com/mixpanel/terraform-provider-mixpanel/internal/provider/resource_team"
)

var (
	_ resource.Resource                = (*TeamResource)(nil)
	_ resource.ResourceWithConfigure   = (*TeamResource)(nil)
	_ resource.ResourceWithImportState = (*TeamResource)(nil)
)

// NewTeamResource constructs the team RPC association resource.
func NewTeamResource() resource.Resource {
	return &TeamResource{}
}

type TeamResource struct {
	client *client.Client
}

// TeamModel is the typed state model for the team association.
type TeamModel struct {
	ID             types.String `tfsdk:"id"`
	OrganizationID types.String `tfsdk:"organization_id"`
	Key            types.String `tfsdk:"key"`
	Payload        types.String `tfsdk:"payload"`
}

func (r *TeamResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_team"
}

func (r *TeamResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = rsc.TeamResourceSchema(ctx)
}

func (r *TeamResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}
	r.client = c
}

// orgID resolves the organization scope from the model (falling back to the
// provider default organization).
func (r *TeamResource) orgID(m *TeamModel) string {
	if !m.OrganizationID.IsNull() && !m.OrganizationID.IsUnknown() && m.OrganizationID.ValueString() != "" {
		return r.client.OrganizationID(m.OrganizationID.ValueString())
	}
	return r.client.OrganizationID("")
}

// decodePayload parses the jsonencode payload string into a request body.
func (r *TeamResource) decodePayload(raw string) (any, error) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return map[string]any{}, nil
	}
	var body any
	if err := json.Unmarshal([]byte(raw), &body); err != nil {
		return nil, fmt.Errorf("payload is not valid JSON: %w", err)
	}
	return body, nil
}

func (r *TeamResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var m TeamModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	org := r.orgID(&m)
	body, err := r.decodePayload(m.Payload.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Encoding team payload", err.Error())
		return
	}
	createPath := strings.NewReplacer("{organization_id}", org).Replace("/organizations/{organization_id}/add-teams/")
	if _, err := r.client.Do(ctx, "POST", createPath, body); err != nil {
		resp.Diagnostics.AddError("Creating team", err.Error())
		return
	}
	m.OrganizationID = types.StringValue(org)
	m.ID = types.StringValue(org + ":" + m.Key.ValueString())
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}

func (r *TeamResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var m TeamModel
	resp.Diagnostics.Append(req.State.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	org := r.orgID(&m)
	listPath := strings.NewReplacer("{organization_id}", org).Replace("/organizations/{organization_id}/teams")
	respBody, err := r.client.Do(ctx, "GET", listPath, nil)
	if err != nil {
		if apiErr, ok := err.(*client.APIError); ok && apiErr.StatusCode == 404 {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Reading team", err.Error())
		return
	}
	unwrapped, err := client.UnwrapEnvelope(respBody)
	if err != nil {
		// Tolerate an un-enveloped body (search the raw bytes).
		unwrapped = respBody
	}
	if !rpcAssocKeyPresent(unwrapped, m.Key.ValueString()) {
		resp.State.RemoveResource(ctx)
		return
	}
	// The association still exists; preserve the config-owned columns and refresh
	// the synthetic identity.
	m.OrganizationID = types.StringValue(org)
	m.ID = types.StringValue(org + ":" + m.Key.ValueString())
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}

func (r *TeamResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var m TeamModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	org := r.orgID(&m)
	body, err := r.decodePayload(m.Payload.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Encoding team update payload", err.Error())
		return
	}
	updatePath := strings.NewReplacer("{organization_id}", org, "{key}", m.Key.ValueString()).Replace("/organizations/{organization_id}/teams/{key}/update/")
	if _, err := r.client.Do(ctx, "POST", updatePath, body); err != nil {
		resp.Diagnostics.AddError("Updating team", err.Error())
		return
	}
	m.OrganizationID = types.StringValue(org)
	m.ID = types.StringValue(org + ":" + m.Key.ValueString())
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
}

func (r *TeamResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var m TeamModel
	resp.Diagnostics.Append(req.State.Get(ctx, &m)...)
	if resp.Diagnostics.HasError() {
		return
	}
	org := r.orgID(&m)
	body, err := r.decodePayload(m.Payload.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Encoding team delete payload", err.Error())
		return
	}
	deletePath := strings.NewReplacer("{organization_id}", org).Replace("/organizations/{organization_id}/delete-teams/")
	if _, err := r.client.Do(ctx, "POST", deletePath, body); err != nil {
		if apiErr, ok := err.(*client.APIError); ok && apiErr.StatusCode == 404 {
			return
		}
		resp.Diagnostics.AddError("Deleting team", err.Error())
		return
	}
}

func (r *TeamResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
