// Code generated by gen/crudgen.py. DO NOT EDIT.

package provider

import "github.com/mixpanel/terraform-provider-mixpanel/internal/client"

// ThemeAttrSpec describes the synthetic / jsonencode attributes of the theme
// entity to the generic tftypes<->JSON bridge in the client package. It is shared
// by the theme resource and data source.
func ThemeAttrSpec() client.AttrSpec {
	return client.AttrSpec{
		IDAttr:            "theme_id",
		ProjectIDAttr:     "project_id",
		PathParamAttrs:    map[string]bool{},
		JSONEncodeAttrs:   map[string]bool{"data": true},
		JSONStringAttrs:   map[string]bool{},
		JSONEncodeWireKey: map[string]string{},
		OutputOnlyAttrs:   map[string]bool{},
		SpreadAttrs:       map[string]bool{},
	}
}
