// Code generated by gen/crudgen.py. DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/plancheck"
)

func TestAccWorkspace_lifecycle(t *testing.T) {
	srv := newMockServer(t, mockOpts{enveloped: true, idField: "id", stringID: false, resultsMap: false, upsert: false, listCreate: false})

	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: testProtoV6,
		Steps: []resource.TestStep{
			{
				// Create; the implicit post-apply refresh+plan asserts idempotency.
				Config: providerConfig(srv.URL, `
resource "mixpanel_workspace" "test" {
  is_restricted = false
  is_visible = false
  name = "tf-acc-test"
}`),
			},
			{
				// A changed attribute must plan as the expected action.
				Config: providerConfig(srv.URL, `
resource "mixpanel_workspace" "test" {
  is_restricted = true
  is_visible = false
  name = "tf-acc-test"
}`),
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction("mixpanel_workspace.test", plancheck.ResourceActionUpdate),
					},
				},
			},
		},
	})
}
