// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_mixpanel

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func MixpanelProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type MixpanelModel struct {
}
