# Bulk-import every annotation in a Mixpanel project into Terraform state.
#
# Flow (Terraform / OpenTofu 1.12):
#   terraform init
#   terraform plan -generate-config-out=generated.tf   # scaffold resource bodies
#   # review generated.tf (config generation is experimental — see docs/guides/import.md)
#   terraform apply                                     # perform the imports
#   terraform plan                                      # iterate until: No changes.
#
# See docs/guides/import.md for the full guide, import-ID formats per scope,
# and gotchas (write-only secrets, normalization drift, etc.).

terraform {
  required_providers {
    mixpanel = {
      source = "mixpanel/mixpanel"
    }
  }
}

variable "mixpanel_service_account" {
  type        = string
  description = "Mixpanel service account name."
}

variable "mixpanel_service_account_secret" {
  type        = string
  description = "Mixpanel service account secret."
  sensitive   = true
}

variable "mixpanel_project_id" {
  type        = string
  description = "Project to import annotations from."
  default     = "2195193"
}

provider "mixpanel" {
  # Credentials may also be supplied via the MIXPANEL_SERVICE_ACCOUNT,
  # MIXPANEL_SERVICE_ACCOUNT_SECRET, and MIXPANEL_PROJECT_ID env vars.
  service_account        = var.mixpanel_service_account
  service_account_secret = var.mixpanel_service_account_secret
  project_id             = var.mixpanel_project_id
}

# List every annotation in the project. `import_ids` emits the
# "PROJECT_ID:ID" composite import id for each one, ready for for_each.
data "mixpanel_annotations" "all" {
  project_id = var.mixpanel_project_id
}

# One import block instance per annotation. each.key and each.value are both
# the composite import id (the set is keyed by its own elements).
import {
  for_each = toset(data.mixpanel_annotations.all.import_ids)
  to       = mixpanel_annotation.this[each.key]
  id       = each.value
}

# One resource instance per annotation. The body is generated by
# `terraform plan -generate-config-out=generated.tf`, then reviewed and edited.
# Annotation attributes: date, description, user, user_id (writable);
# id, project_id, annotation_id are computed.
resource "mixpanel_annotation" "this" {
  for_each = toset(data.mixpanel_annotations.all.import_ids)
}

# Convenience: the composite import ids that were imported.
output "imported_annotation_ids" {
  value = data.mixpanel_annotations.all.import_ids
}
